export type TipoDocumento =
  | 'cotizacion'
  | 'factura'
  | 'nota_credito'
  | 'pago_cliente'
  | 'orden_servicio'
  | 'pedido'
  | 'remision'
  | 'orden_entrega'
  | 'requisicion'
  | 'orden_compra'
  | 'recepcion'
  | 'nota_credito_compra'
  | 'pago_proveedor'
  | 'factura_compra';
