"use client"
import { useCallback,useEffect,useState } from "react"
import { Gavel,Plus } from "lucide-react"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { Textarea } from "@/components/ui/textarea"
import { Empty,EmptyDescription,EmptyHeader,EmptyMedia,EmptyTitle } from "@/components/ui/empty"
import { createDecision,listDecisiones,listFrentes,type Decision,type Frente } from "../../../services/compassService"
const hoy=()=>new Date().toISOString().slice(0,10)
export function DecisionesView(){const [items,setItems]=useState<Decision[]>([]);const [frentes,setFrentes]=useState<Frente[]>([]);const [open,setOpen]=useState(false);const [titulo,setTitulo]=useState("");const [descripcion,setDescripcion]=useState("");const [motivo,setMotivo]=useState("");const [fecha,setFecha]=useState(hoy);const [frente,setFrente]=useState("");const [error,setError]=useState("")
 const load=useCallback(async()=>{try{setError("");const[d,f]=await Promise.all([listDecisiones(),listFrentes(["activo","pausado","completado","archivado"])]);setItems(d);setFrentes(f)}catch(e){setError(e instanceof Error?e.message:"No se pudieron cargar las Decisiones")}},[]);useEffect(()=>{void load()},[load])
 async function save(){await createDecision({titulo:titulo.trim(),descripcion:descripcion.trim()||null,motivo:motivo.trim()||null,fecha,frente_id:frente?Number(frente):null});setOpen(false);setTitulo("");setDescripcion("");setMotivo("");setFrente("");await load()}
 return <div className="flex flex-col gap-8"><header className="flex items-start justify-between gap-3"><div><h1 className="font-heading text-3xl tracking-tight">Decisiones</h1><p className="mt-2 text-sm text-muted-foreground">Un registro de qué decidiste y por qué.</p></div><Button onClick={()=>setOpen(true)}><Plus/>Nueva</Button></header>{error&&<p className="text-sm text-destructive">{error}</p>}{items.length===0?<Empty><EmptyHeader><EmptyMedia variant="icon"><Gavel/></EmptyMedia><EmptyTitle>Sin decisiones registradas</EmptyTitle><EmptyDescription>Las decisiones que captures aparecerán aquí.</EmptyDescription></EmptyHeader></Empty>:<div className="flex flex-col gap-2">{items.map(d=><div key={d.id} className="flex flex-col gap-2 rounded-xl border border-border bg-card px-4 py-3.5"><p className="text-sm">{d.titulo}</p>{d.descripcion&&<p className="text-sm text-muted-foreground">{d.descripcion}</p>}{d.motivo&&<p className="text-sm text-muted-foreground">Motivo: {d.motivo}</p>}<div className="flex justify-between border-t border-border pt-2.5 text-xs text-muted-foreground"><span>{d.frente_nombre??"Sin Frente"}</span><span>{d.fecha}</span></div></div>)}</div>}{open&&<div className="fixed inset-0 z-[1300] flex items-end justify-center bg-black/20 sm:items-center sm:p-4"><div className="w-full max-w-lg rounded-t-2xl border border-border bg-popover p-5 sm:rounded-2xl"><h2 className="font-heading text-xl">Nueva Decisión</h2><div className="mt-4 flex flex-col gap-3"><Input value={titulo} onChange={e=>setTitulo(e.target.value)} placeholder="Qué decidiste"/><Textarea value={descripcion} onChange={e=>setDescripcion(e.target.value)} placeholder="Descripción opcional"/><Textarea value={motivo} onChange={e=>setMotivo(e.target.value)} placeholder="Motivo opcional"/><div className="grid grid-cols-2 gap-3"><Input type="date" value={fecha} onChange={e=>setFecha(e.target.value)}/><select value={frente} onChange={e=>setFrente(e.target.value)} className="h-9 rounded-md border border-input bg-transparent px-3 text-sm"><option value="">Sin Frente</option>{frentes.map(f=><option key={f.id} value={f.id}>{f.nombre}</option>)}</select></div></div><div className="mt-5 flex justify-end gap-2"><Button variant="ghost" onClick={()=>setOpen(false)}>Cancelar</Button><Button onClick={()=>void save()} disabled={!titulo.trim()}>Guardar</Button></div></div></div>}</div>
}

