import { Router } from 'express';
import multer from 'multer';
import path from 'path';
import fs from 'fs/promises';
import crypto from 'crypto';
import { requireAuth, requireEmpresaActiva } from '../auth/auth.middleware';
import pool from '../../config/database';
import { adjuntosStorageRoot, resolverAdjuntoPath, eliminarArchivosAdjuntos } from '../documentacion/adjuntos.files';

const router=Router();
const allowed=new Set(['application/pdf','image/jpeg','image/png','image/webp']);
const upload=multer({storage:multer.memoryStorage(),limits:{fileSize:16*1024*1024},fileFilter:(_req,file,cb)=>cb(null,allowed.has(file.mimetype))});
const belongs=async(empresaId:number,id:number)=>(await pool.query('SELECT id FROM public.contactos WHERE id=$1 AND empresa_id=$2',[id,empresaId])).rowCount===1;
router.use(requireAuth,requireEmpresaActiva);

// Legacy type administration remains available for rollback; new uploads use the common catalog.
router.get('/tipos-documentacion',async(_req,res)=>res.json((await pool.query('SELECT id,nombre,orden FROM public.contactos_documentacion_tipos WHERE activo=true ORDER BY orden,nombre,id')).rows));
router.get('/tipos-documentacion/admin',async(_req,res)=>res.json((await pool.query('SELECT id,nombre,orden,activo,created_at,updated_at FROM public.contactos_documentacion_tipos ORDER BY orden,nombre,id')).rows));
router.post('/tipos-documentacion',async(req:any,res)=>{const nombre=String(req.body?.nombre??'').trim(),orden=Number(req.body?.orden??100);if(!nombre||!Number.isInteger(orden)||orden<0)return res.status(400).json({message:'Datos de tipo inválidos'});try{return res.status(201).json((await pool.query('INSERT INTO public.contactos_documentacion_tipos(nombre,orden,activo) VALUES($1,$2,$3) RETURNING *',[nombre,orden,req.body?.activo!==false])).rows[0]);}catch(e:any){if(e?.code==='23505')return res.status(409).json({message:'Ya existe ese tipo'});throw e;}});
router.put('/tipos-documentacion/:id',async(req:any,res)=>{const r=await pool.query('UPDATE public.contactos_documentacion_tipos SET nombre=$1,orden=$2,activo=$3,updated_at=now() WHERE id=$4 RETURNING *',[String(req.body?.nombre??'').trim(),Number(req.body?.orden??100),req.body?.activo!==false,req.params.id]);if(!r.rowCount)return res.status(404).json({message:'Tipo no encontrado'});return res.json(r.rows[0]);});
router.patch('/tipos-documentacion/:id/estado',async(req:any,res)=>{const r=await pool.query('UPDATE public.contactos_documentacion_tipos SET activo=$1,updated_at=now() WHERE id=$2 RETURNING *',[req.body?.activo===true,req.params.id]);if(!r.rowCount)return res.status(404).json({message:'Tipo no encontrado'});return res.json(r.rows[0]);});

router.get('/:contactoId/documentacion',async(req:any,res)=>{const empresa=Number(req.context.empresaId),contacto=Number(req.params.contactoId);if(!(await belongs(empresa,contacto)))return res.status(404).json({message:'Contacto no encontrado'});const r=await pool.query(`SELECT a.id,t.nombre AS tipo,a.nombre_original,a.mime_type,a.tamano,a.fecha_vencimiento,a.comentarios,a.created_at AS fecha_subida,u.nombre AS usuario_nombre,u.email AS usuario_email FROM documentacion.adjuntos a JOIN documentacion.adjuntos_entidades e ON e.adjunto_id=a.id AND e.contacto_id=$2 LEFT JOIN documentacion.adjuntos_tipos t ON t.id=a.tipo_id LEFT JOIN core.usuarios u ON u.id=a.creado_por WHERE a.empresa_id=$1 ORDER BY a.created_at DESC`,[empresa,contacto]);return res.json(r.rows.map(x=>({...x,preview_posible:x.mime_type==='application/pdf'||String(x.mime_type).startsWith('image/')})));});
router.post('/:contactoId/documentacion',upload.single('archivo'),async(req:any,res)=>{const empresa=Number(req.context.empresaId),contacto=Number(req.params.contactoId);if(!(await belongs(empresa,contacto)))return res.status(404).json({message:'Contacto no encontrado'});if(!req.file)return res.status(400).json({message:'Archivo requerido o tipo no permitido'});const legacyType=await pool.query('SELECT nombre FROM public.contactos_documentacion_tipos WHERE id=$1 AND activo=true',[req.body.tipo_id]);if(!legacyType.rowCount)return res.status(400).json({message:'Tipo de documentación inválido'});const normalized=String(legacyType.rows[0].nombre).toLowerCase()==='constancia fiscal'?'Constancia de situación fiscal':String(legacyType.rows[0].nombre).trim();const type=await pool.query('SELECT id FROM documentacion.adjuntos_tipos WHERE lower(nombre)=lower($1) AND activo=true',[normalized]);if(!type.rowCount)return res.status(400).json({message:'Tipo común no disponible'});const key=`${empresa}/${crypto.randomUUID()}${path.extname(req.file.originalname).toLowerCase()}`,file=path.join(adjuntosStorageRoot(),key);await fs.mkdir(path.dirname(file),{recursive:true});await fs.writeFile(file,req.file.buffer);const client=await pool.connect();try{await client.query('BEGIN');const a=await client.query(`INSERT INTO documentacion.adjuntos(empresa_id,tipo_id,nombre_original,mime_type,tamano,storage_key,fecha_vencimiento,comentarios,creado_por) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9) RETURNING id`,[empresa,type.rows[0].id,req.file.originalname,req.file.mimetype,req.file.size,key,req.body.fecha_vencimiento||null,req.body.comentarios||null,req.auth.userId]);await client.query('INSERT INTO documentacion.adjuntos_entidades(adjunto_id,contacto_id) VALUES($1,$2)',[a.rows[0].id,contacto]);await client.query('COMMIT');return res.status(201).json({id:a.rows[0].id});}catch(e){await client.query('ROLLBACK').catch(()=>undefined);await fs.unlink(file).catch(()=>undefined);throw e;}finally{client.release();}});
router.get('/:contactoId/documentacion/:id/archivo',async(req:any,res)=>{const empresa=Number(req.context.empresaId),contacto=Number(req.params.contactoId);const r=await pool.query('SELECT a.storage_key,a.nombre_original,a.mime_type FROM documentacion.adjuntos a JOIN documentacion.adjuntos_entidades e ON e.adjunto_id=a.id AND e.contacto_id=$3 WHERE a.id=$1 AND a.empresa_id=$2',[req.params.id,empresa,contacto]);if(!r.rowCount)return res.status(404).json({message:'Documentación no encontrada'});try{const file=resolverAdjuntoPath(r.rows[0].storage_key);await fs.access(file);res.setHeader('Content-Type',r.rows[0].mime_type);return res.download(file,r.rows[0].nombre_original);}catch{return res.status(404).json({message:'Archivo no encontrado'});}});
router.delete('/:contactoId/documentacion/:id',async(req:any,res)=>{const empresa=Number(req.context.empresaId),contacto=Number(req.params.contactoId),r=await pool.query('SELECT a.id,a.storage_key FROM documentacion.adjuntos a JOIN documentacion.adjuntos_entidades e ON e.adjunto_id=a.id AND e.contacto_id=$3 WHERE a.id=$1 AND a.empresa_id=$2',[req.params.id,empresa,contacto]);if(!r.rowCount)return res.status(404).json({message:'Documentación no encontrada'});await pool.query('DELETE FROM documentacion.adjuntos WHERE id=$1',[r.rows[0].id]);const failures=await eliminarArchivosAdjuntos([{adjuntoId:r.rows[0].id,empresaId:empresa,storageKey:r.rows[0].storage_key}]);if(failures)return res.status(500).json({message:'Registro eliminado, limpieza física pendiente'});return res.status(204).send();});
export default router;
