-- =========================================================
-- insert_sat_codigos_agrupadores_hardcoded.sql
--
-- Carga/actualiza el catálogo oficial de códigos agrupadores de cuentas
-- (Anexo 24, Contabilidad Electrónica) en sat.codigos_agrupadores con
-- INSERT ... VALUES hardcodeados (sin \copy, sin depender de CSV ni de
-- configuración de importación de ningún cliente SQL como DBeaver).
--
-- Se agregó como alternativa a reimport_sat_codigos_agrupadores.sql
-- porque la importación de CSV desde DBeaver estaba convirtiendo campos
-- vacíos en cadena vacía '' en vez de NULL, lo cual viola
-- chk_codigos_agrupadores_naturaleza. Este script no depende de ningún
-- comportamiento de importación de cliente: los NULL están explícitos
-- en cada VALUES.
--
-- Fuente: PDF oficial "Código agrupador de cuentas del SAT", publicado
-- en:
--   - https://www.gob.mx/sat/documentos/codigo-agrupador-de-cuentas-del-sat
--   - http://omawww.sat.gob.mx/fichas_tematicas/buzon_tributario/Documents/codigo_agrupador.pdf
-- (ambas URLs sirven el mismo archivo, verificado por hash SHA-256
-- idéntico). Extraído el 2026-07-08.
--
-- Archivo CSV origen (se conserva por separado, no se modifica ni se
-- reemplaza por este script):
--   database/catalogos/sat/codigos_agrupadores_sat.csv
--
-- Total de registros esperados: 1,076.
--
-- La columna `naturaleza` (D/A) NO viene explícita en la fuente oficial
-- del SAT para el catálogo de códigos agrupadores: TODOS los registros
-- quedan con naturaleza NULL. No se inventó ni se infirió ningún valor.
--
-- La columna `nivel` viene explícita (1 o 2) solo para cuentas de nivel
-- mayor y subcuentas de primer nivel. 13 códigos no traen nivel en la
-- fuente oficial y quedan con nivel NULL: los encabezados de categoría
-- (100, 100.01, 100.02, 200, 200.01, 200.02, 300, 400, 500, 600, 700,
-- 800) y el código especial "000" (uso exclusivo del sector financiero,
-- cuyo nivel el propio PDF indica que depende del catálogo de cada
-- contribuyente, no es un valor fijo).
--
-- Idempotente: INSERT ... ON CONFLICT (codigo) DO UPDATE. No trunca la
-- tabla ni borra códigos existentes.
-- =========================================================

\set ON_ERROR_STOP on

BEGIN;

INSERT INTO sat.codigos_agrupadores (
    codigo,
    descripcion,
    nivel,
    naturaleza,
    activo
)
VALUES
    ('100', 'Activo', NULL, NULL, true),
    ('100.01', 'Activo a corto plazo', NULL, NULL, true),
    ('101', 'Caja', 1, NULL, true),
    ('101.01', 'Caja y efectivo', 2, NULL, true),
    ('102', 'Bancos', 1, NULL, true),
    ('102.01', 'Bancos nacionales', 2, NULL, true),
    ('102.02', 'Bancos extranjeros', 2, NULL, true),
    ('103', 'Inversiones', 1, NULL, true),
    ('103.01', 'Inversiones temporales', 2, NULL, true),
    ('103.02', 'Inversiones en fideicomisos', 2, NULL, true),
    ('103.03', 'Otras inversiones', 2, NULL, true),
    ('104', 'Otros instrumentos financieros', 1, NULL, true),
    ('104.01', 'Otros instrumentos financieros', 2, NULL, true),
    ('105', 'Clientes', 1, NULL, true),
    ('105.01', 'Clientes nacionales', 2, NULL, true),
    ('105.02', 'Clientes extranjeros', 2, NULL, true),
    ('105.03', 'Clientes nacionales parte relacionada', 2, NULL, true),
    ('105.04', 'Clientes extranjeros parte relacionada', 2, NULL, true),
    ('106', 'Cuentas y documentos por cobrar a corto plazo', 1, NULL, true),
    ('106.01', 'Cuentas y documentos por cobrar a corto plazo nacional', 2, NULL, true),
    ('106.02', 'Cuentas y documentos por cobrar a corto plazo extranjero', 2, NULL, true),
    ('106.03', 'Cuentas y documentos por cobrar a corto plazo nacional parte relacionada', 2, NULL, true),
    ('106.04', 'Cuentas y documentos por cobrar a corto plazo extranjero parte relacionada', 2, NULL, true),
    ('106.05', 'Intereses por cobrar a corto plazo nacional', 2, NULL, true),
    ('106.06', 'Intereses por cobrar a corto plazo extranjero', 2, NULL, true),
    ('106.07', 'Intereses por cobrar a corto plazo nacional parte relacionada', 2, NULL, true),
    ('106.08', 'Intereses por cobrar a corto plazo extranjero parte relacionada', 2, NULL, true),
    ('106.09', 'Otras cuentas y documentos por cobrar a corto plazo', 2, NULL, true),
    ('106.10', 'Otras cuentas y documentos por cobrar a corto plazo parte relacionada', 2, NULL, true),
    ('107', 'Deudores diversos', 1, NULL, true),
    ('107.01', 'Funcionarios y empleados', 2, NULL, true),
    ('107.02', 'Socios y accionistas', 2, NULL, true),
    ('107.03', 'Partes relacionadas nacionales', 2, NULL, true),
    ('107.04', 'Partes relacionadas extranjeros', 2, NULL, true),
    ('107.05', 'Otros deudores diversos', 2, NULL, true),
    ('108', 'Estimación de cuentas incobrables', 1, NULL, true),
    ('108.01', 'Estimación de cuentas incobrables nacional', 2, NULL, true),
    ('108.02', 'Estimación de cuentas incobrables extranjero', 2, NULL, true),
    ('108.03', 'Estimación de cuentas incobrables nacional parte relacionada', 2, NULL, true),
    ('108.04', 'Estimación de cuentas incobrables extranjero parte relacionada', 2, NULL, true),
    ('109', 'Pagos anticipados', 1, NULL, true),
    ('109.01', 'Seguros y fianzas pagados por anticipado nacional', 2, NULL, true),
    ('109.02', 'Seguros y fianzas pagados por anticipado extranjero', 2, NULL, true),
    ('109.03', 'Seguros y fianzas pagados por anticipado nacional parte relacionada', 2, NULL, true),
    ('109.04', 'Seguros y fianzas pagados por anticipado extranjero parte relacionada', 2, NULL, true),
    ('109.05', 'Rentas pagados por anticipado nacional', 2, NULL, true),
    ('109.06', 'Rentas pagados por anticipado extranjero', 2, NULL, true),
    ('109.07', 'Rentas pagados por anticipado nacional parte relacionada', 2, NULL, true),
    ('109.08', 'Rentas pagados por anticipado extranjero parte relacionada', 2, NULL, true),
    ('109.09', 'Intereses pagados por anticipado nacional', 2, NULL, true),
    ('109.10', 'Intereses pagados por anticipado extranjero', 2, NULL, true),
    ('109.11', 'Intereses pagados por anticipado nacional parte relacionada', 2, NULL, true),
    ('109.12', 'Intereses pagados por anticipado extranjero parte relacionada', 2, NULL, true),
    ('109.13', 'Factoraje financiero pagados por anticipado nacional', 2, NULL, true),
    ('109.14', 'Factoraje financiero pagados por anticipado extranjero', 2, NULL, true),
    ('109.15', 'Factoraje financiero pagados por anticipado nacional parte relacionada', 2, NULL, true),
    ('109.16', 'Factoraje financiero pagados por anticipado extranjero parte relacionada', 2, NULL, true),
    ('109.17', 'Arrendamiento financiero pagados por anticipado nacional', 2, NULL, true),
    ('109.18', 'Arrendamiento financiero pagados por anticipado extranjero', 2, NULL, true),
    ('109.19', 'Arrendamiento financiero pagados por anticipado nacional parte relacionada', 2, NULL, true),
    ('109.20', 'Arrendamiento financiero pagados por anticipado extranjero parte relacionada', 2, NULL, true),
    ('109.21', 'Pérdida por deterioro de pagos anticipados', 2, NULL, true),
    ('109.22', 'Derechos fiduciarios', 2, NULL, true),
    ('109.23', 'Otros pagos anticipados', 2, NULL, true),
    ('110', 'Subsidio al empleo por aplicar', 1, NULL, true),
    ('110.01', 'Subsidio al empleo por aplicar', 2, NULL, true),
    ('111', 'Crédito al diesel por acreditar', 1, NULL, true),
    ('111.01', 'Crédito al diesel por acreditar', 2, NULL, true),
    ('112', 'Otros estímulos', 1, NULL, true),
    ('112.01', 'Otros estímulos', 2, NULL, true),
    ('113', 'Impuestos a favor', 1, NULL, true),
    ('113.01', 'IVA a favor', 2, NULL, true),
    ('113.02', 'ISR a favor', 2, NULL, true),
    ('113.03', 'IETU a favor', 2, NULL, true),
    ('113.04', 'IDE a favor', 2, NULL, true),
    ('113.05', 'IA a favor', 2, NULL, true),
    ('113.06', 'Subsidio al empleo', 2, NULL, true),
    ('113.07', 'Pago de lo indebido', 2, NULL, true),
    ('113.08', 'Otros impuestos a favor', 2, NULL, true),
    ('114', 'Pagos provisionales', 1, NULL, true),
    ('114.01', 'Pagos provisionales de ISR', 2, NULL, true),
    ('115', 'Inventario', 1, NULL, true),
    ('115.01', 'Inventario', 2, NULL, true),
    ('115.02', 'Materia prima y materiales', 2, NULL, true),
    ('115.03', 'Producción en proceso', 2, NULL, true),
    ('115.04', 'Productos terminados', 2, NULL, true),
    ('115.05', 'Mercancías en tránsito', 2, NULL, true),
    ('115.06', 'Mercancías en poder de terceros', 2, NULL, true),
    ('115.07', 'Otros', 2, NULL, true),
    ('116', 'Estimación de inventarios obsoletos y de lento movimiento', 1, NULL, true),
    ('116.01', 'Estimación de inventarios obsoletos y de lento movimiento', 2, NULL, true),
    ('117', 'Obras en proceso de inmuebles', 1, NULL, true),
    ('117.01', 'Obras en proceso de inmuebles', 2, NULL, true),
    ('118', 'Impuestos acreditables pagados', 1, NULL, true),
    ('118.01', 'IVA acreditable pagado', 2, NULL, true),
    ('118.02', 'IVA acreditable de importación pagado', 2, NULL, true),
    ('118.03', 'IEPS acreditable pagado', 2, NULL, true),
    ('118.04', 'IEPS pagado en importación', 2, NULL, true),
    ('119', 'Impuestos acreditables por pagar', 1, NULL, true),
    ('119.01', 'IVA pendiente de pago', 2, NULL, true),
    ('119.02', 'IVA de importación pendiente de pago', 2, NULL, true),
    ('119.03', 'IEPS pendiente de pago', 2, NULL, true),
    ('119.04', 'IEPS pendiente de pago en importación', 2, NULL, true),
    ('120', 'Anticipo a proveedores', 1, NULL, true),
    ('120.01', 'Anticipo a proveedores nacional', 2, NULL, true),
    ('120.02', 'Anticipo a proveedores extranjero', 2, NULL, true),
    ('120.03', 'Anticipo a proveedores nacional parte relacionada', 2, NULL, true),
    ('120.04', 'Anticipo a proveedores extranjero parte relacionada', 2, NULL, true),
    ('121', 'Otros activos a corto plazo', 1, NULL, true),
    ('121.01', 'Otros activos a corto plazo', 2, NULL, true),
    ('100.02', 'Activo a largo plazo', NULL, NULL, true),
    ('151', 'Terrenos', 1, NULL, true),
    ('151.01', 'Terrenos', 2, NULL, true),
    ('152', 'Edificios', 1, NULL, true),
    ('152.01', 'Edificios', 2, NULL, true),
    ('153', 'Maquinaria y equipo', 1, NULL, true),
    ('153.01', 'Maquinaria y equipo', 2, NULL, true),
    ('154', 'Automóviles, autobuses, camiones de carga, tractocamiones, montacargas y remolques', 1, NULL, true),
    ('154.01', 'Automóviles, autobuses, camiones de carga, tractocamiones, montacargas y remolques', 2, NULL, true),
    ('155', 'Mobiliario y equipo de oficina', 1, NULL, true),
    ('155.01', 'Mobiliario y equipo de oficina', 2, NULL, true),
    ('156', 'Equipo de cómputo', 1, NULL, true),
    ('156.01', 'Equipo de cómputo', 2, NULL, true),
    ('157', 'Equipo de comunicación', 1, NULL, true),
    ('157.01', 'Equipo de comunicación', 2, NULL, true),
    ('158', 'Activos biológicos, vegetales y semovientes', 1, NULL, true),
    ('158.01', 'Activos biológicos, vegetales y semovientes', 2, NULL, true),
    ('159', 'Obras en proceso de activos fijos', 1, NULL, true),
    ('159.01', 'Obras en proceso de activos fijos', 2, NULL, true),
    ('160', 'Otros activos fijos', 1, NULL, true),
    ('160.01', 'Otros activos fijos', 2, NULL, true),
    ('161', 'Ferrocarriles', 1, NULL, true),
    ('161.01', 'Ferrocarriles', 2, NULL, true),
    ('162', 'Embarcaciones', 1, NULL, true),
    ('162.01', 'Embarcaciones', 2, NULL, true),
    ('163', 'Aviones', 1, NULL, true),
    ('163.01', 'Aviones', 2, NULL, true),
    ('164', 'Troqueles, moldes, matrices y herramental', 1, NULL, true),
    ('164.01', 'Troqueles, moldes, matrices y herramental', 2, NULL, true),
    ('165', 'Equipo de comunicaciones telefónicas', 1, NULL, true),
    ('165.01', 'Equipo de comunicaciones telefónicas', 2, NULL, true),
    ('166', 'Equipo de comunicación satelital', 1, NULL, true),
    ('166.01', 'Equipo de comunicación satelital', 2, NULL, true),
    ('167', 'Equipo de adaptaciones para personas con capacidades diferentes', 1, NULL, true),
    ('167.01', 'Equipo de adaptaciones para personas con capacidades diferentes', 2, NULL, true),
    ('168', 'Maquinaria y equipo de generación de energía de fuentes renovables o de sistemas de cogeneración de electricidad eficiente', 1, NULL, true),
    ('168.01', 'Maquinaria y equipo de generación de energía de fuentes renovables o de sistemas de cogeneración de electricidad eficiente', 2, NULL, true),
    ('169', 'Otra maquinaria y equipo', 1, NULL, true),
    ('169.01', 'Otra maquinaria y equipo', 2, NULL, true),
    ('170', 'Adaptaciones y mejoras', 1, NULL, true),
    ('170.01', 'Adaptaciones y mejoras', 2, NULL, true),
    ('171', 'Depreciación acumulada de activos fijos', 1, NULL, true),
    ('171.01', 'Depreciación acumulada de edificios', 2, NULL, true),
    ('171.02', 'Depreciación acumulada de maquinaria y equipo', 2, NULL, true),
    ('171.03', 'Depreciación acumulada de automóviles, autobuses, camiones de carga, tractocamiones, montacargas y remolques', 2, NULL, true),
    ('171.04', 'Depreciación acumulada de mobiliario y equipo de oficina', 2, NULL, true),
    ('171.05', 'Depreciación acumulada de equipo de cómputo', 2, NULL, true),
    ('171.06', 'Depreciación acumulada de equipo de comunicación', 2, NULL, true),
    ('171.07', 'Depreciación acumulada de activos biológicos, vegetales y semovientes', 2, NULL, true),
    ('171.08', 'Depreciación acumulada de otros activos fijos', 2, NULL, true),
    ('171.09', 'Depreciación acumulada de ferrocarriles', 2, NULL, true),
    ('171.10', 'Depreciación acumulada de embarcaciones', 2, NULL, true),
    ('171.11', 'Depreciación acumulada de aviones', 2, NULL, true),
    ('171.12', 'Depreciación acumulada de troqueles, moldes, matrices y herramental', 2, NULL, true),
    ('171.13', 'Depreciación acumulada de equipo de comunicaciones telefónicas', 2, NULL, true),
    ('171.14', 'Depreciación acumulada de equipo de comunicación satelital', 2, NULL, true),
    ('171.15', 'Depreciación acumulada de equipo de adaptaciones para personas con capacidades diferentes', 2, NULL, true),
    ('171.16', 'Depreciación acumulada de maquinaria y equipo de generación de energía de fuentes renovables o de sistemas de cogeneración de electricidad eficiente', 2, NULL, true),
    ('171.17', 'Depreciación acumulada de adaptaciones y mejoras', 2, NULL, true),
    ('171.18', 'Depreciación acumulada de otra maquinaria y equipo', 2, NULL, true),
    ('172', 'Pérdida por deterioro acumulado de activos fijos', 1, NULL, true),
    ('172.01', 'Pérdida por deterioro acumulado de edificios', 2, NULL, true),
    ('172.02', 'Pérdida por deterioro acumulado de maquinaria y equipo', 2, NULL, true),
    ('172.03', 'Pérdida por deterioro acumulado de automóviles, autobuses, camiones de carga, tractocamiones, montacargas y remolques', 2, NULL, true),
    ('172.04', 'Pérdida por deterioro acumulado de mobiliario y equipo de oficina', 2, NULL, true),
    ('172.05', 'Pérdida por deterioro acumulado de equipo de cómputo', 2, NULL, true),
    ('172.06', 'Pérdida por deterioro acumulado de equipo de comunicación', 2, NULL, true),
    ('172.07', 'Pérdida por deterioro acumulado de activos biológicos, vegetales y semovientes', 2, NULL, true),
    ('172.08', 'Pérdida por deterioro acumulado de otros activos fijos', 2, NULL, true),
    ('172.09', 'Pérdida por deterioro acumulado de ferrocarriles', 2, NULL, true),
    ('172.10', 'Pérdida por deterioro acumulado de embarcaciones', 2, NULL, true),
    ('172.11', 'Pérdida por deterioro acumulado de aviones', 2, NULL, true),
    ('172.12', 'Pérdida por deterioro acumulado de troqueles, moldes, matrices y herramental', 2, NULL, true),
    ('172.13', 'Pérdida por deterioro acumulado de equipo de comunicaciones telefónicas', 2, NULL, true),
    ('172.14', 'Pérdida por deterioro acumulado de equipo de comunicación satelital', 2, NULL, true),
    ('172.15', 'Pérdida por deterioro acumulado de equipo de adaptaciones para personas con capacidades diferentes', 2, NULL, true),
    ('172.16', 'Pérdida por deterioro acumulado de maquinaria y equipo de generación de energía de fuentes renovables o de sistemas de cogeneración de electricidad eficiente', 2, NULL, true),
    ('172.17', 'Pérdida por deterioro acumulado de adaptaciones y mejoras', 2, NULL, true),
    ('172.18', 'Pérdida por deterioro acumulado de otra maquinaria y equipo', 2, NULL, true),
    ('173', 'Gastos diferidos', 1, NULL, true),
    ('173.01', 'Gastos diferidos', 2, NULL, true),
    ('174', 'Gastos pre operativos', 1, NULL, true),
    ('174.01', 'Gastos pre operativos', 2, NULL, true),
    ('175', 'Regalías, asistencia técnica y otros gastos diferidos', 1, NULL, true),
    ('175.01', 'Regalías, asistencia técnica y otros gastos diferidos', 2, NULL, true),
    ('176', 'Activos intangibles', 1, NULL, true),
    ('176.01', 'Activos intangibles', 2, NULL, true),
    ('177', 'Gastos de organización', 1, NULL, true),
    ('177.01', 'Gastos de organización', 2, NULL, true),
    ('178', 'Investigación y desarrollo de mercado', 1, NULL, true),
    ('178.01', 'Investigación y desarrollo de mercado', 2, NULL, true),
    ('179', 'Marcas y patentes', 1, NULL, true),
    ('179.01', 'Marcas y patentes', 2, NULL, true),
    ('180', 'Crédito mercantil', 1, NULL, true),
    ('180.01', 'Crédito mercantil', 2, NULL, true),
    ('181', 'Gastos de instalación', 1, NULL, true),
    ('181.01', 'Gastos de instalación', 2, NULL, true),
    ('182', 'Otros activos diferidos', 1, NULL, true),
    ('182.01', 'Otros activos diferidos', 2, NULL, true),
    ('183', 'Amortización acumulada de activos diferidos', 1, NULL, true),
    ('183.01', 'Amortización acumulada de gastos diferidos', 2, NULL, true),
    ('183.02', 'Amortización acumulada de gastos pre operativos', 2, NULL, true),
    ('183.03', 'Amortización acumulada de regalías, asistencia técnica y otros gastos diferidos', 2, NULL, true),
    ('183.04', 'Amortización acumulada de activos intangibles', 2, NULL, true),
    ('183.05', 'Amortización acumulada de gastos de organización', 2, NULL, true),
    ('183.06', 'Amortización acumulada de investigación y desarrollo de mercado', 2, NULL, true),
    ('183.07', 'Amortización acumulada de marcas y patentes', 2, NULL, true),
    ('183.08', 'Amortización acumulada de crédito mercantil', 2, NULL, true),
    ('183.09', 'Amortización acumulada de gastos de instalación', 2, NULL, true),
    ('183.10', 'Amortización acumulada de otros activos diferidos', 2, NULL, true),
    ('184', 'Depósitos en garantía', 1, NULL, true),
    ('184.01', 'Depósitos de fianzas', 2, NULL, true),
    ('184.02', 'Depósitos de arrendamiento de bienes inmuebles', 2, NULL, true),
    ('184.03', 'Otros depósitos en garantía', 2, NULL, true),
    ('185', 'Impuestos diferidos', 1, NULL, true),
    ('185.01', 'Impuestos diferidos ISR', 2, NULL, true),
    ('186', 'Cuentas y documentos por cobrar a largo plazo', 1, NULL, true),
    ('186.01', 'Cuentas y documentos por cobrar a largo plazo nacional', 2, NULL, true),
    ('186.02', 'Cuentas y documentos por cobrar a largo plazo extranjero', 2, NULL, true),
    ('186.03', 'Cuentas y documentos por cobrar a largo plazo nacional parte relacionada', 2, NULL, true),
    ('186.04', 'Cuentas y documentos por cobrar a largo plazo extranjero parte relacionada', 2, NULL, true),
    ('186.05', 'Intereses por cobrar a largo plazo nacional', 2, NULL, true),
    ('186.06', 'Intereses por cobrar a largo plazo extranjero', 2, NULL, true),
    ('186.07', 'Intereses por cobrar a largo plazo nacional parte relacionada', 2, NULL, true),
    ('186.08', 'Intereses por cobrar a largo plazo extranjero parte relacionada', 2, NULL, true),
    ('186.09', 'Otras cuentas y documentos por cobrar a largo plazo', 2, NULL, true),
    ('186.10', 'Otras cuentas y documentos por cobrar a largo plazo parte relacionada', 2, NULL, true),
    ('187', 'Participación de los trabajadores en las utilidades diferidas', 1, NULL, true),
    ('187.01', 'Participación de los trabajadores en las utilidades diferidas', 2, NULL, true),
    ('188', 'Inversiones permanentes en acciones', 1, NULL, true),
    ('188.01', 'Inversiones a largo plazo en subsidiarias', 2, NULL, true),
    ('188.02', 'Inversiones a largo plazo en asociadas', 2, NULL, true),
    ('188.03', 'Otras inversiones permanentes en acciones', 2, NULL, true),
    ('189', 'Estimación por deterioro de inversiones permanentes en acciones', 1, NULL, true),
    ('189.01', 'Estimación por deterioro de inversiones permanentes en acciones', 2, NULL, true),
    ('190', 'Otros instrumentos financieros', 1, NULL, true),
    ('190.01', 'Otros instrumentos financieros', 2, NULL, true),
    ('191', 'Otros activos a largo plazo', 1, NULL, true),
    ('191.01', 'Otros activos a largo plazo', 2, NULL, true),
    ('200', 'Pasivo', NULL, NULL, true),
    ('200.01', 'Pasivo a corto plazo', NULL, NULL, true),
    ('201', 'Proveedores', 1, NULL, true),
    ('201.01', 'Proveedores nacionales', 2, NULL, true),
    ('201.02', 'Proveedores extranjeros', 2, NULL, true),
    ('201.03', 'Proveedores nacionales parte relacionada', 2, NULL, true),
    ('201.04', 'Proveedores extranjeros parte relacionada', 2, NULL, true),
    ('202', 'Cuentas por pagar a corto plazo', 1, NULL, true),
    ('202.01', 'Documentos por pagar bancario y financiero nacional', 2, NULL, true),
    ('202.02', 'Documentos por pagar bancario y financiero extranjero', 2, NULL, true),
    ('202.03', 'Documentos y cuentas por pagar a corto plazo nacional', 2, NULL, true),
    ('202.04', 'Documentos y cuentas por pagar a corto plazo extranjero', 2, NULL, true),
    ('202.05', 'Documentos y cuentas por pagar a corto plazo nacional parte relacionada', 2, NULL, true),
    ('202.06', 'Documentos y cuentas por pagar a corto plazo extranjero parte relacionada', 2, NULL, true),
    ('202.07', 'Intereses por pagar a corto plazo nacional', 2, NULL, true),
    ('202.08', 'Intereses por pagar a corto plazo extranjero', 2, NULL, true),
    ('202.09', 'Intereses por pagar a corto plazo nacional parte relacionada', 2, NULL, true),
    ('202.10', 'Intereses por pagar a corto plazo extranjero parte relacionada', 2, NULL, true),
    ('202.11', 'Dividendo por pagar nacional', 2, NULL, true),
    ('202.12', 'Dividendo por pagar extranjero', 2, NULL, true),
    ('203', 'Cobros anticipados a corto plazo', 1, NULL, true),
    ('203.01', 'Rentas cobradas por anticipado a corto plazo nacional', 2, NULL, true),
    ('203.02', 'Rentas cobradas por anticipado a corto plazo extranjero', 2, NULL, true),
    ('203.03', 'Rentas cobradas por anticipado a corto plazo nacional parte relacionada', 2, NULL, true),
    ('203.04', 'Rentas cobradas por anticipado a corto plazo extranjero parte relacionada', 2, NULL, true),
    ('203.05', 'Intereses cobrados por anticipado a corto plazo nacional', 2, NULL, true),
    ('203.06', 'Intereses cobrados por anticipado a corto plazo extranjero', 2, NULL, true),
    ('203.07', 'Intereses cobrados por anticipado a corto plazo nacional parte relacionada', 2, NULL, true),
    ('203.08', 'Intereses cobrados por anticipado a corto plazo extranjero parte relacionada', 2, NULL, true),
    ('203.09', 'Factoraje financiero cobrados por anticipado a corto plazo nacional', 2, NULL, true),
    ('203.10', 'Factoraje financiero cobrados por anticipado a corto plazo extranjero', 2, NULL, true),
    ('203.11', 'Factoraje financiero cobrados por anticipado a corto plazo nacional parte relacionada', 2, NULL, true),
    ('203.12', 'Factoraje financiero cobrados por anticipado a corto plazo extranjero parte relacionada', 2, NULL, true),
    ('203.13', 'Arrendamiento financiero cobrados por anticipado a corto plazo nacional', 2, NULL, true),
    ('203.14', 'Arrendamiento financiero cobrados por anticipado a corto plazo extranjero', 2, NULL, true),
    ('203.15', 'Arrendamiento financiero cobrados por anticipado a corto plazo nacional parte relacionada', 2, NULL, true),
    ('203.16', 'Arrendamiento financiero cobrados por anticipado a corto plazo extranjero parte relacionada', 2, NULL, true),
    ('203.17', 'Derechos fiduciarios', 2, NULL, true),
    ('203.18', 'Otros cobros anticipados', 2, NULL, true),
    ('204', 'Instrumentos financieros a corto plazo', 1, NULL, true),
    ('204.01', 'Instrumentos financieros a corto plazo', 2, NULL, true),
    ('205', 'Acreedores diversos a corto plazo', 1, NULL, true),
    ('205.01', 'Socios, accionistas o representante legal', 2, NULL, true),
    ('205.02', 'Acreedores diversos a corto plazo nacional', 2, NULL, true),
    ('205.03', 'Acreedores diversos a corto plazo extranjero', 2, NULL, true),
    ('205.04', 'Acreedores diversos a corto plazo nacional parte relacionada', 2, NULL, true),
    ('205.05', 'Acreedores diversos a corto plazo extranjero parte relacionada', 2, NULL, true),
    ('205.06', 'Otros acreedores diversos a corto plazo', 2, NULL, true),
    ('206', 'Anticipo de cliente', 1, NULL, true),
    ('206.01', 'Anticipo de cliente nacional', 2, NULL, true),
    ('206.02', 'Anticipo de cliente extranjero', 2, NULL, true),
    ('206.03', 'Anticipo de cliente nacional parte relacionada', 2, NULL, true),
    ('206.04', 'Anticipo de cliente extranjero parte relacionada', 2, NULL, true),
    ('206.05', 'Otros anticipos de clientes', 2, NULL, true),
    ('207', 'Impuestos trasladados', 1, NULL, true),
    ('207.01', 'IVA trasladado', 2, NULL, true),
    ('207.02', 'IEPS trasladado', 2, NULL, true),
    ('208', 'Impuestos trasladados cobrados', 1, NULL, true),
    ('208.01', 'IVA trasladado cobrado', 2, NULL, true),
    ('208.02', 'IEPS trasladado cobrado', 2, NULL, true),
    ('209', 'Impuestos trasladados no cobrados', 1, NULL, true),
    ('209.01', 'IVA trasladado no cobrado', 2, NULL, true),
    ('209.02', 'IEPS trasladado no cobrado', 2, NULL, true),
    ('210', 'Provisión de sueldos y salarios por pagar', 1, NULL, true),
    ('210.01', 'Provisión de sueldos y salarios por pagar', 2, NULL, true),
    ('210.02', 'Provisión de vacaciones por pagar', 2, NULL, true),
    ('210.03', 'Provisión de aguinaldo por pagar', 2, NULL, true),
    ('210.04', 'Provisión de fondo de ahorro por pagar', 2, NULL, true),
    ('210.05', 'Provisión de asimilados a salarios por pagar', 2, NULL, true),
    ('210.06', 'Provisión de anticipos o remanentes por distribuir', 2, NULL, true),
    ('210.07', 'Provisión de otros sueldos y salarios por pagar', 2, NULL, true),
    ('211', 'Provisión de contribuciones de seguridad social por pagar', 1, NULL, true),
    ('211.01', 'Provisión de IMSS patronal por pagar', 2, NULL, true),
    ('211.02', 'Provisión de SAR por pagar', 2, NULL, true),
    ('211.03', 'Provisión de infonavit por pagar', 2, NULL, true),
    ('212', 'Provisión de impuesto estatal sobre nómina por pagar', 1, NULL, true),
    ('212.01', 'Provisión de impuesto estatal sobre nómina por pagar', 2, NULL, true),
    ('213', 'Impuestos y derechos por pagar', 1, NULL, true),
    ('213.01', 'IVA por pagar', 2, NULL, true),
    ('213.02', 'IEPS por pagar', 2, NULL, true),
    ('213.03', 'ISR por pagar', 2, NULL, true),
    ('213.04', 'Impuesto estatal sobre nómina por pagar', 2, NULL, true),
    ('213.05', 'Impuesto estatal y municipal por pagar', 2, NULL, true),
    ('213.06', 'Derechos por pagar', 2, NULL, true),
    ('213.07', 'Otros impuestos por pagar', 2, NULL, true),
    ('214', 'Dividendos por pagar', 1, NULL, true),
    ('214.01', 'Dividendos por pagar', 2, NULL, true),
    ('215', 'PTU por pagar', 1, NULL, true),
    ('215.01', 'PTU por pagar', 2, NULL, true),
    ('215.02', 'PTU por pagar de ejercicios anteriores', 2, NULL, true),
    ('215.03', 'Provisión de PTU por pagar', 2, NULL, true),
    ('216', 'Impuestos retenidos', 1, NULL, true),
    ('216.01', 'Impuestos retenidos de ISR por sueldos y salarios', 2, NULL, true),
    ('216.02', 'Impuestos retenidos de ISR por asimilados a salarios', 2, NULL, true),
    ('216.03', 'Impuestos retenidos de ISR por arrendamiento', 2, NULL, true),
    ('216.04', 'Impuestos retenidos de ISR por servicios profesionales', 2, NULL, true),
    ('216.05', 'Impuestos retenidos de ISR por dividendos', 2, NULL, true),
    ('216.06', 'Impuestos retenidos de ISR por intereses', 2, NULL, true),
    ('216.07', 'Impuestos retenidos de ISR por pagos al extranjero', 2, NULL, true),
    ('216.08', 'Impuestos retenidos de ISR por venta de acciones', 2, NULL, true),
    ('216.09', 'Impuestos retenidos de ISR por venta de partes sociales', 2, NULL, true),
    ('216.10', 'Impuestos retenidos de IVA', 2, NULL, true),
    ('216.11', 'Retenciones de IMSS a los trabajadores', 2, NULL, true),
    ('216.12', 'Otras impuestos retenidos', 2, NULL, true),
    ('217', 'Pagos realizados por cuenta de terceros', 1, NULL, true),
    ('217.01', 'Pagos realizados por cuenta de terceros', 2, NULL, true),
    ('218', 'Otros pasivos a corto plazo', 1, NULL, true),
    ('218.01', 'Otros pasivos a corto plazo', 2, NULL, true),
    ('200.02', 'Pasivo a largo plazo', NULL, NULL, true),
    ('251', 'Acreedores diversos a largo plazo', 1, NULL, true),
    ('251.01', 'Socios, accionistas o representante legal', 2, NULL, true),
    ('251.02', 'Acreedores diversos a largo plazo nacional', 2, NULL, true),
    ('251.03', 'Acreedores diversos a largo plazo extranjero', 2, NULL, true),
    ('251.04', 'Acreedores diversos a largo plazo nacional parte relacionada', 2, NULL, true),
    ('251.05', 'Acreedores diversos a largo plazo extranjero parte relacionada', 2, NULL, true),
    ('251.06', 'Otros acreedores diversos a largo plazo', 2, NULL, true),
    ('252', 'Cuentas por pagar a largo plazo', 1, NULL, true),
    ('252.01', 'Documentos bancarios y financieros por pagar a largo plazo nacional', 2, NULL, true),
    ('252.02', 'Documentos bancarios y financieros por pagar a largo plazo extranjero', 2, NULL, true),
    ('252.03', 'Documentos y cuentas por pagar a largo plazo nacional', 2, NULL, true),
    ('252.04', 'Documentos y cuentas por pagar a largo plazo extranjero', 2, NULL, true),
    ('252.05', 'Documentos y cuentas por pagar a largo plazo nacional parte relacionada', 2, NULL, true),
    ('252.06', 'Documentos y cuentas por pagar a largo plazo extranjero parte relacionada', 2, NULL, true),
    ('252.07', 'Hipotecas por pagar a largo plazo nacional', 2, NULL, true),
    ('252.08', 'Hipotecas por pagar a largo plazo extranjero', 2, NULL, true),
    ('252.09', 'Hipotecas por pagar a largo plazo nacional parte relacionada', 2, NULL, true),
    ('252.10', 'Hipotecas por pagar a largo plazo extranjero parte relacionada', 2, NULL, true),
    ('252.11', 'Intereses por pagar a largo plazo nacional', 2, NULL, true),
    ('252.12', 'Intereses por pagar a largo plazo extranjero', 2, NULL, true),
    ('252.13', 'Intereses por pagar a largo plazo nacional parte relacionada', 2, NULL, true),
    ('252.14', 'Intereses por pagar a largo plazo extranjero parte relacionada', 2, NULL, true),
    ('252.15', 'Dividendos por pagar nacionales', 2, NULL, true),
    ('252.16', 'Dividendos por pagar extranjeros', 2, NULL, true),
    ('252.17', 'Otras cuentas y documentos por pagar a largo plazo', 2, NULL, true),
    ('253', 'Cobros anticipados a largo plazo', 1, NULL, true),
    ('253.01', 'Rentas cobradas por anticipado a largo plazo nacional', 2, NULL, true),
    ('253.02', 'Rentas cobradas por anticipado a largo plazo extranjero', 2, NULL, true),
    ('253.03', 'Rentas cobradas por anticipado a largo plazo nacional parte relacionada', 2, NULL, true),
    ('253.04', 'Rentas cobradas por anticipado a largo plazo extranjero parte relacionada', 2, NULL, true),
    ('253.05', 'Intereses cobrados por anticipado a largo plazo nacional', 2, NULL, true),
    ('253.06', 'Intereses cobrados por anticipado a largo plazo extranjero', 2, NULL, true),
    ('253.07', 'Intereses cobrados por anticipado a largo plazo nacional parte relacionada', 2, NULL, true),
    ('253.08', 'Intereses cobrados por anticipado a largo plazo extranjero parte relacionada', 2, NULL, true),
    ('253.09', 'Factoraje financiero cobrados por anticipado a largo plazo nacional', 2, NULL, true),
    ('253.10', 'Factoraje financiero cobrados por anticipado a largo plazo extranjero', 2, NULL, true),
    ('253.11', 'Factoraje financiero cobrados por anticipado a largo plazo nacional parte relacionada', 2, NULL, true),
    ('253.12', 'Factoraje financiero cobrados por anticipado a largo plazo extranjero parte relacionada', 2, NULL, true),
    ('253.13', 'Arrendamiento financiero cobrados por anticipado a largo plazo nacional', 2, NULL, true),
    ('253.14', 'Arrendamiento financiero cobrados por anticipado a largo plazo extranjero', 2, NULL, true),
    ('253.15', 'Arrendamiento financiero cobrados por anticipado a largo plazo nacional parte relacionada', 2, NULL, true),
    ('253.16', 'Arrendamiento financiero cobrados por anticipado a largo plazo extranjero parte relacionada', 2, NULL, true),
    ('253.17', 'Derechos fiduciarios', 2, NULL, true),
    ('253.18', 'Otros cobros anticipados', 2, NULL, true),
    ('254', 'Instrumentos financieros a largo plazo', 1, NULL, true),
    ('254.01', 'Instrumentos financieros a largo plazo', 2, NULL, true),
    ('255', 'Pasivos por beneficios a los empleados a largo plazo', 1, NULL, true),
    ('255.01', 'Pasivos por beneficios a los empleados a largo plazo', 2, NULL, true),
    ('256', 'Otros pasivos a largo plazo', 1, NULL, true),
    ('256.01', 'Otros pasivos a largo plazo', 2, NULL, true),
    ('257', 'Participación de los trabajadores en las utilidades diferida', 1, NULL, true),
    ('257.01', 'Participación de los trabajadores en las utilidades diferida', 2, NULL, true),
    ('258', 'Obligaciones contraídas de fideicomisos', 1, NULL, true),
    ('258.01', 'Obligaciones contraídas de fideicomisos', 2, NULL, true),
    ('259', 'Impuestos diferidos', 1, NULL, true),
    ('259.01', 'ISR diferido', 2, NULL, true),
    ('259.02', 'ISR por dividendo diferido', 2, NULL, true),
    ('259.03', 'Otros impuestos diferidos', 2, NULL, true),
    ('260', 'Pasivos diferidos', 1, NULL, true),
    ('260.01', 'Pasivos diferidos', 2, NULL, true),
    ('300', 'Capital contable', NULL, NULL, true),
    ('301', 'Capital social', 1, NULL, true),
    ('301.01', 'Capital fijo', 2, NULL, true),
    ('301.02', 'Capital variable', 2, NULL, true),
    ('301.03', 'Aportaciones para futuros aumentos de capital', 2, NULL, true),
    ('301.04', 'Prima en suscripción de acciones', 2, NULL, true),
    ('301.05', 'Prima en suscripción de partes sociales', 2, NULL, true),
    ('302', 'Patrimonio', 1, NULL, true),
    ('302.01', 'Patrimonio', 2, NULL, true),
    ('302.02', 'Aportación patrimonial', 2, NULL, true),
    ('302.03', 'Déficit o remanente del ejercicio', 2, NULL, true),
    ('303', 'Reserva legal', 1, NULL, true),
    ('303.01', 'Reserva legal', 2, NULL, true),
    ('304', 'Resultado de ejercicios anteriores', 1, NULL, true),
    ('304.01', 'Utilidad de ejercicios anteriores', 2, NULL, true),
    ('304.02', 'Pérdida de ejercicios anteriores', 2, NULL, true),
    ('304.03', 'Resultado integral de ejercicios anteriores', 2, NULL, true),
    ('304.04', 'Déficit o remanente de ejercicio anteriores', 2, NULL, true),
    ('305', 'Resultado del ejercicio', 1, NULL, true),
    ('305.01', 'Utilidad del ejercicio', 2, NULL, true),
    ('305.02', 'Pérdida del ejercicio', 2, NULL, true),
    ('305.03', 'Resultado integral', 2, NULL, true),
    ('306', 'Otras cuentas de capital', 1, NULL, true),
    ('306.01', 'Otras cuentas de capital', 2, NULL, true),
    ('400', 'Ingresos', NULL, NULL, true),
    ('401', 'Ingresos', 1, NULL, true),
    ('401.01', 'Ventas y/o servicios gravados a la tasa general', 2, NULL, true),
    ('401.02', 'Ventas y/o servicios gravados a la tasa general de contado', 2, NULL, true),
    ('401.03', 'Ventas y/o servicios gravados a la tasa general a crédito', 2, NULL, true),
    ('401.04', 'Ventas y/o servicios gravados al 0%', 2, NULL, true),
    ('401.05', 'Ventas y/o servicios gravados al 0% de contado', 2, NULL, true),
    ('401.06', 'Ventas y/o servicios gravados al 0% a crédito', 2, NULL, true),
    ('401.07', 'Ventas y/o servicios exentos', 2, NULL, true),
    ('401.08', 'Ventas y/o servicios exentos de contado', 2, NULL, true),
    ('401.09', 'Ventas y/o servicios exentos a crédito', 2, NULL, true),
    ('401.10', 'Ventas y/o servicios gravados a la tasa general nacionales partes relacionadas', 2, NULL, true),
    ('401.11', 'Ventas y/o servicios gravados a la tasa general extranjeros partes relacionadas', 2, NULL, true),
    ('401.12', 'Ventas y/o servicios gravados al 0% nacionales partes relacionadas', 2, NULL, true),
    ('401.13', 'Ventas y/o servicios gravados al 0% extranjeros partes relacionadas', 2, NULL, true),
    ('401.14', 'Ventas y/o servicios exentos nacionales partes relacionadas', 2, NULL, true),
    ('401.15', 'Ventas y/o servicios exentos extranjeros partes relacionadas', 2, NULL, true),
    ('401.16', 'Ingresos por servicios administrativos', 2, NULL, true),
    ('401.17', 'Ingresos por servicios administrativos nacionales partes relacionadas', 2, NULL, true),
    ('401.18', 'Ingresos por servicios administrativos extranjeros partes relacionadas', 2, NULL, true),
    ('401.19', 'Ingresos por servicios profesionales', 2, NULL, true),
    ('401.20', 'Ingresos por servicios profesionales nacionales partes relacionadas', 2, NULL, true),
    ('401.21', 'Ingresos por servicios profesionales extranjeros partes relacionadas', 2, NULL, true),
    ('401.22', 'Ingresos por arrendamiento', 2, NULL, true),
    ('401.23', 'Ingresos por arrendamiento nacionales partes relacionadas', 2, NULL, true),
    ('401.24', 'Ingresos por arrendamiento extranjeros partes relacionadas', 2, NULL, true),
    ('401.25', 'Ingresos por exportación', 2, NULL, true),
    ('401.26', 'Ingresos por comisiones', 2, NULL, true),
    ('401.27', 'Ingresos por maquila', 2, NULL, true),
    ('401.28', 'Ingresos por coordinados', 2, NULL, true),
    ('401.29', 'Ingresos por regalías', 2, NULL, true),
    ('401.30', 'Ingresos por asistencia técnica', 2, NULL, true),
    ('401.31', 'Ingresos por donativos', 2, NULL, true),
    ('401.32', 'Ingresos por intereses (actividad propia)', 2, NULL, true),
    ('401.33', 'Ingresos de copropiedad', 2, NULL, true),
    ('401.34', 'Ingresos por fideicomisos', 2, NULL, true),
    ('401.35', 'Ingresos por factoraje financiero', 2, NULL, true),
    ('401.36', 'Ingresos por arrendamiento financiero', 2, NULL, true),
    ('401.37', 'Ingresos de extranjeros con establecimiento en el país', 2, NULL, true),
    ('401.38', 'Otros ingresos propios', 2, NULL, true),
    ('402', 'Devoluciones, descuentos o bonificaciones sobre ingresos', 1, NULL, true),
    ('402.01', 'Devoluciones, descuentos o bonificaciones sobre ventas y/o servicios a la tasa general', 2, NULL, true),
    ('402.02', 'Devoluciones, descuentos o bonificaciones sobre ventas y/o servicios al 0%', 2, NULL, true),
    ('402.03', 'Devoluciones, descuentos o bonificaciones sobre ventas y/o servicios exentos', 2, NULL, true),
    ('402.04', 'Devoluciones, descuentos o bonificaciones de otros ingresos', 2, NULL, true),
    ('403', 'Otros ingresos', 1, NULL, true),
    ('403.01', 'Otros Ingresos', 2, NULL, true),
    ('403.02', 'Otros ingresos nacionales parte relacionada', 2, NULL, true),
    ('403.03', 'Otros ingresos extranjeros parte relacionada', 2, NULL, true),
    ('403.04', 'Ingresos por operaciones discontinuas', 2, NULL, true),
    ('403.05', 'Ingresos por condonación de adeudo', 2, NULL, true),
    ('500', 'Costos', NULL, NULL, true),
    ('501', 'Costo de venta y/o servicio', 1, NULL, true),
    ('501.01', 'Costo de venta', 2, NULL, true),
    ('501.02', 'Costo de servicios (Mano de obra)', 2, NULL, true),
    ('501.03', 'Materia prima directa utilizada para la producción', 2, NULL, true),
    ('501.04', 'Materia prima consumida en el proceso productivo', 2, NULL, true),
    ('501.05', 'Mano de obra directa consumida', 2, NULL, true),
    ('501.06', 'Mano de obra directa', 2, NULL, true),
    ('501.07', 'Cargos indirectos de producción', 2, NULL, true),
    ('501.08', 'Otros conceptos de costo', 2, NULL, true),
    ('502', 'Compras', 1, NULL, true),
    ('502.01', 'Compras nacionales', 2, NULL, true),
    ('502.02', 'Compras nacionales parte relacionada', 2, NULL, true),
    ('502.03', 'Compras de Importación', 2, NULL, true),
    ('502.04', 'Compras de Importación partes relacionadas', 2, NULL, true),
    ('503', 'Devoluciones, descuentos o bonificaciones sobre compras', 1, NULL, true),
    ('503.01', 'Devoluciones, descuentos o bonificaciones sobre compras', 2, NULL, true),
    ('504', 'Otras cuentas de costos', 1, NULL, true),
    ('504.01', 'Gastos indirectos de fabricación', 2, NULL, true),
    ('504.02', 'Gastos indirectos de fabricación de partes relacionadas nacionales', 2, NULL, true),
    ('504.03', 'Gastos indirectos de fabricación de partes relacionadas extranjeras', 2, NULL, true),
    ('504.04', 'Otras cuentas de costos incurridos', 2, NULL, true),
    ('504.05', 'Otras cuentas de costos incurridos con partes relacionadas nacionales', 2, NULL, true),
    ('504.06', 'Otras cuentas de costos incurridos con partes relacionadas extranjeras', 2, NULL, true),
    ('504.07', 'Depreciación de edificios', 2, NULL, true),
    ('504.08', 'Depreciación de maquinaria y equipo', 2, NULL, true),
    ('504.09', 'Depreciación de automóviles, autobuses, camiones de carga, tractocamiones, montacargas y remolques', 2, NULL, true),
    ('504.10', 'Depreciación de mobiliario y equipo de oficina', 2, NULL, true),
    ('504.11', 'Depreciación de equipo de cómputo', 2, NULL, true),
    ('504.12', 'Depreciación de equipo de comunicación', 2, NULL, true),
    ('504.13', 'Depreciación de activos biológicos, vegetales y semovientes', 2, NULL, true),
    ('504.14', 'Depreciación de otros activos fijos', 2, NULL, true),
    ('504.15', 'Depreciación de ferrocarriles', 2, NULL, true),
    ('504.16', 'Depreciación de embarcaciones', 2, NULL, true),
    ('504.17', 'Depreciación de aviones', 2, NULL, true),
    ('504.18', 'Depreciación de troqueles, moldes, matrices y herramental', 2, NULL, true),
    ('504.19', 'Depreciación de equipo de comunicaciones telefónicas', 2, NULL, true),
    ('504.20', 'Depreciación de equipo de comunicación satelital', 2, NULL, true),
    ('504.21', 'Depreciación de equipo de adaptaciones para personas con capacidades diferentes', 2, NULL, true),
    ('504.22', 'Depreciación de maquinaria y equipo de generación de energía de fuentes renovables o de sistemas de cogeneración de electricidad eficiente', 2, NULL, true),
    ('504.23', 'Depreciación de adaptaciones y mejoras', 2, NULL, true),
    ('504.24', 'Depreciación de otra maquinaria y equipo', 2, NULL, true),
    ('504.25', 'Otras cuentas de costos', 2, NULL, true),
    ('505', 'Costo de activo fijo', 1, NULL, true),
    ('505.01', 'Costo por venta de activo fijo', 2, NULL, true),
    ('505.02', 'Costo por baja de activo fijo', 2, NULL, true),
    ('600', 'Gastos', NULL, NULL, true),
    ('601', 'Gastos generales', 1, NULL, true),
    ('601.01', 'Sueldos y salarios', 2, NULL, true),
    ('601.02', 'Compensaciones', 2, NULL, true),
    ('601.03', 'Tiempos extras', 2, NULL, true),
    ('601.04', 'Premios de asistencia', 2, NULL, true),
    ('601.05', 'Premios de puntualidad', 2, NULL, true),
    ('601.06', 'Vacaciones', 2, NULL, true),
    ('601.07', 'Prima vacacional', 2, NULL, true),
    ('601.08', 'Prima dominical', 2, NULL, true),
    ('601.09', 'Días festivos', 2, NULL, true),
    ('601.10', 'Gratificaciones', 2, NULL, true),
    ('601.11', 'Primas de antigüedad', 2, NULL, true),
    ('601.12', 'Aguinaldo', 2, NULL, true),
    ('601.13', 'Indemnizaciones', 2, NULL, true),
    ('601.14', 'Destajo', 2, NULL, true),
    ('601.15', 'Despensa', 2, NULL, true),
    ('601.16', 'Transporte', 2, NULL, true),
    ('601.17', 'Servicio médico', 2, NULL, true),
    ('601.18', 'Ayuda en gastos funerarios', 2, NULL, true),
    ('601.19', 'Fondo de ahorro', 2, NULL, true),
    ('601.20', 'Cuotas sindicales', 2, NULL, true),
    ('601.21', 'PTU', 2, NULL, true),
    ('601.22', 'Estímulo al personal', 2, NULL, true),
    ('601.23', 'Previsión social', 2, NULL, true),
    ('601.24', 'Aportaciones para el plan de jubilación', 2, NULL, true),
    ('601.25', 'Otras prestaciones al personal', 2, NULL, true),
    ('601.26', 'Cuotas al IMSS', 2, NULL, true),
    ('601.27', 'Aportaciones al infonavit', 2, NULL, true),
    ('601.28', 'Aportaciones al SAR', 2, NULL, true),
    ('601.29', 'Impuesto estatal sobre nóminas', 2, NULL, true),
    ('601.30', 'Otras aportaciones', 2, NULL, true),
    ('601.31', 'Asimilados a salarios', 2, NULL, true),
    ('601.32', 'Servicios administrativos', 2, NULL, true),
    ('601.33', 'Servicios administrativos partes relacionadas', 2, NULL, true),
    ('601.34', 'Honorarios a personas físicas residentes nacionales', 2, NULL, true),
    ('601.35', 'Honorarios a personas físicas residentes nacionales partes relacionadas', 2, NULL, true),
    ('601.36', 'Honorarios a personas físicas residentes del extranjero', 2, NULL, true),
    ('601.37', 'Honorarios a personas físicas residentes del extranjero partes relacionadas', 2, NULL, true),
    ('601.38', 'Honorarios a personas morales residentes nacionales', 2, NULL, true),
    ('601.39', 'Honorarios a personas morales residentes nacionales partes relacionadas', 2, NULL, true),
    ('601.40', 'Honorarios a personas morales residentes del extranjero', 2, NULL, true),
    ('601.41', 'Honorarios a personas morales residentes del extranjero partes relacionadas', 2, NULL, true),
    ('601.42', 'Honorarios aduanales personas físicas', 2, NULL, true),
    ('601.43', 'Honorarios aduanales personas morales', 2, NULL, true),
    ('601.44', 'Honorarios al consejo de administración', 2, NULL, true),
    ('601.45', 'Arrendamiento a personas físicas residentes nacionales', 2, NULL, true),
    ('601.46', 'Arrendamiento a personas morales residentes nacionales', 2, NULL, true),
    ('601.47', 'Arrendamiento a residentes del extranjero', 2, NULL, true),
    ('601.48', 'Combustibles y lubricantes', 2, NULL, true),
    ('601.49', 'Viáticos y gastos de viaje', 2, NULL, true),
    ('601.50', 'Teléfono, internet', 2, NULL, true),
    ('601.51', 'Agua', 2, NULL, true),
    ('601.52', 'Energía eléctrica', 2, NULL, true),
    ('601.53', 'Vigilancia y seguridad', 2, NULL, true),
    ('601.54', 'Limpieza', 2, NULL, true),
    ('601.55', 'Papelería y artículos de oficina', 2, NULL, true),
    ('601.56', 'Mantenimiento y conservación', 2, NULL, true),
    ('601.57', 'Seguros y fianzas', 2, NULL, true),
    ('601.58', 'Otros impuestos y derechos', 2, NULL, true),
    ('601.59', 'Recargos fiscales', 2, NULL, true),
    ('601.60', 'Cuotas y suscripciones', 2, NULL, true),
    ('601.61', 'Propaganda y publicidad', 2, NULL, true),
    ('601.62', 'Capacitación al personal', 2, NULL, true),
    ('601.63', 'Donativos y ayudas', 2, NULL, true),
    ('601.64', 'Asistencia técnica', 2, NULL, true),
    ('601.65', 'Regalías sujetas a otros porcentajes', 2, NULL, true),
    ('601.66', 'Regalías sujetas al 5%', 2, NULL, true),
    ('601.67', 'Regalías sujetas al 10%', 2, NULL, true),
    ('601.68', 'Regalías sujetas al 15%', 2, NULL, true),
    ('601.69', 'Regalías sujetas al 25%', 2, NULL, true),
    ('601.70', 'Regalías sujetas al 30%', 2, NULL, true),
    ('601.71', 'Regalías sin retención', 2, NULL, true),
    ('601.72', 'Fletes y acarreos', 2, NULL, true),
    ('601.73', 'Gastos de importación', 2, NULL, true),
    ('601.74', 'Comisiones sobre ventas', 2, NULL, true),
    ('601.75', 'Comisiones por tarjetas de crédito', 2, NULL, true),
    ('601.76', 'Patentes y marcas', 2, NULL, true),
    ('601.77', 'Uniformes', 2, NULL, true),
    ('601.78', 'Prediales', 2, NULL, true),
    ('601.79', 'Gastos generales de urbanización', 2, NULL, true),
    ('601.80', 'Gastos generales de construcción', 2, NULL, true),
    ('601.81', 'Fletes del extranjero', 2, NULL, true),
    ('601.82', 'Recolección de bienes del sector agropecuario y/o ganadero', 2, NULL, true),
    ('601.83', 'Gastos no deducibles (sin requisitos fiscales)', 2, NULL, true),
    ('601.84', 'Otros gastos generales', 2, NULL, true),
    ('602', 'Gastos de venta', 1, NULL, true),
    ('602.01', 'Sueldos y salarios', 2, NULL, true),
    ('602.02', 'Compensaciones', 2, NULL, true),
    ('602.03', 'Tiempos extras', 2, NULL, true),
    ('602.04', 'Premios de asistencia', 2, NULL, true),
    ('602.05', 'Premios de puntualidad', 2, NULL, true),
    ('602.06', 'Vacaciones', 2, NULL, true),
    ('602.07', 'Prima vacacional', 2, NULL, true),
    ('602.08', 'Prima dominical', 2, NULL, true),
    ('602.09', 'Días festivos', 2, NULL, true),
    ('602.10', 'Gratificaciones', 2, NULL, true),
    ('602.11', 'Primas de antigüedad', 2, NULL, true),
    ('602.12', 'Aguinaldo', 2, NULL, true),
    ('602.13', 'Indemnizaciones', 2, NULL, true),
    ('602.14', 'Destajo', 2, NULL, true),
    ('602.15', 'Despensa', 2, NULL, true),
    ('602.16', 'Transporte', 2, NULL, true),
    ('602.17', 'Servicio médico', 2, NULL, true),
    ('602.18', 'Ayuda en gastos funerarios', 2, NULL, true),
    ('602.19', 'Fondo de ahorro', 2, NULL, true),
    ('602.20', 'Cuotas sindicales', 2, NULL, true),
    ('602.21', 'PTU', 2, NULL, true),
    ('602.22', 'Estímulo al personal', 2, NULL, true),
    ('602.23', 'Previsión social', 2, NULL, true),
    ('602.24', 'Aportaciones para el plan de jubilación', 2, NULL, true),
    ('602.25', 'Otras prestaciones al personal', 2, NULL, true),
    ('602.26', 'Cuotas al IMSS', 2, NULL, true),
    ('602.27', 'Aportaciones al infonavit', 2, NULL, true),
    ('602.28', 'Aportaciones al SAR', 2, NULL, true),
    ('602.29', 'Impuesto estatal sobre nóminas', 2, NULL, true),
    ('602.30', 'Otras aportaciones', 2, NULL, true),
    ('602.31', 'Asimilados a salarios', 2, NULL, true),
    ('602.32', 'Servicios administrativos', 2, NULL, true),
    ('602.33', 'Servicios administrativos partes relacionadas', 2, NULL, true),
    ('602.34', 'Honorarios a personas físicas residentes nacionales', 2, NULL, true),
    ('602.35', 'Honorarios a personas físicas residentes nacionales partes relacionadas', 2, NULL, true),
    ('602.36', 'Honorarios a personas físicas residentes del extranjero', 2, NULL, true),
    ('602.37', 'Honorarios a personas físicas residentes del extranjero partes relacionadas', 2, NULL, true),
    ('602.38', 'Honorarios a personas morales residentes nacionales', 2, NULL, true),
    ('602.39', 'Honorarios a personas morales residentes nacionales partes relacionadas', 2, NULL, true),
    ('602.40', 'Honorarios a personas morales residentes del extranjero', 2, NULL, true),
    ('602.41', 'Honorarios a personas morales residentes del extranjero partes relacionadas', 2, NULL, true),
    ('602.42', 'Honorarios aduanales personas físicas', 2, NULL, true),
    ('602.43', 'Honorarios aduanales personas morales', 2, NULL, true),
    ('602.44', 'Honorarios al consejo de administración', 2, NULL, true),
    ('602.45', 'Arrendamiento a personas físicas residentes nacionales', 2, NULL, true),
    ('602.46', 'Arrendamiento a personas morales residentes nacionales', 2, NULL, true),
    ('602.47', 'Arrendamiento a residentes del extranjero', 2, NULL, true),
    ('602.48', 'Combustibles y lubricantes', 2, NULL, true),
    ('602.49', 'Viáticos y gastos de viaje', 2, NULL, true),
    ('602.50', 'Teléfono, internet', 2, NULL, true),
    ('602.51', 'Agua', 2, NULL, true),
    ('602.52', 'Energía eléctrica', 2, NULL, true),
    ('602.53', 'Vigilancia y seguridad', 2, NULL, true),
    ('602.54', 'Limpieza', 2, NULL, true),
    ('602.55', 'Papelería y artículos de oficina', 2, NULL, true),
    ('602.56', 'Mantenimiento y conservación', 2, NULL, true),
    ('602.57', 'Seguros y fianzas', 2, NULL, true),
    ('602.58', 'Otros impuestos y derechos', 2, NULL, true),
    ('602.59', 'Recargos fiscales', 2, NULL, true),
    ('602.60', 'Cuotas y suscripciones', 2, NULL, true),
    ('602.61', 'Propaganda y publicidad', 2, NULL, true),
    ('602.62', 'Capacitación al personal', 2, NULL, true),
    ('602.63', 'Donativos y ayudas', 2, NULL, true),
    ('602.64', 'Asistencia técnica', 2, NULL, true),
    ('602.65', 'Regalías sujetas a otros porcentajes', 2, NULL, true),
    ('602.66', 'Regalías sujetas al 5%', 2, NULL, true),
    ('602.67', 'Regalías sujetas al 10%', 2, NULL, true),
    ('602.68', 'Regalías sujetas al 15%', 2, NULL, true),
    ('602.69', 'Regalías sujetas al 25%', 2, NULL, true),
    ('602.70', 'Regalías sujetas al 30%', 2, NULL, true),
    ('602.71', 'Regalías sin retención', 2, NULL, true),
    ('602.72', 'Fletes y acarreos', 2, NULL, true),
    ('602.73', 'Gastos de importación', 2, NULL, true),
    ('602.74', 'Comisiones sobre ventas', 2, NULL, true),
    ('602.75', 'Comisiones por tarjetas de crédito', 2, NULL, true),
    ('602.76', 'Patentes y marcas', 2, NULL, true),
    ('602.77', 'Uniformes', 2, NULL, true),
    ('602.78', 'Prediales', 2, NULL, true),
    ('602.79', 'Gastos de venta de urbanización', 2, NULL, true),
    ('602.80', 'Gastos de venta de construcción', 2, NULL, true),
    ('602.81', 'Fletes del extranjero', 2, NULL, true),
    ('602.82', 'Recolección de bienes del sector agropecuario y/o ganadero', 2, NULL, true),
    ('602.83', 'Gastos no deducibles (sin requisitos fiscales)', 2, NULL, true),
    ('602.84', 'Otros gastos de venta', 2, NULL, true),
    ('603', 'Gastos de administración', 1, NULL, true),
    ('603.01', 'Sueldos y salarios', 2, NULL, true),
    ('603.02', 'Compensaciones', 2, NULL, true),
    ('603.03', 'Tiempos extras', 2, NULL, true),
    ('603.04', 'Premios de asistencia', 2, NULL, true),
    ('603.05', 'Premios de puntualidad', 2, NULL, true),
    ('603.06', 'Vacaciones', 2, NULL, true),
    ('603.07', 'Prima vacacional', 2, NULL, true),
    ('603.08', 'Prima dominical', 2, NULL, true),
    ('603.09', 'Días festivos', 2, NULL, true),
    ('603.10', 'Gratificaciones', 2, NULL, true),
    ('603.11', 'Primas de antigüedad', 2, NULL, true),
    ('603.12', 'Aguinaldo', 2, NULL, true),
    ('603.13', 'Indemnizaciones', 2, NULL, true),
    ('603.14', 'Destajo', 2, NULL, true),
    ('603.15', 'Despensa', 2, NULL, true),
    ('603.16', 'Transporte', 2, NULL, true),
    ('603.17', 'Servicio médico', 2, NULL, true),
    ('603.18', 'Ayuda en gastos funerarios', 2, NULL, true),
    ('603.19', 'Fondo de ahorro', 2, NULL, true),
    ('603.20', 'Cuotas sindicales', 2, NULL, true),
    ('603.21', 'PTU', 2, NULL, true),
    ('603.22', 'Estímulo al personal', 2, NULL, true),
    ('603.23', 'Previsión social', 2, NULL, true),
    ('603.24', 'Aportaciones para el plan de jubilación', 2, NULL, true),
    ('603.25', 'Otras prestaciones al personal', 2, NULL, true),
    ('603.26', 'Cuotas al IMSS', 2, NULL, true),
    ('603.27', 'Aportaciones al infonavit', 2, NULL, true),
    ('603.28', 'Aportaciones al SAR', 2, NULL, true),
    ('603.29', 'Impuesto estatal sobre nóminas', 2, NULL, true),
    ('603.30', 'Otras aportaciones', 2, NULL, true),
    ('603.31', 'Asimilados a salarios', 2, NULL, true),
    ('603.32', 'Servicios administrativos', 2, NULL, true),
    ('603.33', 'Servicios administrativos partes relacionadas', 2, NULL, true),
    ('603.34', 'Honorarios a personas físicas residentes nacionales', 2, NULL, true),
    ('603.35', 'Honorarios a personas físicas residentes nacionales partes relacionadas', 2, NULL, true),
    ('603.36', 'Honorarios a personas físicas residentes del extranjero', 2, NULL, true),
    ('603.37', 'Honorarios a personas físicas residentes del extranjero partes relacionadas', 2, NULL, true),
    ('603.38', 'Honorarios a personas morales residentes nacionales', 2, NULL, true),
    ('603.39', 'Honorarios a personas morales residentes nacionales partes relacionadas', 2, NULL, true),
    ('603.40', 'Honorarios a personas morales residentes del extranjero', 2, NULL, true),
    ('603.41', 'Honorarios a personas morales residentes del extranjero partes relacionadas', 2, NULL, true),
    ('603.42', 'Honorarios aduanales personas físicas', 2, NULL, true),
    ('603.43', 'Honorarios aduanales personas morales', 2, NULL, true),
    ('603.44', 'Honorarios al consejo de administración', 2, NULL, true),
    ('603.45', 'Arrendamiento a personas físicas residentes nacionales', 2, NULL, true),
    ('603.46', 'Arrendamiento a personas morales residentes nacionales', 2, NULL, true),
    ('603.47', 'Arrendamiento a residentes del extranjero', 2, NULL, true),
    ('603.48', 'Combustibles y lubricantes', 2, NULL, true),
    ('603.49', 'Viáticos y gastos de viaje', 2, NULL, true),
    ('603.50', 'Teléfono, internet', 2, NULL, true),
    ('603.51', 'Agua', 2, NULL, true),
    ('603.52', 'Energía eléctrica', 2, NULL, true),
    ('603.53', 'Vigilancia y seguridad', 2, NULL, true),
    ('603.54', 'Limpieza', 2, NULL, true),
    ('603.55', 'Papelería y artículos de oficina', 2, NULL, true),
    ('603.56', 'Mantenimiento y conservación', 2, NULL, true),
    ('603.57', 'Seguros y fianzas', 2, NULL, true),
    ('603.58', 'Otros impuestos y derechos', 2, NULL, true),
    ('603.59', 'Recargos fiscales', 2, NULL, true),
    ('603.60', 'Cuotas y suscripciones', 2, NULL, true),
    ('603.61', 'Propaganda y publicidad', 2, NULL, true),
    ('603.62', 'Capacitación al personal', 2, NULL, true),
    ('603.63', 'Donativos y ayudas', 2, NULL, true),
    ('603.64', 'Asistencia técnica', 2, NULL, true),
    ('603.65', 'Regalías sujetas a otros porcentajes', 2, NULL, true),
    ('603.66', 'Regalías sujetas al 5%', 2, NULL, true),
    ('603.67', 'Regalías sujetas al 10%', 2, NULL, true),
    ('603.68', 'Regalías sujetas al 15%', 2, NULL, true),
    ('603.69', 'Regalías sujetas al 25%', 2, NULL, true),
    ('603.70', 'Regalías sujetas al 30%', 2, NULL, true),
    ('603.71', 'Regalías sin retención', 2, NULL, true),
    ('603.72', 'Fletes y acarreos', 2, NULL, true),
    ('603.73', 'Gastos de importación', 2, NULL, true),
    ('603.74', 'Patentes y marcas', 2, NULL, true),
    ('603.75', 'Uniformes', 2, NULL, true),
    ('603.76', 'Prediales', 2, NULL, true),
    ('603.77', 'Gastos de administración de urbanización', 2, NULL, true),
    ('603.78', 'Gastos de administración de construcción', 2, NULL, true),
    ('603.79', 'Fletes del extranjero', 2, NULL, true),
    ('603.80', 'Recolección de bienes del sector agropecuario y/o ganadero', 2, NULL, true),
    ('603.81', 'Gastos no deducibles (sin requisitos fiscales)', 2, NULL, true),
    ('603.82', 'Otros gastos de administración', 2, NULL, true),
    ('604', 'Gastos de fabricación', 1, NULL, true),
    ('604.01', 'Sueldos y salarios', 2, NULL, true),
    ('604.02', 'Compensaciones', 2, NULL, true),
    ('604.03', 'Tiempos extras', 2, NULL, true),
    ('604.04', 'Premios de asistencia', 2, NULL, true),
    ('604.05', 'Premios de puntualidad', 2, NULL, true),
    ('604.06', 'Vacaciones', 2, NULL, true),
    ('604.07', 'Prima vacacional', 2, NULL, true),
    ('604.08', 'Prima dominical', 2, NULL, true),
    ('604.09', 'Días festivos', 2, NULL, true),
    ('604.10', 'Gratificaciones', 2, NULL, true),
    ('604.11', 'Primas de antigüedad', 2, NULL, true),
    ('604.12', 'Aguinaldo', 2, NULL, true),
    ('604.13', 'Indemnizaciones', 2, NULL, true),
    ('604.14', 'Destajo', 2, NULL, true),
    ('604.15', 'Despensa', 2, NULL, true),
    ('604.16', 'Transporte', 2, NULL, true),
    ('604.17', 'Servicio médico', 2, NULL, true),
    ('604.18', 'Ayuda en gastos funerarios', 2, NULL, true),
    ('604.19', 'Fondo de ahorro', 2, NULL, true),
    ('604.20', 'Cuotas sindicales', 2, NULL, true),
    ('604.21', 'PTU', 2, NULL, true),
    ('604.22', 'Estímulo al personal', 2, NULL, true),
    ('604.23', 'Previsión social', 2, NULL, true),
    ('604.24', 'Aportaciones para el plan de jubilación', 2, NULL, true),
    ('604.25', 'Otras prestaciones al personal', 2, NULL, true),
    ('604.26', 'Cuotas al IMSS', 2, NULL, true),
    ('604.27', 'Aportaciones al infonavit', 2, NULL, true),
    ('604.28', 'Aportaciones al SAR', 2, NULL, true),
    ('604.29', 'Impuesto estatal sobre nóminas', 2, NULL, true),
    ('604.30', 'Otras aportaciones', 2, NULL, true),
    ('604.31', 'Asimilados a salarios', 2, NULL, true),
    ('604.32', 'Servicios administrativos', 2, NULL, true),
    ('604.33', 'Servicios administrativos partes relacionadas', 2, NULL, true),
    ('604.34', 'Honorarios a personas físicas residentes nacionales', 2, NULL, true),
    ('604.35', 'Honorarios a personas físicas residentes nacionales partes relacionadas', 2, NULL, true),
    ('604.36', 'Honorarios a personas físicas residentes del extranjero', 2, NULL, true),
    ('604.37', 'Honorarios a personas físicas residentes del extranjero partes relacionadas', 2, NULL, true),
    ('604.38', 'Honorarios a personas morales residentes nacionales', 2, NULL, true),
    ('604.39', 'Honorarios a personas morales residentes nacionales partes relacionadas', 2, NULL, true),
    ('604.40', 'Honorarios a personas morales residentes del extranjero', 2, NULL, true),
    ('604.41', 'Honorarios a personas morales residentes del extranjero partes relacionadas', 2, NULL, true),
    ('604.42', 'Honorarios aduanales personas físicas', 2, NULL, true),
    ('604.43', 'Honorarios aduanales personas morales', 2, NULL, true),
    ('604.44', 'Honorarios al consejo de administración', 2, NULL, true),
    ('604.45', 'Arrendamiento a personas físicas residentes nacionales', 2, NULL, true),
    ('604.46', 'Arrendamiento a personas morales residentes nacionales', 2, NULL, true),
    ('604.47', 'Arrendamiento a residentes del extranjero', 2, NULL, true),
    ('604.48', 'Combustibles y lubricantes', 2, NULL, true),
    ('604.49', 'Viáticos y gastos de viaje', 2, NULL, true),
    ('604.50', 'Teléfono, internet', 2, NULL, true),
    ('604.51', 'Agua', 2, NULL, true),
    ('604.52', 'Energía eléctrica', 2, NULL, true),
    ('604.53', 'Vigilancia y seguridad', 2, NULL, true),
    ('604.54', 'Limpieza', 2, NULL, true),
    ('604.55', 'Papelería y artículos de oficina', 2, NULL, true),
    ('604.56', 'Mantenimiento y conservación', 2, NULL, true),
    ('604.57', 'Seguros y fianzas', 2, NULL, true),
    ('604.58', 'Otros impuestos y derechos', 2, NULL, true),
    ('604.59', 'Recargos fiscales', 2, NULL, true),
    ('604.60', 'Cuotas y suscripciones', 2, NULL, true),
    ('604.61', 'Propaganda y publicidad', 2, NULL, true),
    ('604.62', 'Capacitación al personal', 2, NULL, true),
    ('604.63', 'Donativos y ayudas', 2, NULL, true),
    ('604.64', 'Asistencia técnica', 2, NULL, true),
    ('604.65', 'Regalías sujetas a otros porcentajes', 2, NULL, true),
    ('604.66', 'Regalías sujetas al 5%', 2, NULL, true),
    ('604.67', 'Regalías sujetas al 10%', 2, NULL, true),
    ('604.68', 'Regalías sujetas al 15%', 2, NULL, true),
    ('604.69', 'Regalías sujetas al 25%', 2, NULL, true),
    ('604.70', 'Regalías sujetas al 30%', 2, NULL, true),
    ('604.71', 'Regalías sin retención', 2, NULL, true),
    ('604.72', 'Fletes y acarreos', 2, NULL, true),
    ('604.73', 'Gastos de importación', 2, NULL, true),
    ('604.74', 'Patentes y marcas', 2, NULL, true),
    ('604.75', 'Uniformes', 2, NULL, true),
    ('604.76', 'Prediales', 2, NULL, true),
    ('604.77', 'Gastos de fabricación de urbanización', 2, NULL, true),
    ('604.78', 'Gastos de fabricación de construcción', 2, NULL, true),
    ('604.79', 'Fletes del extranjero', 2, NULL, true),
    ('604.80', 'Recolección de bienes del sector agropecuario y/o ganadero', 2, NULL, true),
    ('604.81', 'Gastos no deducibles (sin requisitos fiscales)', 2, NULL, true),
    ('604.82', 'Otros gastos de fabricación', 2, NULL, true),
    ('605', 'Mano de obra directa', 1, NULL, true),
    ('605.01', 'Mano de obra', 2, NULL, true),
    ('605.02', 'Sueldos y Salarios', 2, NULL, true),
    ('605.03', 'Compensaciones', 2, NULL, true),
    ('605.04', 'Tiempos extras', 2, NULL, true),
    ('605.05', 'Premios de asistencia', 2, NULL, true),
    ('605.06', 'Premios de puntualidad', 2, NULL, true),
    ('605.07', 'Vacaciones', 2, NULL, true),
    ('605.08', 'Prima vacacional', 2, NULL, true),
    ('605.09', 'Prima dominical', 2, NULL, true),
    ('605.10', 'Días festivos', 2, NULL, true),
    ('605.11', 'Gratificaciones', 2, NULL, true),
    ('605.12', 'Primas de antigüedad', 2, NULL, true),
    ('605.13', 'Aguinaldo', 2, NULL, true),
    ('605.14', 'Indemnizaciones', 2, NULL, true),
    ('605.15', 'Destajo', 2, NULL, true),
    ('605.16', 'Despensa', 2, NULL, true),
    ('605.17', 'Transporte', 2, NULL, true),
    ('605.18', 'Servicio médico', 2, NULL, true),
    ('605.19', 'Ayuda en gastos funerarios', 2, NULL, true),
    ('605.20', 'Fondo de ahorro', 2, NULL, true),
    ('605.21', 'Cuotas sindicales', 2, NULL, true),
    ('605.22', 'PTU', 2, NULL, true),
    ('605.23', 'Estímulo al personal', 2, NULL, true),
    ('605.24', 'Previsión social', 2, NULL, true),
    ('605.25', 'Aportaciones para el plan de jubilación', 2, NULL, true),
    ('605.26', 'Otras prestaciones al personal', 2, NULL, true),
    ('605.27', 'Asimilados a salarios', 2, NULL, true),
    ('605.28', 'Cuotas al IMSS', 2, NULL, true),
    ('605.29', 'Aportaciones al infonavit', 2, NULL, true),
    ('605.30', 'Aportaciones al SAR', 2, NULL, true),
    ('605.31', 'Otros costos de mano de obra directa', 2, NULL, true),
    ('606', 'Facilidades administrativas fiscales', 1, NULL, true),
    ('606.01', 'Facilidades administrativas fiscales', 2, NULL, true),
    ('607', 'Participación de los trabajadores en las utilidades', 1, NULL, true),
    ('607.01', 'Participación de los trabajadores en las utilidades', 2, NULL, true),
    ('608', 'Participación en resultados de subsidiarias', 1, NULL, true),
    ('608.01', 'Participación en resultados de subsidiarias', 2, NULL, true),
    ('609', 'Participación en resultados de asociadas', 1, NULL, true),
    ('609.01', 'Participación en resultados de asociadas', 2, NULL, true),
    ('610', 'Participación de los trabajadores en las utilidades diferida', 1, NULL, true),
    ('610.01', 'Participación de los trabajadores en las utilidades diferida', 2, NULL, true),
    ('611', 'Impuesto Sobre la renta', 1, NULL, true),
    ('611.01', 'Impuesto Sobre la renta', 2, NULL, true),
    ('611.02', 'Impuesto Sobre la renta por remanente distribuible', 2, NULL, true),
    ('612', 'Gastos no deducibles para CUFIN', 1, NULL, true),
    ('612.01', 'Gastos no deducibles para CUFIN', 2, NULL, true),
    ('613', 'Depreciación contable', 1, NULL, true),
    ('613.01', 'Depreciación de edificios', 2, NULL, true),
    ('613.02', 'Depreciación de maquinaria y equipo', 2, NULL, true),
    ('613.03', 'Depreciación de automóviles, autobuses, camiones de carga, tractocamiones, montacargas y remolques', 2, NULL, true),
    ('613.04', 'Depreciación de mobiliario y equipo de oficina', 2, NULL, true),
    ('613.05', 'Depreciación de equipo de cómputo', 2, NULL, true),
    ('613.06', 'Depreciación de equipo de comunicación', 2, NULL, true),
    ('613.07', 'Depreciación de activos biológicos, vegetales y semovientes', 2, NULL, true),
    ('613.08', 'Depreciación de otros activos fijos', 2, NULL, true),
    ('613.09', 'Depreciación de ferrocarriles', 2, NULL, true),
    ('613.10', 'Depreciación de embarcaciones', 2, NULL, true),
    ('613.11', 'Depreciación de aviones', 2, NULL, true),
    ('613.12', 'Depreciación de troqueles, moldes, matrices y herramental', 2, NULL, true),
    ('613.13', 'Depreciación de equipo de comunicaciones telefónicas', 2, NULL, true),
    ('613.14', 'Depreciación de equipo de comunicación satelital', 2, NULL, true),
    ('613.15', 'Depreciación de equipo de adaptaciones para personas con capacidades diferentes', 2, NULL, true),
    ('613.16', 'Depreciación de maquinaria y equipo de generación de energía de fuentes renovables o de sistemas de cogeneración de electricidad eficiente', 2, NULL, true),
    ('613.17', 'Depreciación de adaptaciones y mejoras', 2, NULL, true),
    ('613.18', 'Depreciación de otra maquinaria y equipo', 2, NULL, true),
    ('614', 'Amortización contable', 1, NULL, true),
    ('614.01', 'Amortización de gastos diferidos', 2, NULL, true),
    ('614.02', 'Amortización de gastos pre operativos', 2, NULL, true),
    ('614.03', 'Amortización de regalías, asistencia técnica y otros gastos diferidos', 2, NULL, true),
    ('614.04', 'Amortización de activos intangibles', 2, NULL, true),
    ('614.05', 'Amortización de gastos de organización', 2, NULL, true),
    ('614.06', 'Amortización de investigación y desarrollo de mercado', 2, NULL, true),
    ('614.07', 'Amortización de marcas y patentes', 2, NULL, true),
    ('614.08', 'Amortización de crédito mercantil', 2, NULL, true),
    ('614.09', 'Amortización de gastos de instalación', 2, NULL, true),
    ('614.10', 'Amortización de otros activos diferidos', 2, NULL, true),
    ('700', 'Resultado integral de financiamiento', NULL, NULL, true),
    ('701', 'Gastos financieros', 1, NULL, true),
    ('701.01', 'Pérdida cambiaria', 2, NULL, true),
    ('701.02', 'Pérdida cambiaria nacional parte relacionada', 2, NULL, true),
    ('701.03', 'Pérdida cambiaria extranjero parte relacionada', 2, NULL, true),
    ('701.04', 'Intereses a cargo bancario nacional', 2, NULL, true),
    ('701.05', 'Intereses a cargo bancario extranjero', 2, NULL, true),
    ('701.06', 'Intereses a cargo de personas físicas nacional', 2, NULL, true),
    ('701.07', 'Intereses a cargo de personas físicas extranjero', 2, NULL, true),
    ('701.08', 'Intereses a cargo de personas morales nacional', 2, NULL, true),
    ('701.09', 'Intereses a cargo de personas morales extranjero', 2, NULL, true),
    ('701.10', 'Comisiones bancarias', 2, NULL, true),
    ('701.11', 'Otros gastos financieros', 2, NULL, true),
    ('702', 'Productos financieros', 1, NULL, true),
    ('702.01', 'Utilidad cambiaria', 2, NULL, true),
    ('702.02', 'Utilidad cambiaria nacional parte relacionada', 2, NULL, true),
    ('702.03', 'Utilidad cambiaria extranjero parte relacionada', 2, NULL, true),
    ('702.04', 'Intereses a favor bancarios nacional', 2, NULL, true),
    ('702.05', 'Intereses a favor bancarios extranjero', 2, NULL, true),
    ('702.06', 'Intereses a favor de personas físicas nacional', 2, NULL, true),
    ('702.07', 'Intereses a favor de personas físicas extranjero', 2, NULL, true),
    ('702.08', 'Intereses a favor de personas morales nacional', 2, NULL, true),
    ('702.09', 'Intereses a favor de personas morales extranjero', 2, NULL, true),
    ('702.10', 'Otros productos financieros', 2, NULL, true),
    ('703', 'Otros gastos', 1, NULL, true),
    ('703.01', 'Pérdida en venta y/o baja de terrenos', 2, NULL, true),
    ('703.02', 'Pérdida en venta y/o baja de edificios', 2, NULL, true),
    ('703.03', 'Pérdida en venta y/o baja de maquinaria y equipo', 2, NULL, true),
    ('703.04', 'Pérdida en venta y/o baja de automóviles, autobuses, camiones de carga, tractocamiones, montacargas y remolques', 2, NULL, true),
    ('703.05', 'Pérdida en venta y/o baja de mobiliario y equipo de oficina', 2, NULL, true),
    ('703.06', 'Pérdida en venta y/o baja de equipo de cómputo', 2, NULL, true),
    ('703.07', 'Pérdida en venta y/o baja de equipo de comunicación', 2, NULL, true),
    ('703.08', 'Pérdida en venta y/o baja de activos biológicos, vegetales y semovientes', 2, NULL, true),
    ('703.09', 'Pérdida en venta y/o baja de otros activos fijos', 2, NULL, true),
    ('703.10', 'Pérdida en venta y/o baja de ferrocarriles', 2, NULL, true),
    ('703.11', 'Pérdida en venta y/o baja de embarcaciones', 2, NULL, true),
    ('703.12', 'Pérdida en venta y/o baja de aviones', 2, NULL, true),
    ('703.13', 'Pérdida en venta y/o baja de troqueles, moldes, matrices y herramental', 2, NULL, true),
    ('703.14', 'Pérdida en venta y/o baja de equipo de comunicaciones telefónicas', 2, NULL, true),
    ('703.15', 'Pérdida en venta y/o baja de equipo de comunicación satelital', 2, NULL, true),
    ('703.16', 'Pérdida en venta y/o baja de equipo de adaptaciones para personas con capacidades diferentes', 2, NULL, true),
    ('703.17', 'Pérdida en venta y/o baja de maquinaria y equipo de generación de energía de fuentes renovables o de sistemas de cogeneración de electricidad eficiente', 2, NULL, true),
    ('703.18', 'Pérdida en venta y/o baja de otra maquinaria y equipo', 2, NULL, true),
    ('703.19', 'Pérdida por enajenación de acciones', 2, NULL, true),
    ('703.20', 'Pérdida por enajenación de partes sociales', 2, NULL, true),
    ('703.21', 'Otros gastos', 2, NULL, true),
    ('704', 'Otros productos', 1, NULL, true),
    ('704.01', 'Ganancia en venta y/o baja de terrenos', 2, NULL, true),
    ('704.02', 'Ganancia en venta y/o baja de edificios', 2, NULL, true),
    ('704.03', 'Ganancia en venta y/o baja de maquinaria y equipo', 2, NULL, true),
    ('704.04', 'Ganancia en venta y/o baja de automóviles, autobuses, camiones de carga, tractocamiones, montacargas y remolques', 2, NULL, true),
    ('704.05', 'Ganancia en venta y/o baja de mobiliario y equipo de oficina', 2, NULL, true),
    ('704.06', 'Ganancia en venta y/o baja de equipo de cómputo', 2, NULL, true),
    ('704.07', 'Ganancia en venta y/o baja de equipo de comunicación', 2, NULL, true),
    ('704.08', 'Ganancia en venta y/o baja de activos biológicos, vegetales y semovientes', 2, NULL, true),
    ('704.09', 'Ganancia en venta y/o baja de otros activos fijos', 2, NULL, true),
    ('704.10', 'Ganancia en venta y/o baja de ferrocarriles', 2, NULL, true),
    ('704.11', 'Ganancia en venta y/o baja de embarcaciones', 2, NULL, true),
    ('704.12', 'Ganancia en venta y/o baja de aviones', 2, NULL, true),
    ('704.13', 'Ganancia en venta y/o baja de troqueles, moldes, matrices y herramental', 2, NULL, true),
    ('704.14', 'Ganancia en venta y/o baja de equipo de comunicaciones telefónicas', 2, NULL, true),
    ('704.15', 'Ganancia en venta y/o baja de equipo de comunicación satelital', 2, NULL, true),
    ('704.16', 'Ganancia en venta y/o baja de equipo de adaptaciones para personas con capacidades diferentes', 2, NULL, true),
    ('704.17', 'Ganancia en venta de maquinaria y equipo de generación de energía de fuentes renovables o de sistemas de cogeneración de electricidad eficiente', 2, NULL, true),
    ('704.18', 'Ganancia en venta y/o baja de otra maquinaria y equipo', 2, NULL, true),
    ('704.19', 'Ganancia por enajenación de acciones', 2, NULL, true),
    ('704.20', 'Ganancia por enajenación de partes sociales', 2, NULL, true),
    ('704.21', 'Ingresos por estímulos fiscales', 2, NULL, true),
    ('704.22', 'Ingresos por condonación de adeudo', 2, NULL, true),
    ('704.23', 'Otros productos', 2, NULL, true),
    ('800', 'Cuentas de orden', NULL, NULL, true),
    ('801', 'UFIN del ejercicio', 1, NULL, true),
    ('801.01', 'UFIN', 2, NULL, true),
    ('801.02', 'Contra cuenta UFIN', 2, NULL, true),
    ('802', 'CUFIN del ejercicio', 1, NULL, true),
    ('802.01', 'CUFIN', 2, NULL, true),
    ('802.02', 'Contra cuenta CUFIN', 2, NULL, true),
    ('803', 'CUFIN de ejercicios anteriores', 1, NULL, true),
    ('803.01', 'CUFIN de ejercicios anteriores', 2, NULL, true),
    ('803.02', 'Contra cuenta CUFIN de ejercicios anteriores', 2, NULL, true),
    ('804', 'CUFINRE del ejercicio', 1, NULL, true),
    ('804.01', 'CUFINRE', 2, NULL, true),
    ('804.02', 'Contra cuenta CUFINRE', 2, NULL, true),
    ('805', 'CUFINRE de ejercicios anteriores', 1, NULL, true),
    ('805.01', 'CUFINRE de ejercicios anteriores', 2, NULL, true),
    ('805.02', 'Contra cuenta CUFINRE de ejercicios anteriores', 2, NULL, true),
    ('806', 'CUCA del ejercicio', 1, NULL, true),
    ('806.01', 'CUCA', 2, NULL, true),
    ('806.02', 'Contra cuenta CUCA', 2, NULL, true),
    ('807', 'CUCA de ejercicios anteriores', 1, NULL, true),
    ('807.01', 'CUCA de ejercicios anteriores', 2, NULL, true),
    ('807.02', 'Contra cuenta CUCA de ejercicios anteriores', 2, NULL, true),
    ('808', 'Ajuste anual por inflación acumulable', 1, NULL, true),
    ('808.01', 'Ajuste anual por inflación acumulable', 2, NULL, true),
    ('808.02', 'Acumulación del ajuste anual inflacionario', 2, NULL, true),
    ('809', 'Ajuste anual por inflación deducible', 1, NULL, true),
    ('809.01', 'Ajuste anual por inflación deducible', 2, NULL, true),
    ('809.02', 'Deducción del ajuste anual inflacionario', 2, NULL, true),
    ('810', 'Deducción de inversión', 1, NULL, true),
    ('810.01', 'Deducción de inversión', 2, NULL, true),
    ('810.02', 'Contra cuenta deducción de inversiones', 2, NULL, true),
    ('811', 'Utilidad o pérdida fiscal en venta y/o baja de activo fijo', 1, NULL, true),
    ('811.01', 'Utilidad o pérdida fiscal en venta y/o baja de activo fijo', 2, NULL, true),
    ('811.02', 'Contra cuenta utilidad o pérdida fiscal en venta y/o baja de activo fijo', 2, NULL, true),
    ('812', 'Utilidad o pérdida fiscal en venta acciones o partes sociales', 1, NULL, true),
    ('812.01', 'Utilidad o pérdida fiscal en venta acciones o partes sociales', 2, NULL, true),
    ('812.02', 'Contra cuenta utilidad o pérdida fiscal en venta acciones o partes sociales', 2, NULL, true),
    ('813', 'Pérdidas fiscales pendientes de amortizar actualizadas de ejercicios anteriores', 1, NULL, true),
    ('813.01', 'Pérdidas fiscales pendientes de amortizar actualizadas de ejercicios anteriores', 2, NULL, true),
    ('813.02', 'Actualización de pérdidas fiscales pendientes de amortizar de ejercicios anteriores', 2, NULL, true),
    ('814', 'Mercancías recibidas en consignación', 1, NULL, true),
    ('814.01', 'Mercancías recibidas en consignación', 2, NULL, true),
    ('814.02', 'Consignación de mercancías recibidas', 2, NULL, true),
    ('815', 'Crédito fiscal de IVA e IEPS por la importación de mercancías para empresas certificadas', 1, NULL, true),
    ('815.01', 'Crédito fiscal de IVA e IEPS por la importación de mercancías', 2, NULL, true),
    ('815.02', 'Importación de mercancías con aplicación de crédito fiscal de IVA e IEPS', 2, NULL, true),
    ('816', 'Crédito fiscal de IVA e IEPS por la importación de activos fijos para empresas certificadas', 1, NULL, true),
    ('816.01', 'Crédito fiscal de IVA e IEPS por la importación de activo fijo', 2, NULL, true),
    ('816.02', 'Importación de activo fijo con aplicación de crédito fiscal de IVA e IEPS', 2, NULL, true),
    ('899', 'Otras cuentas de orden', 1, NULL, true),
    ('899.01', 'Otras cuentas de orden', 2, NULL, true),
    ('899.02', 'Contra cuenta otras cuentas de orden', 2, NULL, true),
    ('000', 'Código para uso exclusivo de contribuyentes del sector financiero', NULL, NULL, true)
ON CONFLICT (codigo) DO UPDATE SET
    descripcion = EXCLUDED.descripcion,
    nivel = EXCLUDED.nivel,
    naturaleza = EXCLUDED.naturaleza,
    activo = EXCLUDED.activo,
    actualizado_en = now();

-- Verificación: total cargado y muestra de las primeras filas.
SELECT COUNT(*) AS total_codigos_agrupadores FROM sat.codigos_agrupadores;

SELECT codigo, descripcion, nivel, naturaleza
FROM sat.codigos_agrupadores
ORDER BY codigo
LIMIT 20;

COMMIT;
