import { useEffect, useState } from 'react';
import { Alert, Autocomplete, Box, Button, Checkbox, Chip, CircularProgress, Dialog, DialogActions, DialogContent, DialogTitle, FormControlLabel, IconButton, Stack, TextField, Typography } from '@mui/material';
import EditOutlinedIcon from '@mui/icons-material/EditOutlined';
import DeleteOutlineIcon from '@mui/icons-material/DeleteOutline';
import AddIcon from '@mui/icons-material/Add';
import type { ContactoDomicilio } from '../../types/contactos.types';
import { actualizarDomicilioContacto, crearDomicilioContacto, eliminarDomicilioContacto, listarDomiciliosContacto } from '../../services/contactos.api';
import { apiFetch } from '../../services/apiFetch';

const fields = ['identificador','responsable','calle','numero_exterior','numero_interior','colonia','ciudad','estado','cp','pais','cruces','recibe','telefono_recibe','telefono','fax','observaciones','tipo_referencia','latitud','longitud','coto_o_fraccionamiento'] as const;
const labels: Record<string, string> = { identificador:'Identificador', responsable:'Responsable', calle:'Calle', numero_exterior:'Número exterior', numero_interior:'Número interior', colonia:'Colonia', ciudad:'Ciudad / localidad', estado:'Estado', cp:'Código postal', pais:'País', cruces:'Cruces / referencia', recibe:'Recibe', telefono_recibe:'Teléfono de recepción', telefono:'Teléfono', fax:'Fax', observaciones:'Observaciones', cp_sat:'Código postal SAT', colonia_sat:'Colonia SAT', tipo_referencia:'Tipo de referencia', latitud:'Latitud', longitud:'Longitud', coto_o_fraccionamiento:'Coto / fraccionamiento' };
const empty = (): Partial<ContactoDomicilio> => ({ identificador:'', activo:true, es_principal:false });
const addressSummary = (row: ContactoDomicilio) => [row.calle, row.numero_exterior, row.numero_interior, row.colonia, row.ciudad, row.estado, row.cp].filter(Boolean).join(', ') || 'Sin datos de ubicación';

export default function ContactoDomiciliosSection({ contactoId }: { contactoId: number }) {
  const [rows, setRows] = useState<ContactoDomicilio[]>([]); const [form, setForm] = useState<Partial<ContactoDomicilio>>(empty()); const [editing, setEditing] = useState<number|null>(null); const [dialogOpen, setDialogOpen] = useState(false); const [error, setError] = useState('');
  const [cpLoading, setCpLoading] = useState(false); const [cpError, setCpError] = useState(''); const [colonias, setColonias] = useState<{ colonia:string; texto:string }[]>([]);
  const load = async () => { try { setRows(await listarDomiciliosContacto(contactoId)); } catch (e) { setError(e instanceof Error ? e.message : 'No se pudieron cargar las ubicaciones'); } };
  useEffect(() => { void load(); }, [contactoId]);
  useEffect(() => { let alive = true; const cp = String(form.cp_sat ?? '').trim(); if (cp.length !== 5) { setColonias([]); return; } setCpLoading(true); setCpError(''); void (async () => { try { const data = await apiFetch<{ codigo_postal?:string; estado?:{nombre?:string}; municipio?:{nombre?:string}; localidad?:{nombre?:string}; colonias?:{clave:string;nombre:string}[] }>(`/api/sat/codigos-postales/${cp}`); const items = (data.colonias ?? []).map(c => ({ colonia:c.clave, texto:c.nombre })); if (!alive) return; setColonias(items); setForm(prev => ({ ...prev, cp: data.codigo_postal || cp, estado: data.estado?.nombre || prev.estado, ciudad: data.localidad?.nombre || data.municipio?.nombre || prev.ciudad, colonia_sat: items.some(c => c.colonia === prev.colonia_sat) ? prev.colonia_sat : '' })); } catch { if (alive) { setColonias([]); setCpError('El código postal SAT no se encontró'); setForm(prev => ({ ...prev, colonia_sat:'' })); } } finally { if (alive) setCpLoading(false); } })(); return () => { alive = false; }; }, [form.cp_sat]);
  const openNew = () => { setEditing(null); setForm(empty()); setError(''); setDialogOpen(true); }; const openEdit = (row: ContactoDomicilio) => { setEditing(row.id); setForm({ ...row }); setError(''); setDialogOpen(true); }; const closeDialog = () => { setDialogOpen(false); setEditing(null); setForm(empty()); setCpError(''); };
  const save = async () => { try { setError(''); if (!form.identificador?.trim()) { setError('El identificador es obligatorio'); return; } if (editing !== null) await actualizarDomicilioContacto(contactoId, editing, form); else await crearDomicilioContacto(contactoId, form); closeDialog(); await load(); } catch (e) { setError(e instanceof Error ? e.message : 'No se pudo guardar la ubicación'); } };
  const remove = async (row: ContactoDomicilio) => { try { setError(''); await eliminarDomicilioContacto(contactoId, row.id); await load(); } catch (e) { setError(e instanceof Error ? e.message : 'No se pudo eliminar la ubicación'); } };
  return <Stack spacing={2}>
    <Stack direction={{ xs:'column', sm:'row' }} justifyContent="space-between" alignItems={{ xs:'stretch', sm:'center' }} gap={1}><Typography variant="h6" sx={{ color: (theme) => theme.emphasys.content.foreground }}>Ubicaciones adicionales</Typography><Button variant="contained" startIcon={<AddIcon />} onClick={openNew} sx={{ alignSelf:{ xs:'flex-start', sm:'auto' } }}>Nueva ubicación</Button></Stack>
    {error && !dialogOpen && <Alert severity="error">{error}</Alert>}
    <Stack spacing={1}>{rows.length === 0 && <Typography color="text.secondary" sx={{ py:2 }}>No hay ubicaciones adicionales.</Typography>}{rows.map(row => <Stack key={row.id} direction={{ xs:'column', sm:'row' }} alignItems={{ xs:'stretch', sm:'center' }} spacing={{ xs:1, sm:2 }} sx={{ borderBottom:'1px solid #e5e7eb', px:{ xs:1, sm:1.5 }, py:1.25, opacity:row.activo ? 1 : .68 }}><Box sx={{ minWidth:0, flex:1 }}><Typography fontWeight={700}>{row.identificador}</Typography><Typography variant="body2" color="text.secondary" sx={{ overflow:'hidden', textOverflow:'ellipsis', whiteSpace:{ sm:'nowrap' } }}>{addressSummary(row)}</Typography></Box><Stack direction="row" spacing={.75} alignItems="center" flexWrap="wrap">{row.es_principal && <Chip label="Principal" size="small" color="primary" variant="outlined" />}{row.activo ? <Chip label="Activo" size="small" color="success" variant="outlined" /> : <Chip label="Inactivo" size="small" variant="outlined" />}</Stack><Stack direction="row" alignItems="center" justifyContent="flex-end"><Button size="small" startIcon={<EditOutlinedIcon />} onClick={() => openEdit(row)}>Editar</Button>{!row.es_principal && !row.activo && <IconButton size="small" aria-label="Eliminar ubicación" color="error" onClick={() => void remove(row)}><DeleteOutlineIcon fontSize="small" /></IconButton>}</Stack></Stack>)}</Stack>
    <Dialog open={dialogOpen} onClose={closeDialog} fullWidth maxWidth="md" fullScreen={false}><DialogTitle>{editing !== null ? 'Editar ubicación' : 'Nueva ubicación'}</DialogTitle><DialogContent dividers><Stack spacing={2} sx={{ pt:1 }}><Stack direction="row" flexWrap="wrap" gap={1.25}>{fields.map(field => <TextField key={field} label={labels[field]} value={(form as any)[field] ?? ''} onChange={e => setForm(prev => ({...prev,[field]:e.target.value}))} size="small" sx={{ flex:'1 1 220px' }} />)}</Stack><Stack direction={{ xs:'column', sm:'row' }} gap={1.25}><TextField label="Código postal SAT" value={form.cp_sat ?? ''} onChange={e => setForm(prev => ({...prev,cp_sat:e.target.value.replace(/\D/g,'').slice(0,5),colonia_sat:''}))} size="small" sx={{ flex:'1 1 220px' }} error={Boolean(cpError)} helperText={cpError || (cpLoading ? 'Cargando datos geográficos…' : 'Captura 5 dígitos')} InputProps={{ endAdornment: cpLoading ? <CircularProgress size={18} /> : undefined }} /><Autocomplete options={colonias} loading={cpLoading} disabled={!form.cp_sat || form.cp_sat.length !== 5} value={colonias.find(c => c.colonia === form.colonia_sat) ?? null} getOptionLabel={o => o.texto} onChange={(_, value) => setForm(prev => ({...prev,colonia_sat:value?.colonia ?? '',colonia:value?.texto ?? prev.colonia}))} renderInput={params => <TextField {...params} label="Colonia SAT" size="small" placeholder="Selecciona una colonia" />} noOptionsText="Sin colonias válidas" sx={{ flex:'1 1 280px' }} /></Stack><Stack direction={{ xs:'column', sm:'row' }}><FormControlLabel control={<Checkbox checked={Boolean(form.es_principal)} onChange={e => setForm(prev => ({...prev,es_principal:e.target.checked}))} />} label="Marcar como principal" /><FormControlLabel control={<Checkbox checked={form.activo !== false} onChange={e => setForm(prev => ({...prev,activo:e.target.checked}))} />} label="Activo" /></Stack>{error && <Alert severity="error">{error}</Alert>}</Stack></DialogContent><DialogActions><Button onClick={closeDialog}>Cancelar</Button><Button variant="contained" onClick={() => void save()}>{editing !== null ? 'Guardar cambios' : 'Guardar ubicación'}</Button></DialogActions></Dialog>
  </Stack>;
}
