"use client"
import { useEffect,useState } from "react"
import { CalendarClock,RotateCcw } from "lucide-react"
import { Button } from "@/components/ui/button"
import { Drawer,DrawerClose,DrawerContent,DrawerFooter,DrawerHeader,DrawerTitle } from "@/components/ui/drawer"
import { Textarea } from "@/components/ui/textarea"
import { Field,FieldLabel } from "@/components/ui/field"
import { useRealWork } from "@/lib/real-work-store"
import { fechaHoraLocalAISOString,formatFechaHora,formatHora } from "@/lib/format"
import type { Actividad,ActividadEstado } from "../../../services/compassService"
type Modo="cerrar"|"reprogramar"|"siguiente"
const estados:Exclude<ActividadEstado,"programada">[]=["realizada","parcial","no_realizada","cancelada"]
export function CerrarActividadDrawer({actividad,open,onOpenChange,onSaved,modoInicial}:{actividad:Actividad|null;open:boolean;onOpenChange:(v:boolean)=>void;onSaved?:()=>void|Promise<void>;modoInicial?:Modo}) {
 const { cerrarActividad,reprogramarActividad,continuarActividad,loading }=useRealWork()
 const [modo,setModo]=useState<Modo>("cerrar"); const [estado,setEstado]=useState<Exclude<ActividadEstado,"programada">>("realizada"); const [minutos,setMinutos]=useState(""); const [resultado,setResultado]=useState(""); const [nuevoInicio,setNuevoInicio]=useState("")
 useEffect(()=>{if(actividad&&open){setModo(modoInicial??"cerrar");setEstado("realizada");setMinutos(String(Math.round((new Date(actividad.fin_programado).getTime()-new Date(actividad.inicio_programado).getTime())/60000)));setResultado("");setNuevoInicio("")}},[actividad,open,modoInicial])
 if(!actividad)return null
 const persist=async()=>{if(modo==="cerrar")await cerrarActividad(actividad.id,{estado,minutos_efectivos:estado==="realizada"||estado==="parcial"?Number(minutos)||0:null,resultado:resultado.trim()||null});else {if(!nuevoInicio)return;const start=new Date(fechaHoraLocalAISOString(nuevoInicio));const duration=new Date(actividad.fin_programado).getTime()-new Date(actividad.inicio_programado).getTime();const payload={nuevo_inicio:start.toISOString(),nuevo_fin:new Date(start.getTime()+duration).toISOString()};if(modo==="reprogramar")await reprogramarActividad(actividad.id,payload);else await continuarActividad(actividad.id,payload)};onOpenChange(false);await onSaved?.()}
 return <Drawer open={open} onOpenChange={onOpenChange} showSwipeHandle><DrawerContent><DrawerHeader><DrawerTitle className="font-heading text-lg">{actividad.titulo}</DrawerTitle><p className="text-sm text-muted-foreground">{formatFechaHora(actividad.inicio_programado)} – {formatHora(actividad.fin_programado)}</p></DrawerHeader>{modo==="cerrar"?<div className="flex flex-col gap-4 px-4 py-3"><Field><FieldLabel>¿Se realizó?</FieldLabel><select value={estado} onChange={e=>setEstado(e.target.value as Exclude<ActividadEstado,"programada">)} className="h-9 rounded-md border border-input bg-transparent px-3 text-sm">{estados.map(e=><option key={e} value={e}>{e.replace("_"," ")}</option>)}</select></Field>{(estado==="realizada"||estado==="parcial")&&<Field><FieldLabel>Tiempo efectivo (minutos)</FieldLabel><input type="number" min={0} value={minutos} onChange={e=>setMinutos(e.target.value)} className="h-9 rounded-md border border-input bg-transparent px-3 text-sm" /></Field>}<Field><FieldLabel>Resultado o comentario</FieldLabel><Textarea value={resultado} onChange={e=>setResultado(e.target.value)} /></Field></div>:<div className="px-4 py-3"><Field><FieldLabel>Nueva fecha y hora</FieldLabel><input type="datetime-local" value={nuevoInicio} onChange={e=>setNuevoInicio(e.target.value)} className="h-9 w-full rounded-md border border-input bg-transparent px-3 text-sm" /></Field></div>}<DrawerFooter>{modo==="cerrar"?<><Button onClick={()=>void persist()} disabled={loading}>Cerrar actividad</Button><div className="grid grid-cols-2 gap-2"><Button variant="outline" onClick={()=>setModo("reprogramar")}><RotateCcw />Reprogramar</Button><Button variant="outline" onClick={()=>setModo("siguiente")}><CalendarClock />Programar siguiente</Button></div><DrawerClose render={<Button variant="ghost">Cancelar</Button>} /></>:<><Button onClick={()=>void persist()} disabled={!nuevoInicio||loading}>{modo==="reprogramar"?"Confirmar reprogramación":"Crear siguiente actividad"}</Button><Button variant="ghost" onClick={()=>setModo("cerrar")}>Volver</Button></>}</DrawerFooter></DrawerContent></Drawer>
}
