import express from 'express';
import multer from 'multer';
import path from 'path';
import fs from 'fs/promises';
import { requireAuth, requireEmpresaActiva } from '../auth/auth.middleware';
import pool from '../../config/database';

const router = express.Router();
const upload = multer({ storage: multer.memoryStorage(), limits: { fileSize: 5 * 1024 * 1024 }, fileFilter: (_req, file, cb) => cb(null, ['application/pdf','image/png','image/jpeg'].includes(file.mimetype)) });
const root = () => path.resolve(process.env.DOCUMENTACION_STORAGE_DIR || path.join(process.cwd(), 'private-storage', 'documentacion', 'documentos_empresa'));
const safeName = (name: string) => `${Date.now()}-${Math.random().toString(16).slice(2)}${path.extname(name).toLowerCase()}`;
router.use(requireAuth, requireEmpresaActiva);

router.get('/tipos', async (_req,res)=>{ const r=await pool.query('SELECT id,nombre,descripcion,requiere_vigencia,dias_vigencia,activo FROM documentacion.documentos_empresa_tipos WHERE activo=true ORDER BY nombre'); res.json(r.rows); });
router.get('/', async (req:any,res)=>{ const r=await pool.query(`SELECT d.*,t.nombre tipo_nombre,u.nombre usuario_nombre,u.email usuario_email FROM documentacion.documentos_empresa d JOIN documentacion.documentos_empresa_tipos t ON t.id=d.tipo_id LEFT JOIN core.usuarios u ON u.id=d.usuario_subio_id WHERE d.empresa_id=$1 ORDER BY d.fecha_subida DESC`,[req.context.empresaId]); res.json(r.rows); });
router.get('/:id', async (req:any,res)=>{ const r=await pool.query(`SELECT d.*,t.nombre tipo_nombre,u.nombre usuario_nombre,u.email usuario_email FROM documentacion.documentos_empresa d JOIN documentacion.documentos_empresa_tipos t ON t.id=d.tipo_id LEFT JOIN core.usuarios u ON u.id=d.usuario_subio_id WHERE d.id=$1 AND d.empresa_id=$2`,[req.params.id,req.context.empresaId]); if(!r.rowCount)return res.status(404).json({message:'Documento no encontrado'}); res.json(r.rows[0]); });
router.get('/:id/archivo', async (req:any,res)=>{ const r=await pool.query('SELECT archivo_url,nombre_original FROM documentacion.documentos_empresa WHERE id=$1 AND empresa_id=$2',[req.params.id,req.context.empresaId]); if(!r.rowCount)return res.status(404).json({message:'Documento no encontrado'}); if(String(r.rows[0].archivo_url).startsWith('DICOR_PENDIENTE/'))return res.status(409).json({message:'El archivo físico de este documento está pendiente de migración.'}); const file=path.resolve(root(),r.rows[0].archivo_url); if(!file.startsWith(path.resolve(root())+path.sep))return res.status(400).json({message:'Ruta inválida'}); try { await fs.access(file); return res.download(file,r.rows[0].nombre_original); } catch { return res.status(404).json({message:'Archivo no encontrado'}); } });
router.post('/', upload.single('archivo'), async (req:any,res)=>{ if(!req.file)return res.status(400).json({message:'Archivo requerido o tipo no permitido'}); const tipo=await pool.query('SELECT id FROM documentacion.documentos_empresa_tipos WHERE id=$1 AND activo=true',[req.body.tipo_id]); if(!tipo.rowCount)return res.status(400).json({message:'Tipo de documento inválido'}); const dir=path.join(root(),String(req.context.empresaId)); await fs.mkdir(dir,{recursive:true}); const filename=safeName(req.file.originalname); await fs.writeFile(path.join(dir,filename),req.file.buffer); try { const r=await pool.query(`INSERT INTO documentacion.documentos_empresa(empresa_id,tipo_id,archivo_url,nombre_original,fecha_vencimiento,comentarios,usuario_subio_id) VALUES($1,$2,$3,$4,$5,$6,$7) RETURNING *`,[req.context.empresaId,req.body.tipo_id,path.join(String(req.context.empresaId),filename).replace(/\\/g,'/'),req.file.originalname,req.body.fecha_vencimiento||null,req.body.comentarios||null,req.auth.userId]); return res.status(201).json(r.rows[0]); } catch(e) { await fs.unlink(path.join(dir,filename)).catch(()=>{}); throw e; } });
router.delete('/:id', async (req:any,res)=>{ const r=await pool.query('SELECT archivo_url FROM documentacion.documentos_empresa WHERE id=$1 AND empresa_id=$2',[req.params.id,req.context.empresaId]); if(!r.rowCount)return res.status(404).json({message:'Documento no encontrado'}); await pool.query('DELETE FROM documentacion.documentos_empresa WHERE id=$1 AND empresa_id=$2',[req.params.id,req.context.empresaId]); await fs.unlink(path.join(root(),r.rows[0].archivo_url)).catch(()=>{}); res.status(204).send(); });
export default router;
