CREATE TABLE IF NOT EXISTS public.contactos_documentacion_tipos (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre varchar(120) NOT NULL UNIQUE,
  activo boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now()
);

INSERT INTO public.contactos_documentacion_tipos (nombre) VALUES
  ('Licencia de conducir'), ('Identificación'), ('Constancia fiscal'), ('Contrato'), ('Otro')
ON CONFLICT (nombre) DO NOTHING;

CREATE TABLE IF NOT EXISTS public.contactos_documentacion (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  empresa_id integer NOT NULL REFERENCES core.empresas(id),
  contacto_id integer NOT NULL,
  tipo_id integer NOT NULL REFERENCES public.contactos_documentacion_tipos(id),
  nombre_original varchar(255) NOT NULL,
  mime_type varchar(120) NOT NULL,
  tamano bigint NOT NULL,
  storage_key text NOT NULL UNIQUE,
  fecha_vencimiento date,
  comentarios text,
  creado_por integer REFERENCES core.usuarios(id),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT fk_contactos_documentacion_contacto FOREIGN KEY (contacto_id)
    REFERENCES public.contactos(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_contactos_documentacion_empresa_contacto
  ON public.contactos_documentacion (empresa_id, contacto_id);
CREATE INDEX IF NOT EXISTS idx_contactos_documentacion_tipo
  ON public.contactos_documentacion (tipo_id);
