-- Extensión reusable para el cierre operativo de facturas de compra FULL.
-- No agrega columnas a documentos ni migra datos legacy.

CREATE TABLE IF NOT EXISTS public.operaciones_full (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    empresa_id integer NOT NULL REFERENCES core.empresas(id) ON DELETE RESTRICT,
    documento_id integer NOT NULL UNIQUE REFERENCES public.documentos(id) ON DELETE CASCADE,
    partida_id integer REFERENCES public.documentos_partidas(id) ON DELETE RESTRICT,
    estado_operativo varchar(20) NOT NULL DEFAULT 'abierto',
    litros_castigados numeric(15,6) NOT NULL DEFAULT 0,
    motivo_cierre text,
    fecha_cierre timestamptz,
    usuario_cierre_id integer REFERENCES core.usuarios(id) ON DELETE RESTRICT,
    fecha_creacion timestamptz NOT NULL DEFAULT now(),
    fecha_modificacion timestamptz,
    CONSTRAINT operaciones_full_estado_check CHECK (estado_operativo IN ('abierto','cerrado')),
    CONSTRAINT operaciones_full_litros_check CHECK (litros_castigados >= 0),
    CONSTRAINT operaciones_full_cierre_consistente_check CHECK (
      (estado_operativo = 'abierto' AND motivo_cierre IS NULL AND fecha_cierre IS NULL AND usuario_cierre_id IS NULL)
      OR (estado_operativo = 'cerrado' AND fecha_cierre IS NOT NULL AND usuario_cierre_id IS NOT NULL)
    ),
    CONSTRAINT operaciones_full_motivo_check CHECK (motivo_cierre IS NULL OR btrim(motivo_cierre) <> '')
);

CREATE TABLE IF NOT EXISTS public.operaciones_full_cierres (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    operacion_full_id integer NOT NULL REFERENCES public.operaciones_full(id) ON DELETE CASCADE,
    documento_id integer NOT NULL REFERENCES public.documentos(id) ON DELETE CASCADE,
    partida_id integer REFERENCES public.documentos_partidas(id) ON DELETE RESTRICT,
    estado_resultante varchar(20) NOT NULL,
    litros_castigados numeric(15,6) NOT NULL,
    motivo text NOT NULL,
    fecha_cierre timestamptz NOT NULL DEFAULT now(),
    usuario_id integer NOT NULL REFERENCES core.usuarios(id) ON DELETE RESTRICT,
    CONSTRAINT operaciones_full_cierres_estado_check CHECK (estado_resultante = 'cerrado'),
    CONSTRAINT operaciones_full_cierres_litros_check CHECK (litros_castigados >= 0),
    CONSTRAINT operaciones_full_cierres_motivo_check CHECK (btrim(motivo) <> '')
);

CREATE INDEX IF NOT EXISTS idx_operaciones_full_empresa_estado
  ON public.operaciones_full (empresa_id, estado_operativo);
CREATE INDEX IF NOT EXISTS idx_operaciones_full_cierres_documento_fecha
  ON public.operaciones_full_cierres (documento_id, fecha_cierre DESC);

COMMENT ON TABLE public.operaciones_full IS 'Estado operativo especializado de una factura de compra FULL; no sustituye el estado documental, financiero ni de entregas.';
COMMENT ON TABLE public.operaciones_full_cierres IS 'Historial append-only de cierres operativos FULL.';
COMMENT ON COLUMN public.operaciones_full.litros_castigados IS 'Litros operativos castigados; no altera cantidad comprada ni importes financieros.';
