-- Normaliza el bloque funcional de estados de cuenta importados.
-- Renombra tablas antiguas cuando existen y crea el modelo acumulado cuando no existen.
-- No modifica datos ni cambia el comportamiento de conciliación.

DO $$
BEGIN
  IF to_regclass('public.finanzas_importaciones_bancarias') IS NOT NULL
     AND to_regclass('public.finanzas_estados_cuenta_importados') IS NOT NULL THEN
    RAISE EXCEPTION 'Existen simultáneamente la tabla antigua y nueva de estados de cuenta importados; no se fusionarán datos';
  ELSIF to_regclass('public.finanzas_importaciones_bancarias') IS NOT NULL THEN
    ALTER TABLE public.finanzas_importaciones_bancarias RENAME TO finanzas_estados_cuenta_importados;
  END IF;
  IF to_regclass('public.finanzas_movimientos_bancarios') IS NOT NULL
     AND to_regclass('public.finanzas_estados_cuenta_importados_movimientos') IS NOT NULL THEN
    RAISE EXCEPTION 'Existen simultáneamente la tabla antigua y nueva de movimientos; no se fusionarán datos';
  ELSIF to_regclass('public.finanzas_movimientos_bancarios') IS NOT NULL THEN
    ALTER TABLE public.finanzas_movimientos_bancarios RENAME TO finanzas_estados_cuenta_importados_movimientos;
  END IF;
  IF to_regclass('public.finanzas_movimientos_bancarios_relaciones') IS NOT NULL
     AND to_regclass('public.finanzas_estados_cuenta_importados_relaciones') IS NOT NULL THEN
    RAISE EXCEPTION 'Existen simultáneamente la tabla antigua y nueva de relaciones; no se fusionarán datos';
  ELSIF to_regclass('public.finanzas_movimientos_bancarios_relaciones') IS NOT NULL THEN
    ALTER TABLE public.finanzas_movimientos_bancarios_relaciones RENAME TO finanzas_estados_cuenta_importados_relaciones;
  END IF;
END $$;

CREATE TABLE IF NOT EXISTS public.finanzas_estados_cuenta_importados (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    empresa_id bigint NOT NULL REFERENCES core.empresas(id),
    cuenta_id bigint NOT NULL REFERENCES public.finanzas_cuentas(id),
    nombre_original text NOT NULL,
    hash_archivo text NOT NULL,
    contenido_original bytea,
    codificacion text,
    formato_detectado text,
    parser_version text,
    fecha_inicial date,
    fecha_final date,
    saldo_inicial numeric(20,6),
    saldo_final numeric(20,6),
    total_cargos numeric(20,6) NOT NULL DEFAULT 0 CHECK (total_cargos >= 0),
    total_abonos numeric(20,6) NOT NULL DEFAULT 0 CHECK (total_abonos >= 0),
    total_filas integer NOT NULL DEFAULT 0 CHECK (total_filas >= 0),
    filas_validas integer NOT NULL DEFAULT 0 CHECK (filas_validas >= 0),
    filas_invalidas integer NOT NULL DEFAULT 0 CHECK (filas_invalidas >= 0),
    filas_nuevas integer NOT NULL DEFAULT 0 CHECK (filas_nuevas >= 0),
    filas_duplicadas integer NOT NULL DEFAULT 0 CHECK (filas_duplicadas >= 0),
    duplicados_omitidos jsonb NOT NULL DEFAULT '{}'::jsonb,
    estado text NOT NULL DEFAULT 'borrador' CHECK (estado IN ('borrador','procesada','conciliada','cancelada','revertida')),
    usuario_creacion_id bigint REFERENCES core.usuarios(id),
    fecha_creacion timestamptz NOT NULL DEFAULT now(),
    usuario_cancelacion_id bigint REFERENCES core.usuarios(id),
    fecha_cancelacion timestamptz,
    motivo_cancelacion text,
    usuario_finalizacion_id bigint REFERENCES core.usuarios(id),
    fecha_finalizacion timestamptz,
    saldo_calculado_final numeric(20,6),
    diferencia_final numeric(20,6),
    metadatos jsonb NOT NULL DEFAULT '{}'::jsonb,
    es_historica boolean NOT NULL DEFAULT false
);

COMMENT ON TABLE public.finanzas_estados_cuenta_importados IS 'Estado de cuenta importado y su resultado; no sustituye movimientos ni conciliaciones.';
COMMENT ON COLUMN public.finanzas_estados_cuenta_importados.hash_archivo IS 'Huella del archivo para detectar repeticiones por empresa.';
COMMENT ON COLUMN public.finanzas_estados_cuenta_importados.es_historica IS 'Indica que la importación proviene de un histórico migrado.';

CREATE TABLE IF NOT EXISTS public.finanzas_estados_cuenta_importados_movimientos (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    empresa_id bigint NOT NULL REFERENCES core.empresas(id),
    importacion_id bigint NOT NULL REFERENCES public.finanzas_estados_cuenta_importados(id) ON DELETE CASCADE,
    cuenta_id bigint NOT NULL REFERENCES public.finanzas_cuentas(id),
    numero_fila integer NOT NULL CHECK (numero_fila > 0),
    fecha date NOT NULL,
    hora time,
    concepto_bancario text,
    referencia_bancaria text,
    cargo numeric(20,6) NOT NULL DEFAULT 0 CHECK (cargo >= 0),
    abono numeric(20,6) NOT NULL DEFAULT 0 CHECK (abono >= 0),
    importe numeric(20,6) NOT NULL,
    tipo text NOT NULL CHECK (tipo IN ('Deposito','Retiro')),
    saldo_posterior numeric(20,6),
    linea_original text,
    hash_movimiento text NOT NULL,
    estado_revision text NOT NULL DEFAULT 'pendiente' CHECK (estado_revision IN ('pendiente','relacionado','sin_coincidencia','excluido')),
    activo boolean NOT NULL DEFAULT true,
    fecha_creacion timestamptz NOT NULL DEFAULT now(),
    motivo_exclusion text,
    usuario_exclusion_id bigint REFERENCES core.usuarios(id),
    fecha_exclusion timestamptz,
    datos_originales jsonb NOT NULL DEFAULT '{}'::jsonb,
    metadatos jsonb NOT NULL DEFAULT '{}'::jsonb,
    saldo_disponible boolean,
    es_historico boolean NOT NULL DEFAULT false,
    CONSTRAINT uq_finanzas_estados_cuenta_importados_movimientos_fila UNIQUE (importacion_id, numero_fila)
);

COMMENT ON TABLE public.finanzas_estados_cuenta_importados_movimientos IS 'Movimiento normalizado de un estado de cuenta importado, con datos originales para trazabilidad.';
COMMENT ON COLUMN public.finanzas_estados_cuenta_importados_movimientos.es_historico IS 'Indica que el movimiento proviene de un histórico migrado.';

CREATE TABLE IF NOT EXISTS public.finanzas_estados_cuenta_importados_relaciones (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    empresa_id bigint NOT NULL REFERENCES core.empresas(id),
    movimiento_bancario_id bigint NOT NULL REFERENCES public.finanzas_estados_cuenta_importados_movimientos(id) ON DELETE CASCADE,
    operacion_id bigint NOT NULL REFERENCES public.finanzas_operaciones(id),
    estado text NOT NULL DEFAULT 'sugerida' CHECK (estado IN ('sugerida','confirmada','anulada')),
    origen text NOT NULL DEFAULT 'manual' CHECK (origen IN ('automatico','manual','importacion')),
    puntuacion numeric(8,6) CHECK (puntuacion BETWEEN 0 AND 1),
    nivel_confianza text,
    explicacion text,
    motivos jsonb NOT NULL DEFAULT '{}'::jsonb,
    usuario_confirmacion_id bigint REFERENCES core.usuarios(id),
    fecha_confirmacion timestamptz,
    activa boolean NOT NULL DEFAULT true,
    fecha_creacion timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT uq_finanzas_estados_cuenta_importados_relacion UNIQUE (movimiento_bancario_id, operacion_id)
);

COMMENT ON TABLE public.finanzas_estados_cuenta_importados_relaciones IS 'Relación auditable entre movimiento de estado de cuenta importado y operación financiera.';

ALTER TABLE public.finanzas_estados_cuenta_importados
  ADD COLUMN IF NOT EXISTS es_historica boolean NOT NULL DEFAULT false;

ALTER TABLE public.finanzas_estados_cuenta_importados_movimientos
  ADD COLUMN IF NOT EXISTS es_historico boolean NOT NULL DEFAULT false;

ALTER TABLE public.finanzas_estados_cuenta_importados
  DROP CONSTRAINT IF EXISTS uq_finanzas_importaciones_empresa_hash,
  DROP CONSTRAINT IF EXISTS uq_finanzas_estados_cuenta_importados_empresa_hash;

ALTER TABLE public.finanzas_estados_cuenta_importados_movimientos
  DROP CONSTRAINT IF EXISTS uq_finanzas_movimientos_hash,
  DROP CONSTRAINT IF EXISTS uq_finanzas_estados_cuenta_importados_movimientos_hash;

CREATE INDEX IF NOT EXISTS ix_finanzas_estados_cuenta_importados_empresa_cuenta
  ON public.finanzas_estados_cuenta_importados (empresa_id, cuenta_id, fecha_creacion);
CREATE UNIQUE INDEX IF NOT EXISTS uq_finanzas_estados_cuenta_importados_empresa_hash_normal
  ON public.finanzas_estados_cuenta_importados (empresa_id, hash_archivo)
  WHERE es_historica = false;
CREATE INDEX IF NOT EXISTS ix_finanzas_estados_cuenta_importados_movimientos_empresa_fecha
  ON public.finanzas_estados_cuenta_importados_movimientos (empresa_id, cuenta_id, fecha);
CREATE INDEX IF NOT EXISTS ix_finanzas_estados_cuenta_importados_movimientos_estado
  ON public.finanzas_estados_cuenta_importados_movimientos (empresa_id, estado_revision);
CREATE UNIQUE INDEX IF NOT EXISTS uq_finanzas_estados_cuenta_importados_movimientos_hash_normal
  ON public.finanzas_estados_cuenta_importados_movimientos (empresa_id, cuenta_id, hash_movimiento)
  WHERE es_historico = false;
CREATE INDEX IF NOT EXISTS ix_finanzas_estados_cuenta_importados_relaciones_operacion
  ON public.finanzas_estados_cuenta_importados_relaciones (empresa_id, operacion_id);

DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'uq_finanzas_importaciones_empresa_hash')
     AND NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'uq_finanzas_estados_cuenta_importados_empresa_hash') THEN
    ALTER TABLE public.finanzas_estados_cuenta_importados
      RENAME CONSTRAINT uq_finanzas_importaciones_empresa_hash TO uq_finanzas_estados_cuenta_importados_empresa_hash;
  END IF;
  IF EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'uq_finanzas_movimientos_fila')
     AND NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'uq_finanzas_estados_cuenta_importados_movimientos_fila') THEN
    ALTER TABLE public.finanzas_estados_cuenta_importados_movimientos
      RENAME CONSTRAINT uq_finanzas_movimientos_fila TO uq_finanzas_estados_cuenta_importados_movimientos_fila;
  END IF;
  IF EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'uq_finanzas_movimientos_relacion')
     AND NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'uq_finanzas_estados_cuenta_importados_relacion') THEN
    ALTER TABLE public.finanzas_estados_cuenta_importados_relaciones
      RENAME CONSTRAINT uq_finanzas_movimientos_relacion TO uq_finanzas_estados_cuenta_importados_relacion;
  END IF;
END $$;

DO $$
BEGIN
  IF to_regclass('public.ix_finanzas_importaciones_empresa_cuenta') IS NOT NULL
     AND to_regclass('public.ix_finanzas_estados_cuenta_importados_empresa_cuenta') IS NULL THEN
    ALTER INDEX public.ix_finanzas_importaciones_empresa_cuenta RENAME TO ix_finanzas_estados_cuenta_importados_empresa_cuenta;
  END IF;
  IF to_regclass('public.uq_finanzas_importaciones_empresa_hash_normal') IS NOT NULL
     AND to_regclass('public.uq_finanzas_estados_cuenta_importados_empresa_hash_normal') IS NULL THEN
    ALTER INDEX public.uq_finanzas_importaciones_empresa_hash_normal RENAME TO uq_finanzas_estados_cuenta_importados_empresa_hash_normal;
  END IF;
  IF to_regclass('public.ix_finanzas_movimientos_empresa_fecha') IS NOT NULL
     AND to_regclass('public.ix_finanzas_estados_cuenta_importados_movimientos_empresa_fecha') IS NULL THEN
    ALTER INDEX public.ix_finanzas_movimientos_empresa_fecha RENAME TO ix_finanzas_estados_cuenta_importados_movimientos_empresa_fecha;
  END IF;
  IF to_regclass('public.ix_finanzas_movimientos_estado') IS NOT NULL
     AND to_regclass('public.ix_finanzas_estados_cuenta_importados_movimientos_estado') IS NULL THEN
    ALTER INDEX public.ix_finanzas_movimientos_estado RENAME TO ix_finanzas_estados_cuenta_importados_movimientos_estado;
  END IF;
  IF to_regclass('public.ix_finanzas_relaciones_operacion') IS NOT NULL
     AND to_regclass('public.ix_finanzas_estados_cuenta_importados_relaciones_operacion') IS NULL THEN
    ALTER INDEX public.ix_finanzas_relaciones_operacion RENAME TO ix_finanzas_estados_cuenta_importados_relaciones_operacion;
  END IF;
  IF to_regclass('public.uq_finanzas_movimientos_hash_normal') IS NOT NULL
     AND to_regclass('public.uq_finanzas_estados_cuenta_importados_movimientos_hash_normal') IS NULL THEN
    ALTER INDEX public.uq_finanzas_movimientos_hash_normal RENAME TO uq_finanzas_estados_cuenta_importados_movimientos_hash_normal;
  END IF;
END $$;
