BEGIN;

CREATE TABLE IF NOT EXISTS public.especificaciones_biblioteca (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    empresa_id integer NOT NULL REFERENCES core.empresas(id) ON DELETE RESTRICT,
    producto_id integer REFERENCES public.productos(id) ON DELETE CASCADE,
    alcance character varying(20) NOT NULL,
    tipo character varying(20) NOT NULL DEFAULT 'otro',
    contenido text NOT NULL,
    orden integer NOT NULL DEFAULT 0,
    es_preferida boolean NOT NULL DEFAULT false,
    fecha_baja timestamp with time zone,
    usuario_creacion_id integer REFERENCES core.usuarios(id) ON DELETE SET NULL,
    usuario_modificacion_id integer REFERENCES core.usuarios(id) ON DELETE SET NULL,
    usuario_baja_id integer REFERENCES core.usuarios(id) ON DELETE SET NULL,
    fecha_creacion timestamp with time zone NOT NULL DEFAULT now(),
    fecha_modificacion timestamp with time zone,
    CONSTRAINT chk_especificaciones_biblioteca_alcance
      CHECK (alcance IN ('global', 'producto')),
    CONSTRAINT chk_especificaciones_biblioteca_tipo
      CHECK (tipo IN ('medida', 'material', 'accesorio', 'garantia', 'entrega', 'condicion', 'otro')),
    CONSTRAINT chk_especificaciones_biblioteca_producto_alcance
      CHECK ((alcance = 'global' AND producto_id IS NULL) OR (alcance = 'producto' AND producto_id IS NOT NULL)),
    CONSTRAINT chk_especificaciones_biblioteca_orden CHECK (orden >= 0),
    CONSTRAINT chk_especificaciones_biblioteca_contenido CHECK (length(btrim(contenido)) > 0)
);

CREATE TABLE IF NOT EXISTS public.documentos_partidas_especificaciones (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    partida_id integer NOT NULL REFERENCES public.documentos_partidas(id) ON DELETE CASCADE,
    especificacion_biblioteca_id bigint REFERENCES public.especificaciones_biblioteca(id) ON DELETE SET NULL,
    orden integer NOT NULL DEFAULT 0,
    tipo character varying(20) NOT NULL DEFAULT 'otro',
    origen character varying(20) NOT NULL,
    contenido text NOT NULL,
    usuario_creacion_id integer REFERENCES core.usuarios(id) ON DELETE SET NULL,
    usuario_modificacion_id integer REFERENCES core.usuarios(id) ON DELETE SET NULL,
    fecha_creacion timestamp with time zone NOT NULL DEFAULT now(),
    fecha_modificacion timestamp with time zone,
    CONSTRAINT chk_documentos_partidas_especificaciones_tipo
      CHECK (tipo IN ('medida', 'material', 'accesorio', 'garantia', 'entrega', 'condicion', 'otro')),
    CONSTRAINT chk_documentos_partidas_especificaciones_origen
      CHECK (origen IN ('global', 'producto', 'manual', 'heredada')),
    CONSTRAINT chk_documentos_partidas_especificaciones_orden CHECK (orden >= 0),
    CONSTRAINT chk_documentos_partidas_especificaciones_contenido CHECK (length(btrim(contenido)) > 0),
    CONSTRAINT uq_documentos_partidas_especificaciones_orden UNIQUE (partida_id, orden)
);

CREATE INDEX IF NOT EXISTS idx_especificaciones_biblioteca_empresa_alcance_vigencia
    ON public.especificaciones_biblioteca (empresa_id, alcance, fecha_baja, es_preferida DESC, orden, id);
CREATE INDEX IF NOT EXISTS idx_especificaciones_biblioteca_producto_vigencia
    ON public.especificaciones_biblioteca (empresa_id, producto_id, fecha_baja, es_preferida DESC, orden, id);
CREATE INDEX IF NOT EXISTS idx_documentos_partidas_especificaciones_partida
    ON public.documentos_partidas_especificaciones (partida_id, orden, id);

CREATE OR REPLACE FUNCTION public.validar_empresa_especificacion_producto()
RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  IF NEW.producto_id IS NOT NULL AND NOT EXISTS (
    SELECT 1 FROM public.productos p
     WHERE p.id = NEW.producto_id AND p.empresa_id = NEW.empresa_id
  ) THEN
    RAISE EXCEPTION 'El producto no pertenece a la empresa de la especificacion';
  END IF;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_validar_empresa_especificacion_producto ON public.especificaciones_biblioteca;
CREATE TRIGGER trg_validar_empresa_especificacion_producto
BEFORE INSERT OR UPDATE OF empresa_id, producto_id ON public.especificaciones_biblioteca
FOR EACH ROW EXECUTE FUNCTION public.validar_empresa_especificacion_producto();

CREATE OR REPLACE FUNCTION public.validar_biblioteca_especificacion_partida()
RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE
  biblioteca_empresa_id integer;
  biblioteca_producto_id integer;
  biblioteca_alcance character varying(20);
  partida_empresa_id integer;
  partida_producto_id integer;
BEGIN
  IF NEW.origen = 'manual' AND NEW.especificacion_biblioteca_id IS NOT NULL THEN
    RAISE EXCEPTION 'Una especificacion manual no puede referir a la biblioteca';
  END IF;

  IF TG_OP = 'INSERT'
     AND NEW.origen IN ('global', 'producto')
     AND NEW.especificacion_biblioteca_id IS NULL THEN
    RAISE EXCEPTION 'El origen de biblioteca requiere una referencia valida';
  END IF;

  IF NEW.especificacion_biblioteca_id IS NULL THEN
    RETURN NEW;
  END IF;

  SELECT eb.empresa_id, eb.producto_id, eb.alcance
    INTO biblioteca_empresa_id, biblioteca_producto_id, biblioteca_alcance
    FROM public.especificaciones_biblioteca eb
   WHERE eb.id = NEW.especificacion_biblioteca_id;

  SELECT d.empresa_id, dp.producto_id
    INTO partida_empresa_id, partida_producto_id
    FROM public.documentos_partidas dp
    JOIN public.documentos d ON d.id = dp.documento_id
   WHERE dp.id = NEW.partida_id;

  IF biblioteca_empresa_id IS DISTINCT FROM partida_empresa_id THEN
    RAISE EXCEPTION 'La especificacion de biblioteca no pertenece a la empresa del documento';
  END IF;

  IF biblioteca_alcance = 'producto'
     AND biblioteca_producto_id IS DISTINCT FROM partida_producto_id THEN
    RAISE EXCEPTION 'La especificacion de biblioteca no pertenece al producto de la partida';
  END IF;

  IF NEW.origen = 'global' AND biblioteca_alcance <> 'global' THEN
    RAISE EXCEPTION 'El origen global no coincide con el alcance de la biblioteca';
  END IF;

  IF NEW.origen = 'producto' AND biblioteca_alcance <> 'producto' THEN
    RAISE EXCEPTION 'El origen producto no coincide con el alcance de la biblioteca';
  END IF;

  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_validar_biblioteca_especificacion_partida ON public.documentos_partidas_especificaciones;
CREATE TRIGGER trg_validar_biblioteca_especificacion_partida
BEFORE INSERT OR UPDATE OF partida_id, especificacion_biblioteca_id, origen
ON public.documentos_partidas_especificaciones
FOR EACH ROW EXECUTE FUNCTION public.validar_biblioteca_especificacion_partida();

COMMENT ON TABLE public.especificaciones_biblioteca IS 'Biblioteca multiempresa de especificaciones globales y propias de productos.';
COMMENT ON TABLE public.documentos_partidas_especificaciones IS 'Snapshot independiente y ordenado de especificaciones utilizadas en una partida de documento.';
COMMENT ON COLUMN public.documentos_partidas_especificaciones.especificacion_biblioteca_id IS 'Referencia informativa al origen; el contenido snapshot es la fuente documental autoritativa.';

COMMIT;
