-- Schema: inventario
-- Table: almacenes
-- Generated automatically

--
-- PostgreSQL database dump
--

-- Dumped from database version 14.22 (Ubuntu 14.22-0ubuntu0.22.04.1)
-- Dumped by pg_dump version 17.3

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_table_access_method = heap;

--
-- Name: almacenes; Type: TABLE; Schema: inventario; Owner: -
--

CREATE TABLE inventario.almacenes (
    id integer NOT NULL,
    empresa_id integer NOT NULL,
    clave character varying(30) NOT NULL,
    nombre character varying(120) NOT NULL,
    tipo character varying(30) DEFAULT 'normal'::character varying NOT NULL,
    activo boolean DEFAULT true NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone,
    CONSTRAINT chk_inventario_almacenes_clave_no_vacia CHECK ((btrim((clave)::text) <> ''::text)),
    CONSTRAINT chk_inventario_almacenes_nombre_no_vacio CHECK ((btrim((nombre)::text) <> ''::text)),
    CONSTRAINT chk_inventario_almacenes_tipo_no_vacio CHECK ((btrim((tipo)::text) <> ''::text))
);


--
-- Name: TABLE almacenes; Type: COMMENT; Schema: inventario; Owner: -
--

COMMENT ON TABLE inventario.almacenes IS 'Catálogo de almacenes por empresa para el módulo de inventario.';


--
-- Name: COLUMN almacenes.id; Type: COMMENT; Schema: inventario; Owner: -
--

COMMENT ON COLUMN inventario.almacenes.id IS 'Identificador único interno del almacén.';


--
-- Name: COLUMN almacenes.empresa_id; Type: COMMENT; Schema: inventario; Owner: -
--

COMMENT ON COLUMN inventario.almacenes.empresa_id IS 'Empresa a la que pertenece el almacén.';


--
-- Name: COLUMN almacenes.clave; Type: COMMENT; Schema: inventario; Owner: -
--

COMMENT ON COLUMN inventario.almacenes.clave IS 'Clave corta obligatoria del almacén, usada como identificador visible para los usuarios.';


--
-- Name: COLUMN almacenes.nombre; Type: COMMENT; Schema: inventario; Owner: -
--

COMMENT ON COLUMN inventario.almacenes.nombre IS 'Nombre descriptivo del almacén.';


--
-- Name: COLUMN almacenes.tipo; Type: COMMENT; Schema: inventario; Owner: -
--

COMMENT ON COLUMN inventario.almacenes.tipo IS 'Tipo de almacén: normal, transito, virtual, produccion, consignacion, etc.';


--
-- Name: COLUMN almacenes.activo; Type: COMMENT; Schema: inventario; Owner: -
--

COMMENT ON COLUMN inventario.almacenes.activo IS 'Indica si el almacén está activo para operación.';


--
-- Name: COLUMN almacenes.created_at; Type: COMMENT; Schema: inventario; Owner: -
--

COMMENT ON COLUMN inventario.almacenes.created_at IS 'Fecha y hora de creación del registro.';


--
-- Name: COLUMN almacenes.updated_at; Type: COMMENT; Schema: inventario; Owner: -
--

COMMENT ON COLUMN inventario.almacenes.updated_at IS 'Fecha y hora de la última actualización del registro.';


--
-- Name: almacenes_id_seq; Type: SEQUENCE; Schema: inventario; Owner: -
--

ALTER TABLE inventario.almacenes ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME inventario.almacenes_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: almacenes pk_inventario_almacenes; Type: CONSTRAINT; Schema: inventario; Owner: -
--

ALTER TABLE ONLY inventario.almacenes
    ADD CONSTRAINT pk_inventario_almacenes PRIMARY KEY (id);


--
-- Name: idx_inventario_almacenes_empresa_activo; Type: INDEX; Schema: inventario; Owner: -
--

CREATE INDEX idx_inventario_almacenes_empresa_activo ON inventario.almacenes USING btree (empresa_id, activo);


--
-- Name: INDEX idx_inventario_almacenes_empresa_activo; Type: COMMENT; Schema: inventario; Owner: -
--

COMMENT ON INDEX inventario.idx_inventario_almacenes_empresa_activo IS 'Índice para filtrar almacenes activos por empresa.';


--
-- Name: idx_inventario_almacenes_empresa_id; Type: INDEX; Schema: inventario; Owner: -
--

CREATE INDEX idx_inventario_almacenes_empresa_id ON inventario.almacenes USING btree (empresa_id);


--
-- Name: INDEX idx_inventario_almacenes_empresa_id; Type: COMMENT; Schema: inventario; Owner: -
--

COMMENT ON INDEX inventario.idx_inventario_almacenes_empresa_id IS 'Índice para búsquedas de almacenes por empresa.';


--
-- Name: idx_inventario_almacenes_empresa_nombre; Type: INDEX; Schema: inventario; Owner: -
--

CREATE INDEX idx_inventario_almacenes_empresa_nombre ON inventario.almacenes USING btree (empresa_id, nombre);


--
-- Name: INDEX idx_inventario_almacenes_empresa_nombre; Type: COMMENT; Schema: inventario; Owner: -
--

COMMENT ON INDEX inventario.idx_inventario_almacenes_empresa_nombre IS 'Índice para búsquedas y ordenamientos por nombre dentro de la empresa.';


--
-- Name: uq_inventario_almacenes_empresa_clave; Type: INDEX; Schema: inventario; Owner: -
--

CREATE UNIQUE INDEX uq_inventario_almacenes_empresa_clave ON inventario.almacenes USING btree (empresa_id, clave);


--
-- Name: INDEX uq_inventario_almacenes_empresa_clave; Type: COMMENT; Schema: inventario; Owner: -
--

COMMENT ON INDEX inventario.uq_inventario_almacenes_empresa_clave IS 'Garantiza que la clave del almacén no se repita dentro de una misma empresa.';


--
-- Name: almacenes fk_inventario_almacenes_empresa; Type: FK CONSTRAINT; Schema: inventario; Owner: -
--

ALTER TABLE ONLY inventario.almacenes
    ADD CONSTRAINT fk_inventario_almacenes_empresa FOREIGN KEY (empresa_id) REFERENCES core.empresas(id);


--
-- PostgreSQL database dump complete
--

