import type { PoolClient } from 'pg';
import pool from '../../config/database';
import type { CompassOwnerScope, ConvertirIdeaInput, DecisionInput, DecisionPatch, IdeaInput, IdeaPatch } from './compass.types';
import { CompassBusinessError, CompassNotFoundError } from './compass-work.repository';
const IDEA=`SELECT i.id,i.titulo,i.descripcion,i.frente_id,f.nombre frente_nombre,i.estado,i.tipo_conversion,i.conversion_id,i.fecha_archivo,i.created_at,i.updated_at FROM compass.ideas i LEFT JOIN compass.frentes f ON f.usuario_id=i.usuario_id AND f.id=i.frente_id`;
const DECISION=`SELECT d.id,d.titulo,d.descripcion,d.motivo,to_char(d.fecha_decision,'YYYY-MM-DD') fecha,d.frente_id,f.nombre frente_nombre,d.created_at,d.updated_at FROM compass.decisiones d LEFT JOIN compass.frentes f ON f.usuario_id=d.usuario_id AND f.id=d.frente_id`;
async function tx<T>(fn:(c:PoolClient)=>Promise<T>){const c=await pool.connect();try{await c.query('BEGIN');const r=await fn(c);await c.query('COMMIT');return r}catch(e){await c.query('ROLLBACK');throw e}finally{c.release()}}
async function frente(c:PoolClient,s:CompassOwnerScope,id:number|null){if(!id)return;const r=await c.query('SELECT id FROM compass.frentes WHERE usuario_id=$1 AND id=$2 FOR UPDATE',[s.usuarioId,id]);if(!r.rowCount)throw new CompassNotFoundError('Frente no encontrado')}
export async function listarIdeas(s:CompassOwnerScope,estado?:'activa'|'archivada'){const values:any[]=[s.usuarioId],where=['i.usuario_id=$1'];if(estado){values.push(estado);where.push(`i.estado=$${values.length}`)}return (await pool.query(`${IDEA} WHERE ${where.join(' AND ')} ORDER BY i.created_at DESC`,values)).rows}
export async function obtenerIdea(s:CompassOwnerScope,id:number,c:PoolClient|null=null,lock=false){const db=c??pool;return (await db.query(`${IDEA} WHERE i.usuario_id=$1 AND i.id=$2 LIMIT 1${lock?' FOR UPDATE OF i':''}`,[s.usuarioId,id])).rows[0]??null}
export async function crearIdea(s:CompassOwnerScope,input:IdeaInput){return tx(async c=>{await frente(c,s,input.frente_id);const r=await c.query<{id:number}>('INSERT INTO compass.ideas (empresa_id,usuario_id,titulo,descripcion,frente_id) VALUES ($1,$2,$3,$4,$5) RETURNING id',[s.empresaId,s.usuarioId,input.titulo,input.descripcion,input.frente_id]);return obtenerIdea(s,r.rows[0].id,c)})}
export async function actualizarIdea(s:CompassOwnerScope,id:number,patch:IdeaPatch){return tx(async c=>{const current=await obtenerIdea(s,id,c,true);if(!current)throw new CompassNotFoundError('Idea no encontrada');if(patch.frente_id)await frente(c,s,patch.frente_id);if(patch.estado==='activa'&&current.tipo_conversion)throw new CompassBusinessError('Una Idea convertida no puede reactivarse');const fields:string[]=[],values:any[]=[s.usuarioId,id];for(const [k,v]of Object.entries(patch)){values.push(v);fields.push(`${k}=$${values.length}`)}if(patch.estado==='archivada')fields.push('fecha_archivo=COALESCE(fecha_archivo,now())');if(patch.estado==='activa')fields.push('fecha_archivo=NULL');await c.query(`UPDATE compass.ideas SET ${fields.join(',')},updated_at=now() WHERE usuario_id=$1 AND id=$2`,values);return obtenerIdea(s,id,c)})}
async function validateActivity(c:PoolClient,s:CompassOwnerScope,frenteId:number|null,tareaId:number|null){await frente(c,s,frenteId);if(!tareaId)return;const r=await c.query('SELECT frente_id FROM compass.tareas WHERE usuario_id=$1 AND id=$2 FOR UPDATE',[s.usuarioId,tareaId]);if(!r.rows[0])throw new CompassNotFoundError('Tarea no encontrada');if((r.rows[0].frente_id??null)!==frenteId)throw new CompassBusinessError('El Frente de la Actividad debe coincidir con el de la Tarea')}
export async function convertirIdea(s:CompassOwnerScope,id:number,input:ConvertirIdeaInput){return tx(async c=>{const idea=await obtenerIdea(s,id,c,true);if(!idea)throw new CompassNotFoundError('Idea no encontrada');if(idea.estado!=='activa'||idea.tipo_conversion)throw new CompassBusinessError('La Idea ya fue archivada o convertida');let target:number;if(input.destino==='tarea'){await frente(c,s,input.frente_id);target=(await c.query('INSERT INTO compass.tareas (empresa_id,usuario_id,titulo,frente_id) VALUES ($1,$2,$3,$4) RETURNING id',[s.empresaId,s.usuarioId,idea.titulo,input.frente_id])).rows[0].id}else if(input.destino==='actividad'){await validateActivity(c,s,input.frente_id,input.tarea_id);target=(await c.query('INSERT INTO compass.actividades (empresa_id,usuario_id,titulo,frente_id,tarea_id,inicio_programado,fin_programado) VALUES ($1,$2,$3,$4,$5,$6,$7) RETURNING id',[s.empresaId,s.usuarioId,idea.titulo,input.frente_id,input.tarea_id,input.inicio_programado,input.fin_programado])).rows[0].id}else{target=(await c.query("INSERT INTO compass.frentes (empresa_id,usuario_id,nombre,proposito,categoria,estado) VALUES ($1,$2,$3,$4,$5,'activo') RETURNING id",[s.empresaId,s.usuarioId,input.nombre,input.proposito,input.categoria])).rows[0].id}await c.query("UPDATE compass.ideas SET estado='archivada',tipo_conversion=$3,conversion_id=$4,fecha_archivo=now(),updated_at=now() WHERE usuario_id=$1 AND id=$2",[s.usuarioId,id,input.destino,target]);return obtenerIdea(s,id,c)})}
export async function listarDecisiones(s:CompassOwnerScope){return (await pool.query(`${DECISION} WHERE d.usuario_id=$1 ORDER BY d.fecha_decision DESC,d.created_at DESC`,[s.usuarioId])).rows}
export async function obtenerDecision(s:CompassOwnerScope,id:number,c:PoolClient|null=null){return (await (c??pool).query(`${DECISION} WHERE d.usuario_id=$1 AND d.id=$2 LIMIT 1`,[s.usuarioId,id])).rows[0]??null}
export async function crearDecision(s:CompassOwnerScope,input:DecisionInput){return tx(async c=>{await frente(c,s,input.frente_id);const r=await c.query<{id:number}>('INSERT INTO compass.decisiones (empresa_id,usuario_id,titulo,descripcion,motivo,fecha_decision,frente_id) VALUES ($1,$2,$3,$4,$5,$6,$7) RETURNING id',[s.empresaId,s.usuarioId,input.titulo,input.descripcion,input.motivo,input.fecha_decision,input.frente_id]);return obtenerDecision(s,r.rows[0].id,c)})}
export async function actualizarDecision(s:CompassOwnerScope,id:number,patch:DecisionPatch){return tx(async c=>{if(!await obtenerDecision(s,id,c))throw new CompassNotFoundError('Decisión no encontrada');if(patch.frente_id)await frente(c,s,patch.frente_id);const fields:string[]=[],values:any[]=[s.usuarioId,id];for(const[k,v]of Object.entries(patch)){values.push(v);fields.push(`${k}=$${values.length}`)}await c.query(`UPDATE compass.decisiones SET ${fields.join(',')},updated_at=now() WHERE usuario_id=$1 AND id=$2`,values);return obtenerDecision(s,id,c)})}
