import { Router } from 'express';
import { optionalEmpresaActiva, requireAuth } from '../auth/auth.middleware';
import { getFrente, getFrentes, patchFrente, postFrente, putIntencionSemanal } from './compass.controller';
import { deleteActividad, getActividad, getActividades, getTarea, getTareas, patchActividad, patchTarea, postActividad, postCerrarActividad, postContinuarActividad, postReprogramarActividad, postTarea } from './compass.controller';
import { getCapturas, patchCaptura, postCaptura, postProcesarCaptura } from './compass.controller';
import { getDecision, getDecisiones, getIdea, getIdeas, patchDecision, patchIdea, postConvertirIdea, postDecision, postIdea } from './compass.controller';
import { getRevisionSemanal, putRevisionSemanal } from './compass.controller';

const router = Router();
router.use(requireAuth);
router.get('/frentes', optionalEmpresaActiva, getFrentes);
router.get('/frentes/:id', optionalEmpresaActiva, getFrente);
router.post('/frentes', optionalEmpresaActiva, postFrente);
router.patch('/frentes/:id', optionalEmpresaActiva, patchFrente);
router.put('/frentes/:id/intencion-semanal', optionalEmpresaActiva, putIntencionSemanal);
router.get('/tareas', optionalEmpresaActiva, getTareas);
router.get('/tareas/:id', optionalEmpresaActiva, getTarea);
router.post('/tareas', optionalEmpresaActiva, postTarea);
router.patch('/tareas/:id', optionalEmpresaActiva, patchTarea);
router.get('/actividades', optionalEmpresaActiva, getActividades);
router.get('/actividades/:id', optionalEmpresaActiva, getActividad);
router.post('/actividades', optionalEmpresaActiva, postActividad);
router.patch('/actividades/:id', optionalEmpresaActiva, patchActividad);
router.delete('/actividades/:id', optionalEmpresaActiva, deleteActividad);
router.post('/actividades/:id/cerrar', optionalEmpresaActiva, postCerrarActividad);
router.post('/actividades/:id/reprogramar', optionalEmpresaActiva, postReprogramarActividad);
router.post('/actividades/:id/continuar', optionalEmpresaActiva, postContinuarActividad);
router.get('/capturas', optionalEmpresaActiva, getCapturas);
router.post('/capturas', optionalEmpresaActiva, postCaptura);
router.patch('/capturas/:id', optionalEmpresaActiva, patchCaptura);
router.post('/capturas/:id/procesar', optionalEmpresaActiva, postProcesarCaptura);
router.get('/ideas', optionalEmpresaActiva, getIdeas);
router.get('/ideas/:id', optionalEmpresaActiva, getIdea);
router.post('/ideas', optionalEmpresaActiva, postIdea);
router.patch('/ideas/:id', optionalEmpresaActiva, patchIdea);
router.post('/ideas/:id/convertir', optionalEmpresaActiva, postConvertirIdea);
router.get('/decisiones', optionalEmpresaActiva, getDecisiones);
router.get('/decisiones/:id', optionalEmpresaActiva, getDecision);
router.post('/decisiones', optionalEmpresaActiva, postDecision);
router.patch('/decisiones/:id', optionalEmpresaActiva, patchDecision);
router.get('/revisiones-semanales/:semana_inicio', optionalEmpresaActiva, getRevisionSemanal);
router.put('/revisiones-semanales/:semana_inicio', optionalEmpresaActiva, putRevisionSemanal);
export default router;
