-- Soporte generalizable para importaciones y movimientos bancarios.
-- No migra datos de ningún sistema externo.

CREATE TABLE IF NOT EXISTS public.finanzas_importaciones_bancarias (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    empresa_id bigint NOT NULL REFERENCES core.empresas(id),
    cuenta_id bigint NOT NULL REFERENCES public.finanzas_cuentas(id),
    nombre_original text NOT NULL,
    hash_archivo text NOT NULL,
    contenido_original bytea,
    codificacion text,
    formato_detectado text,
    parser_version text,
    fecha_inicial date,
    fecha_final date,
    saldo_inicial numeric(20,6),
    saldo_final numeric(20,6),
    total_cargos numeric(20,6) NOT NULL DEFAULT 0 CHECK (total_cargos >= 0),
    total_abonos numeric(20,6) NOT NULL DEFAULT 0 CHECK (total_abonos >= 0),
    total_filas integer NOT NULL DEFAULT 0 CHECK (total_filas >= 0),
    filas_validas integer NOT NULL DEFAULT 0 CHECK (filas_validas >= 0),
    filas_invalidas integer NOT NULL DEFAULT 0 CHECK (filas_invalidas >= 0),
    filas_nuevas integer NOT NULL DEFAULT 0 CHECK (filas_nuevas >= 0),
    filas_duplicadas integer NOT NULL DEFAULT 0 CHECK (filas_duplicadas >= 0),
    duplicados_omitidos jsonb NOT NULL DEFAULT '{}'::jsonb,
    estado text NOT NULL DEFAULT 'borrador' CHECK (estado IN ('borrador','procesada','conciliada','cancelada','revertida')),
    usuario_creacion_id bigint REFERENCES core.usuarios(id),
    fecha_creacion timestamptz NOT NULL DEFAULT now(),
    usuario_cancelacion_id bigint REFERENCES core.usuarios(id),
    fecha_cancelacion timestamptz,
    motivo_cancelacion text,
    usuario_finalizacion_id bigint REFERENCES core.usuarios(id),
    fecha_finalizacion timestamptz,
    saldo_calculado_final numeric(20,6),
    diferencia_final numeric(20,6),
    metadatos jsonb NOT NULL DEFAULT '{}'::jsonb,
    CONSTRAINT uq_finanzas_importaciones_empresa_hash UNIQUE (empresa_id, hash_archivo)
);

COMMENT ON TABLE public.finanzas_importaciones_bancarias IS 'Archivo bancario importado y su resultado; no sustituye movimientos ni conciliaciones.';
COMMENT ON COLUMN public.finanzas_importaciones_bancarias.hash_archivo IS 'Huella del archivo para idempotencia por empresa.';

CREATE TABLE IF NOT EXISTS public.finanzas_movimientos_bancarios (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    empresa_id bigint NOT NULL REFERENCES core.empresas(id),
    importacion_id bigint NOT NULL REFERENCES public.finanzas_importaciones_bancarias(id) ON DELETE CASCADE,
    cuenta_id bigint NOT NULL REFERENCES public.finanzas_cuentas(id),
    numero_fila integer NOT NULL CHECK (numero_fila > 0),
    fecha date NOT NULL,
    hora time,
    concepto_bancario text,
    referencia_bancaria text,
    cargo numeric(20,6) NOT NULL DEFAULT 0 CHECK (cargo >= 0),
    abono numeric(20,6) NOT NULL DEFAULT 0 CHECK (abono >= 0),
    importe numeric(20,6) NOT NULL,
    tipo text NOT NULL CHECK (tipo IN ('Deposito','Retiro')),
    saldo_posterior numeric(20,6),
    linea_original text,
    hash_movimiento text NOT NULL,
    estado_revision text NOT NULL DEFAULT 'pendiente' CHECK (estado_revision IN ('pendiente','relacionado','sin_coincidencia','excluido')),
    activo boolean NOT NULL DEFAULT true,
    fecha_creacion timestamptz NOT NULL DEFAULT now(),
    motivo_exclusion text,
    usuario_exclusion_id bigint REFERENCES core.usuarios(id),
    fecha_exclusion timestamptz,
    datos_originales jsonb NOT NULL DEFAULT '{}'::jsonb,
    metadatos jsonb NOT NULL DEFAULT '{}'::jsonb,
    saldo_disponible boolean,
    CONSTRAINT uq_finanzas_movimientos_fila UNIQUE (importacion_id, numero_fila),
    CONSTRAINT uq_finanzas_movimientos_hash UNIQUE (empresa_id, cuenta_id, hash_movimiento)
);

COMMENT ON TABLE public.finanzas_movimientos_bancarios IS 'Movimiento bancario normalizado, con datos originales para trazabilidad.';

CREATE TABLE IF NOT EXISTS public.finanzas_movimientos_bancarios_relaciones (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    empresa_id bigint NOT NULL REFERENCES core.empresas(id),
    movimiento_bancario_id bigint NOT NULL REFERENCES public.finanzas_movimientos_bancarios(id) ON DELETE CASCADE,
    operacion_id bigint NOT NULL REFERENCES public.finanzas_operaciones(id),
    estado text NOT NULL DEFAULT 'sugerida' CHECK (estado IN ('sugerida','confirmada','anulada')),
    origen text NOT NULL DEFAULT 'manual' CHECK (origen IN ('automatico','manual','importacion')),
    puntuacion numeric(8,6) CHECK (puntuacion BETWEEN 0 AND 1),
    nivel_confianza text,
    explicacion text,
    motivos jsonb NOT NULL DEFAULT '{}'::jsonb,
    usuario_confirmacion_id bigint REFERENCES core.usuarios(id),
    fecha_confirmacion timestamptz,
    activa boolean NOT NULL DEFAULT true,
    fecha_creacion timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT uq_finanzas_movimientos_relacion UNIQUE (movimiento_bancario_id, operacion_id)
);

COMMENT ON TABLE public.finanzas_movimientos_bancarios_relaciones IS 'Relación auditable entre movimiento bancario y operación financiera.';

CREATE INDEX IF NOT EXISTS ix_finanzas_importaciones_empresa_cuenta ON public.finanzas_importaciones_bancarias (empresa_id, cuenta_id, fecha_creacion);
CREATE INDEX IF NOT EXISTS ix_finanzas_movimientos_empresa_fecha ON public.finanzas_movimientos_bancarios (empresa_id, cuenta_id, fecha);
CREATE INDEX IF NOT EXISTS ix_finanzas_movimientos_estado ON public.finanzas_movimientos_bancarios (empresa_id, estado_revision);
CREATE INDEX IF NOT EXISTS ix_finanzas_relaciones_operacion ON public.finanzas_movimientos_bancarios_relaciones (empresa_id, operacion_id);
