-- Entrega operativa/logística reusable; no contamina documentos ni partidas.
CREATE TABLE IF NOT EXISTS public.operaciones_entregas (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  empresa_id integer NOT NULL REFERENCES core.empresas(id) ON DELETE RESTRICT,
  fecha date NOT NULL,
  cantidad numeric(15,6) NOT NULL,
  estado varchar(20) NOT NULL,
  full_documento_id integer REFERENCES public.documentos(id) ON DELETE RESTRICT,
  contacto_id integer REFERENCES public.contactos(id) ON DELETE RESTRICT,
  fletera_contacto_id integer REFERENCES public.contactos(id) ON DELETE RESTRICT,
  operador_id bigint REFERENCES transporte.operadores(id) ON DELETE RESTRICT,
  vehiculo_id bigint REFERENCES transporte.vehiculos(id) ON DELETE RESTRICT,
  domicilio_snapshot jsonb NOT NULL DEFAULT '{}'::jsonb,
  carta_porte_referencia text,
  observaciones text,
  datos_logisticos_snapshot jsonb NOT NULL DEFAULT '{}'::jsonb,
  usuario_creacion_id integer NOT NULL REFERENCES core.usuarios(id) ON DELETE RESTRICT,
  fecha_creacion timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT operaciones_entregas_cantidad_check CHECK (cantidad >= 0),
  CONSTRAINT operaciones_entregas_estado_check CHECK (estado IN ('programada','entregada'))
);
CREATE TABLE IF NOT EXISTS public.operaciones_entregas_partidas (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  entrega_id bigint NOT NULL REFERENCES public.operaciones_entregas(id) ON DELETE CASCADE,
  documento_id integer NOT NULL REFERENCES public.documentos(id) ON DELETE RESTRICT,
  partida_id integer NOT NULL REFERENCES public.documentos_partidas(id) ON DELETE RESTRICT,
  cantidad numeric(15,6) NOT NULL,
  CONSTRAINT operaciones_entregas_partidas_cantidad_check CHECK (cantidad > 0),
  CONSTRAINT operaciones_entregas_partidas_uq UNIQUE (entrega_id, partida_id)
);
CREATE INDEX IF NOT EXISTS idx_operaciones_entregas_empresa_estado ON public.operaciones_entregas(empresa_id,estado);
CREATE INDEX IF NOT EXISTS idx_operaciones_entregas_partidas_partida ON public.operaciones_entregas_partidas(partida_id);
COMMENT ON TABLE public.operaciones_entregas IS 'Eventos físicos de entrega; separados del documento comercial y del transporte formal.';
COMMENT ON TABLE public.operaciones_entregas_partidas IS 'Cantidades entregadas físicamente por partida comercial.';
COMMENT ON COLUMN public.operaciones_entregas.datos_logisticos_snapshot IS 'Texto histórico acotado cuando fletera/operador/vehículo no pueden normalizarse.';
