-- Precio comercial por partida. No agrega semántica DICOR ni altera importes fiscales.
CREATE TABLE IF NOT EXISTS public.documentos_partidas_condiciones_comerciales (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    empresa_id integer NOT NULL REFERENCES core.empresas(id) ON DELETE RESTRICT,
    documento_id integer NOT NULL REFERENCES public.documentos(id) ON DELETE CASCADE,
    partida_id integer NOT NULL UNIQUE REFERENCES public.documentos_partidas(id) ON DELETE CASCADE,
    precio_base_comercial numeric(15,6),
    fecha_creacion timestamptz NOT NULL DEFAULT now(),
    fecha_modificacion timestamptz,
    CONSTRAINT documentos_partidas_condiciones_base_check CHECK (precio_base_comercial IS NULL OR precio_base_comercial >= 0)
);

CREATE TABLE IF NOT EXISTS public.documentos_partidas_condiciones_comerciales_historial (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    condicion_id bigint NOT NULL REFERENCES public.documentos_partidas_condiciones_comerciales(id) ON DELETE CASCADE,
    empresa_id integer NOT NULL REFERENCES core.empresas(id) ON DELETE RESTRICT,
    documento_id integer NOT NULL REFERENCES public.documentos(id) ON DELETE CASCADE,
    partida_id integer NOT NULL REFERENCES public.documentos_partidas(id) ON DELETE CASCADE,
    precio_base_anterior numeric(15,6),
    precio_base_nuevo numeric(15,6) NOT NULL,
    motivo text,
    usuario_id integer NOT NULL REFERENCES core.usuarios(id) ON DELETE RESTRICT,
    fecha_cambio timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT documentos_partidas_condiciones_hist_base_check CHECK (precio_base_nuevo >= 0),
    CONSTRAINT documentos_partidas_condiciones_hist_motivo_check CHECK (motivo IS NULL OR btrim(motivo) <> '')
);

CREATE INDEX IF NOT EXISTS idx_documentos_partidas_condiciones_empresa_documento
  ON public.documentos_partidas_condiciones_comerciales (empresa_id, documento_id);
CREATE INDEX IF NOT EXISTS idx_documentos_partidas_condiciones_historial_partida_fecha
  ON public.documentos_partidas_condiciones_comerciales_historial (partida_id, fecha_cambio DESC, id DESC);

COMMENT ON TABLE public.documentos_partidas_condiciones_comerciales IS 'Condiciones comerciales específicas de una partida. El precio base no participa automáticamente en importes fiscales o financieros.';
COMMENT ON COLUMN public.documentos_partidas_condiciones_comerciales.precio_base_comercial IS 'Referencia interna mínima/base comercial por partida.';
COMMENT ON TABLE public.documentos_partidas_condiciones_comerciales_historial IS 'Historial append-only de cambios explícitos del precio base comercial.';
