import type { TipoDocumento } from '../../types/documentos.types';
import type {
  DocumentoField,
  DocumentoSectionKey,
  DocumentoTypeConfigMap,
  DocumentoTypeConfig,
  DocumentoTextos,
  DocumentoFieldRule,
  DocumentoSectionRule,
} from './documentoTypes';
import { DEFAULT_ESTADO_SEGUIMIENTO } from '../cotizaciones/estadoSeguimiento';

const seccionesBase: Partial<Record<DocumentoSectionKey, DocumentoSectionRule>> = {
  encabezado: { visible: true, label: 'Encabezado' },
  cliente: { visible: true, label: 'Cliente' },
  fechas: { visible: true, label: 'Fechas' },
  moneda: { visible: true, label: 'Moneda' },
  fiscal: { visible: false, label: 'Datos fiscales' },
  partidas: { visible: true, label: 'Partidas' },
  totales: { visible: true, label: 'Totales' },
  observaciones: { visible: true, label: 'Observaciones' },
  otros: { visible: false, label: 'Otros' },
};

const camposBase: Partial<Record<DocumentoField, DocumentoFieldRule>> = {
  contacto_principal_id: { required: true, section: 'cliente' },
  fecha_documento: { required: true, section: 'fechas' },
  moneda: { required: true, section: 'moneda' },
  observaciones: { required: false, section: 'observaciones' },
  partidas: { required: true, section: 'partidas' },
  subtotal: { readOnly: true, section: 'totales' },
  iva: { readOnly: true, section: 'totales' },
  total: { readOnly: true, section: 'totales' },
  usuario_creacion_id: { visible: false, section: 'otros' },
  empresa_id: { visible: false, section: 'otros' },
  tipo_cambio: { required: false, section: 'moneda', visible: false },
  serie: { visible: false, section: 'encabezado' },
  numero: { visible: false, section: 'encabezado' },
  rfc_receptor: { visible: false, section: 'fiscal' },
  nombre_receptor: { visible: false, section: 'fiscal' },
  metodo_pago: { visible: false, section: 'fiscal' },
  forma_pago: { visible: false, section: 'fiscal' },
  uso_cfdi: { visible: false, section: 'fiscal' },
  regimen_fiscal_receptor: { visible: false, section: 'fiscal' },
  lugar_expedicion: { visible: false, section: 'fiscal' },
  codigo_postal_receptor: { visible: false, section: 'fiscal' },
};

const withOverrides = <T extends object>(base: T, overrides: Partial<T> = {}): T => ({ ...base, ...overrides });

const seccionesDocumentoMonetario: Partial<Record<DocumentoSectionKey, DocumentoSectionRule>> = {
  ...seccionesBase,
  partidas: withOverrides(seccionesBase.partidas ?? { label: 'Partidas' }, { visible: false }),
  totales: withOverrides(seccionesBase.totales ?? { label: 'Totales' }, { visible: false }),
};

const camposDocumentoMonetario: Partial<Record<DocumentoField, DocumentoFieldRule>> = {
  ...camposBase,
  partidas: { ...camposBase.partidas, required: false, visible: false },
  subtotal: { ...camposBase.subtotal, readOnly: false, visible: true },
  iva: { ...camposBase.iva, readOnly: true, visible: false },
  total: { ...camposBase.total, readOnly: false, visible: true },
  forma_pago: { ...camposBase.forma_pago, visible: true, required: false, section: 'encabezado' },
  metodo_pago: { ...camposBase.metodo_pago, visible: false, required: false },
  serie: { ...camposBase.serie, visible: true, required: false },
  numero: { ...camposBase.numero, visible: true, required: false },
  moneda: { ...camposBase.moneda, required: true },
  tipo_cambio: { ...camposBase.tipo_cambio, visible: true },
};

export const DOCUMENTO_TYPE_CONFIG: DocumentoTypeConfigMap = {
  cotizacion: {
    tipo: 'cotizacion',
    label: 'Cotización',
    descripcion: 'Propuesta económica o estimado de venta.',
    textos: {
      nuevo: 'Nueva cotización',
      editar: 'Editar cotización',
      guardado: 'Cotización guardada',
      cargando: 'Cargando cotización...',
      singular: 'cotización',
    },
    features: {
      filtroAgente: true,
      mostrarSaldo: false,
      tiposContactoPermitidos: ['Cliente', 'Lead'],
      accionesDisponibles: ['duplicar', 'enviar_produccion', 'ver_produccion', 'enviar_email', 'enviar_whatsapp'],
    },
    partidas: {
      mostrarImagenes: true,
      mostrarEsParteOportunidad: true,
      mostrarMontoOportunidad: true,
    },
    widgets: {
      pagosDrawer: false,
      origenDocumento: true,
      tratamientoFiscal: false,
      fiscalTab: false,
    },
    defaults: {
      serie: null,
      estadoSeguimiento: DEFAULT_ESTADO_SEGUIMIENTO,
    },
    relatedEntities: {
      contacto: {
        creationMode: 'inline',
        captureMode: 'simple',
        defaultTipoContacto: 'Cliente',
        tiposPermitidos: ['Cliente'],
      },
      vendedor: {
        creationMode: 'disabled',
        captureMode: 'simple',
        defaultTipoVendedor: 'Vendedor',
        tiposPermitidos: ['Vendedor'],
      },
      producto: {
        creationMode: 'disabled',
        captureMode: 'simple',
        defaultTipoProducto: 'Inventariable',
        tiposPermitidos: ['Inventariable', 'No inventariable', 'Kit'],
      },
    },
    secciones: { ...seccionesBase },
    campos: {
      ...camposBase,
      serie: { ...camposBase.serie, visible: false },
      numero: { ...camposBase.numero, visible: false },
      moneda: { ...camposBase.moneda, required: true },
      tipo_cambio: { ...camposBase.tipo_cambio, visible: false },
    },
    fiscales: {
      requiereDatosFiscales: false,
      requiereMetodoPago: false,
      requiereFormaPago: false,
      requiereUsoCfdi: false,
      requiereRegimenFiscal: false,
      requiereTipoCambio: false,
    },
    estatusPermitidos: ['borrador', 'emitido', 'cancelado'],
  },
  factura: {
    tipo: 'factura',
    label: 'Factura',
    descripcion: 'Documento fiscal timbrable.',
    textos: {
      nuevo: 'Nueva factura',
      editar: 'Editar factura',
      guardado: 'Factura guardada',
      cargando: 'Cargando factura...',
      singular: 'factura',
    },
    features: {
      filtroAgente: false,
      mostrarSaldo: true,
      accionesDisponibles: ['aplicar_pago', 'timbrar', 'enviar_email', 'enviar_whatsapp'],
    },
    partidas: {
      mostrarImagenes: false,
      mostrarEsParteOportunidad: false,
      mostrarMontoOportunidad: false,
    },
    widgets: {
      pagosDrawer: true,
      origenDocumento: false,
      tratamientoFiscal: true,
      fiscalTab: true,
    },
    defaults: {
      serie: null,
      estadoSeguimiento: null,
    },
    relatedEntities: {
      contacto: {
        creationMode: 'inline',
        captureMode: 'simple',
        defaultTipoContacto: 'Lead',
        tiposPermitidos: ['Lead', 'Cliente'],
      },
      vendedor: {
        creationMode: 'disabled',
        captureMode: 'simple',
        defaultTipoVendedor: 'Vendedor',
        tiposPermitidos: ['Vendedor'],
      },
      producto: {
        creationMode: 'disabled',
        captureMode: 'simple',
        defaultTipoProducto: 'Inventariable',
        tiposPermitidos: ['Inventariable', 'No inventariable', 'Kit'],
      },
    },
    secciones: {
      ...seccionesBase,
      fiscal: withOverrides(seccionesBase.fiscal ?? { label: 'Datos fiscales' }, { visible: true }),
    },
    campos: {
      ...camposBase,
      serie: { ...camposBase.serie, visible: false, required: false },
      numero: { ...camposBase.numero, visible: false, required: false },
      rfc_receptor: { ...camposBase.rfc_receptor, visible: true, required: true },
      nombre_receptor: { ...camposBase.nombre_receptor, visible: true, required: false },
      moneda: { ...camposBase.moneda, required: true },
      tipo_cambio: { ...camposBase.tipo_cambio, visible: true },
      metodo_pago: { ...camposBase.metodo_pago, visible: true, required: true },
      forma_pago: { ...camposBase.forma_pago, visible: true, required: true },
      uso_cfdi: { ...camposBase.uso_cfdi, visible: true, required: true },
      regimen_fiscal_receptor: { ...camposBase.regimen_fiscal_receptor, visible: true, required: true },
      codigo_postal_receptor: { ...camposBase.codigo_postal_receptor, visible: true, required: true },
      lugar_expedicion: { ...camposBase.lugar_expedicion, visible: true, required: true },
    },
    fiscales: {
      requiereDatosFiscales: true,
      requiereMetodoPago: true,
      requiereFormaPago: true,
      requiereUsoCfdi: true,
      requiereRegimenFiscal: true,
      requiereTipoCambio: true,
    },
    estatusPermitidos: ['borrador', 'emitido', 'cancelado', 'timbrado'],
  },
  nota_credito: {
    tipo: 'nota_credito',
    label: 'Nota de crédito',
    descripcion: 'Documento de egreso para descuentos comerciales o devoluciones de cliente.',
    textos: {
      nuevo: 'Nueva nota de crédito',
      editar: 'Editar nota de crédito',
      guardado: 'Nota de crédito guardada',
      cargando: 'Cargando nota de crédito...',
      singular: 'nota de crédito',
    },
    features: {
      filtroAgente: false,
      mostrarSaldo: true,
      accionesDisponibles: ['timbrar'],
    },
    partidas: {
      mostrarImagenes: false,
      mostrarEsParteOportunidad: false,
      mostrarMontoOportunidad: false,
    },
    widgets: {
      pagosDrawer: false,
      origenDocumento: false,
      tratamientoFiscal: true,
      fiscalTab: true,
    },
    defaults: {
      serie: null,
      estadoSeguimiento: null,
    },
    relatedEntities: {
      contacto: {
        creationMode: 'inline',
        captureMode: 'simple',
        defaultTipoContacto: 'Cliente',
        tiposPermitidos: ['Cliente'],
      },
      vendedor: {
        creationMode: 'disabled',
        captureMode: 'simple',
        defaultTipoVendedor: 'Vendedor',
        tiposPermitidos: ['Vendedor'],
      },
      producto: {
        creationMode: 'disabled',
        captureMode: 'simple',
        defaultTipoProducto: 'Inventariable',
        tiposPermitidos: ['Inventariable', 'No inventariable', 'Kit'],
      },
    },
    secciones: {
      ...seccionesBase,
      fiscal: withOverrides(seccionesBase.fiscal ?? { label: 'Datos fiscales' }, { visible: true }),
    },
    campos: {
      ...camposBase,
      partidas: { ...camposBase.partidas, required: false },
      serie: { ...camposBase.serie, visible: false, required: false },
      numero: { ...camposBase.numero, visible: false, required: false },
      subtotal: { ...camposBase.subtotal, readOnly: false },
      iva: { ...camposBase.iva, readOnly: false },
      total: { ...camposBase.total, readOnly: true },
      rfc_receptor: { ...camposBase.rfc_receptor, visible: true, required: true },
      nombre_receptor: { ...camposBase.nombre_receptor, visible: true, required: false },
      moneda: { ...camposBase.moneda, required: true },
      tipo_cambio: { ...camposBase.tipo_cambio, visible: true },
      metodo_pago: { ...camposBase.metodo_pago, visible: true, required: true },
      forma_pago: { ...camposBase.forma_pago, visible: true, required: true },
      uso_cfdi: { ...camposBase.uso_cfdi, visible: true, required: true },
      regimen_fiscal_receptor: { ...camposBase.regimen_fiscal_receptor, visible: true, required: true },
      codigo_postal_receptor: { ...camposBase.codigo_postal_receptor, visible: true, required: true },
      lugar_expedicion: { ...camposBase.lugar_expedicion, visible: true, required: true },
    },
    fiscales: {
      requiereDatosFiscales: true,
      requiereMetodoPago: true,
      requiereFormaPago: true,
      requiereUsoCfdi: true,
      requiereRegimenFiscal: true,
      requiereTipoCambio: true,
    },
    estatusPermitidos: ['borrador', 'emitido', 'cancelado', 'timbrado'],
  },
  orden_servicio: {
    tipo: 'orden_servicio',
    label: 'Orden de servicio',
    descripcion: 'Registra los artículos recibidos y los servicios solicitados.',
    textos: {
      nuevo: 'Nueva orden de servicio',
      editar: 'Editar orden de servicio',
      guardado: 'Orden de servicio guardada',
      cargando: 'Cargando orden de servicio...',
      singular: 'orden de servicio',
    },
    features: {
      filtroAgente: false,
      mostrarSaldo: false,
      tiposContactoPermitidos: ['Cliente'],
      accionesDisponibles: ['enviar_email'],
    },
    partidas: {
      mostrarImagenes: true,
      mostrarEsParteOportunidad: false,
      mostrarMontoOportunidad: false,
    },
    widgets: {
      pagosDrawer: false,
      origenDocumento: false,
      tratamientoFiscal: false,
      fiscalTab: false,
    },
    defaults: {
      serie: null,
      estadoSeguimiento: null,
    },
    relatedEntities: {
      contacto: {
        creationMode: 'inline',
        captureMode: 'detailed',
        defaultTipoContacto: 'Cliente',
        tiposPermitidos: ['Cliente'],
      },
      vendedor: {
        creationMode: 'inline',
        captureMode: 'simple',
        defaultTipoVendedor: 'Vendedor',
        tiposPermitidos: ['Vendedor'],
      },
      producto: {
        creationMode: 'inline',
        captureMode: 'simple',
        defaultTipoProducto: 'Inventariable',
        tiposPermitidos: ['Inventariable', 'No inventariable', 'Kit'],
      },
    },
    secciones: { ...seccionesBase },
    campos: {
      ...camposBase,
      serie: { ...camposBase.serie, visible: false },
      numero: { ...camposBase.numero, visible: false },
      moneda: { ...camposBase.moneda, required: true },
      tipo_cambio: { ...camposBase.tipo_cambio, visible: false },
      observaciones: {
        ...camposBase.observaciones,
        required: false,
        helperText: 'Usa este espacio para describir el servicio solicitado o condiciones de recepción.',
      },
    },
    fiscales: {
      requiereDatosFiscales: false,
      requiereMetodoPago: false,
      requiereFormaPago: false,
      requiereUsoCfdi: false,
      requiereRegimenFiscal: false,
      requiereTipoCambio: false,
    },
    estatusPermitidos: ['borrador', 'emitido', 'cancelado'],
  },
  pedido: {
    tipo: 'pedido',
    label: 'Pedido',
    descripcion: 'Orden interna para surtir productos o servicios.',
    textos: {
      nuevo: 'Nuevo pedido',
      editar: 'Editar pedido',
      guardado: 'Pedido guardado',
      cargando: 'Cargando pedido...',
      singular: 'pedido',
    },
    features: {
      filtroAgente: false,
      mostrarSaldo: false,
      accionesDisponibles: [],
    },
    partidas: {
      mostrarImagenes: false,
      mostrarEsParteOportunidad: false,
      mostrarMontoOportunidad: false,
    },
    widgets: {
      pagosDrawer: false,
      origenDocumento: false,
      tratamientoFiscal: false,
      fiscalTab: false,
    },
    defaults: {
      serie: null,
      estadoSeguimiento: null,
    },
    relatedEntities: {
      contacto: {
        creationMode: 'inline',
        captureMode: 'simple',
        defaultTipoContacto: 'Cliente',
        tiposPermitidos: ['Cliente'],
      },
      vendedor: {
        creationMode: 'disabled',
        captureMode: 'simple',
        defaultTipoVendedor: 'Vendedor',
        tiposPermitidos: ['Vendedor'],
      },
      producto: {
        creationMode: 'disabled',
        captureMode: 'simple',
        defaultTipoProducto: 'Inventariable',
        tiposPermitidos: ['Inventariable', 'No inventariable', 'Kit'],
      },
    },
    secciones: { ...seccionesBase },
    campos: {
      ...camposBase,
      serie: { ...camposBase.serie, visible: false },
      numero: { ...camposBase.numero, visible: false },
      moneda: { ...camposBase.moneda, required: true },
      tipo_cambio: { ...camposBase.tipo_cambio, visible: false },
    },
    fiscales: {
      requiereDatosFiscales: false,
      requiereMetodoPago: false,
      requiereFormaPago: false,
      requiereUsoCfdi: false,
      requiereRegimenFiscal: false,
      requiereTipoCambio: false,
    },
    estatusPermitidos: ['borrador', 'emitido', 'cancelado'],
  },
  remision: {
    tipo: 'remision',
    label: 'Remisión',
    descripcion: 'Documento de entrega o salida de almacén.',
    textos: {
      nuevo: 'Nueva remisión',
      editar: 'Editar remisión',
      guardado: 'Remisión guardada',
      cargando: 'Cargando remisión...',
      singular: 'remisión',
    },
    features: {
      filtroAgente: false,
      mostrarSaldo: false,
      accionesDisponibles: [],
    },
    partidas: {
      mostrarImagenes: false,
      mostrarEsParteOportunidad: false,
      mostrarMontoOportunidad: false,
    },
    widgets: {
      pagosDrawer: false,
      origenDocumento: false,
      tratamientoFiscal: false,
      fiscalTab: false,
    },
    defaults: {
      serie: null,
      estadoSeguimiento: null,
    },
    relatedEntities: {
      contacto: {
        creationMode: 'inline',
        captureMode: 'simple',
        defaultTipoContacto: 'Cliente',
        tiposPermitidos: ['Cliente'],
      },
      vendedor: {
        creationMode: 'disabled',
        captureMode: 'simple',
        defaultTipoVendedor: 'Vendedor',
        tiposPermitidos: ['Vendedor'],
      },
      producto: {
        creationMode: 'disabled',
        captureMode: 'simple',
        defaultTipoProducto: 'Inventariable',
        tiposPermitidos: ['Inventariable', 'No inventariable', 'Kit'],
      },
    },
    secciones: { ...seccionesBase },
    campos: {
      ...camposBase,
      serie: { ...camposBase.serie, visible: false },
      numero: { ...camposBase.numero, visible: false },
      moneda: { ...camposBase.moneda, required: true },
      tipo_cambio: { ...camposBase.tipo_cambio, visible: false },
      observaciones: { ...camposBase.observaciones, required: false },
    },
    fiscales: {
      requiereDatosFiscales: false,
      requiereMetodoPago: false,
      requiereFormaPago: false,
      requiereUsoCfdi: false,
      requiereRegimenFiscal: false,
      requiereTipoCambio: false,
    },
    estatusPermitidos: ['borrador', 'emitido', 'cancelado'],
  },
  factura_compra: {
    tipo: 'factura_compra',
    label: 'Factura de compra',
    descripcion: 'Factura recibida de proveedor.',
    textos: {
      nuevo: 'Nueva factura de compra',
      editar: 'Editar factura de compra',
      guardado: 'Factura de compra guardada',
      cargando: 'Cargando factura de compra...',
      singular: 'factura de compra',
    },
    features: {
      filtroAgente: false,
      mostrarSaldo: true,
      accionesDisponibles: ['aplicar_pago'],
    },
    partidas: {
      mostrarImagenes: false,
      mostrarEsParteOportunidad: false,
      mostrarMontoOportunidad: false,
    },
    widgets: {
      pagosDrawer: true,
      origenDocumento: false,
      tratamientoFiscal: false,
      fiscalTab: false,
    },
    defaults: {
      serie: null,
      estadoSeguimiento: null,
    },
    relatedEntities: {
      contacto: {
        label: 'Proveedor',
        creationMode: 'inline',
        captureMode: 'simple',
        defaultTipoContacto: 'Proveedor',
        tiposPermitidos: ['Proveedor'],
      },
      vendedor: {
        visible: false,
        creationMode: 'disabled',
        captureMode: 'simple',
        defaultTipoVendedor: 'Vendedor',
        tiposPermitidos: ['Vendedor'],
      },
      producto: {
        creationMode: 'disabled',
        captureMode: 'simple',
        defaultTipoProducto: 'Inventariable',
        tiposPermitidos: ['Inventariable', 'No inventariable', 'Kit'],
      },
    },
    secciones: { ...seccionesBase },
    campos: { ...camposBase },
    fiscales: {
      requiereDatosFiscales: false,
      requiereMetodoPago: false,
      requiereFormaPago: false,
      requiereUsoCfdi: false,
      requiereRegimenFiscal: false,
      requiereTipoCambio: false,
    },
    estatusPermitidos: ['borrador', 'emitido', 'cancelado'],
  },
  nota_credito_compra: {
    tipo: 'nota_credito_compra',
    label: 'Nota de crédito de compra',
    descripcion: 'Documento de ajuste o devolución asociado a una factura de proveedor.',
    textos: {
      nuevo: 'Nueva nota de crédito de compra',
      editar: 'Editar nota de crédito de compra',
      guardado: 'Nota de crédito de compra guardada',
      cargando: 'Cargando nota de crédito de compra...',
      singular: 'nota de crédito de compra',
    },
    features: {
      filtroAgente: false,
      mostrarSaldo: true,
      accionesDisponibles: [],
    },
    partidas: {
      mostrarImagenes: false,
      mostrarEsParteOportunidad: false,
      mostrarMontoOportunidad: false,
    },
    widgets: {
      pagosDrawer: false,
      origenDocumento: false,
      tratamientoFiscal: false,
      fiscalTab: false,
    },
    defaults: {
      serie: null,
      estadoSeguimiento: null,
    },
    relatedEntities: {
      contacto: {
        label: 'Proveedor',
        creationMode: 'inline',
        captureMode: 'simple',
        defaultTipoContacto: 'Proveedor',
        tiposPermitidos: ['Proveedor'],
      },
      vendedor: {
        visible: false,
        creationMode: 'disabled',
        captureMode: 'simple',
        defaultTipoVendedor: 'Vendedor',
        tiposPermitidos: ['Vendedor'],
      },
      producto: {
        creationMode: 'disabled',
        captureMode: 'simple',
        defaultTipoProducto: 'Inventariable',
        tiposPermitidos: ['Inventariable', 'No inventariable', 'Kit'],
      },
    },
    secciones: { ...seccionesBase },
    campos: {
      ...camposBase,
      partidas: { ...camposBase.partidas, required: false },
      serie: { ...camposBase.serie, visible: false, required: false },
      numero: { ...camposBase.numero, visible: false, required: false },
      subtotal: { ...camposBase.subtotal, readOnly: false },
      iva: { ...camposBase.iva, readOnly: false },
      total: { ...camposBase.total, readOnly: true },
      moneda: { ...camposBase.moneda, required: true },
      tipo_cambio: { ...camposBase.tipo_cambio, visible: true },
    },
    fiscales: {
      requiereDatosFiscales: false,
      requiereMetodoPago: false,
      requiereFormaPago: false,
      requiereUsoCfdi: false,
      requiereRegimenFiscal: false,
      requiereTipoCambio: false,
    },
    estatusPermitidos: ['borrador', 'emitido', 'cancelado'],
  },
  pago_cliente: {
    tipo: 'pago_cliente',
    label: 'Pago de cliente',
    descripcion: 'Documento monetario simple de pago recibido.',
    modulo: 'finanzas',
    naturalezaSaldo: 'abono',
    esDocumentoMonetario: true,
    requiereCuentaFinanciera: true,
    usaPartidas: false,
    textos: {
      nuevo: 'Nuevo pago de cliente',
      editar: 'Editar pago de cliente',
      guardado: 'Pago de cliente guardado',
      cargando: 'Cargando pago de cliente...',
      singular: 'pago de cliente',
    },
    features: {
      filtroAgente: false,
      mostrarSaldo: true,
      accionesDisponibles: [],
    },
    partidas: {
      mostrarImagenes: false,
      mostrarEsParteOportunidad: false,
      mostrarMontoOportunidad: false,
    },
    widgets: {
      pagosDrawer: false,
      origenDocumento: false,
      tratamientoFiscal: false,
      fiscalTab: false,
    },
    defaults: {
      serie: null,
      estadoSeguimiento: null,
    },
    relatedEntities: {
      contacto: {
        creationMode: 'inline',
        captureMode: 'simple',
        defaultTipoContacto: 'Cliente',
        tiposPermitidos: ['Cliente'],
      },
      vendedor: {
        visible: false,
        creationMode: 'disabled',
        captureMode: 'simple',
        defaultTipoVendedor: 'Vendedor',
        tiposPermitidos: ['Vendedor'],
      },
      producto: {
        visible: false,
        creationMode: 'disabled',
        captureMode: 'simple',
        defaultTipoProducto: 'No inventariable',
        tiposPermitidos: ['No inventariable'],
      },
    },
    secciones: { ...seccionesDocumentoMonetario },
    campos: { ...camposDocumentoMonetario },
    fiscales: {
      requiereDatosFiscales: false,
      requiereMetodoPago: false,
      requiereFormaPago: false,
      requiereUsoCfdi: false,
      requiereRegimenFiscal: false,
      requiereTipoCambio: false,
    },
    estatusPermitidos: ['borrador', 'emitido', 'cancelado', 'pagado'],
  },
  pago_proveedor: {
    tipo: 'pago_proveedor',
    label: 'Pago a proveedor',
    descripcion: 'Documento monetario simple de pago emitido a proveedor.',
    modulo: 'finanzas',
    naturalezaSaldo: 'abono',
    esDocumentoMonetario: true,
    requiereCuentaFinanciera: true,
    usaPartidas: false,
    textos: {
      nuevo: 'Nuevo pago a proveedor',
      editar: 'Editar pago a proveedor',
      guardado: 'Pago a proveedor guardado',
      cargando: 'Cargando pago a proveedor...',
      singular: 'pago a proveedor',
    },
    features: {
      filtroAgente: false,
      mostrarSaldo: true,
      accionesDisponibles: [],
    },
    partidas: {
      mostrarImagenes: false,
      mostrarEsParteOportunidad: false,
      mostrarMontoOportunidad: false,
    },
    widgets: {
      pagosDrawer: false,
      origenDocumento: false,
      tratamientoFiscal: false,
      fiscalTab: false,
    },
    defaults: {
      serie: null,
      estadoSeguimiento: null,
    },
    relatedEntities: {
      contacto: {
        label: 'Proveedor',
        creationMode: 'inline',
        captureMode: 'simple',
        defaultTipoContacto: 'Proveedor',
        tiposPermitidos: ['Proveedor'],
      },
      vendedor: {
        visible: false,
        creationMode: 'disabled',
        captureMode: 'simple',
        defaultTipoVendedor: 'Vendedor',
        tiposPermitidos: ['Vendedor'],
      },
      producto: {
        visible: false,
        creationMode: 'disabled',
        captureMode: 'simple',
        defaultTipoProducto: 'No inventariable',
        tiposPermitidos: ['No inventariable'],
      },
    },
    secciones: { ...seccionesDocumentoMonetario },
    campos: { ...camposDocumentoMonetario },
    fiscales: {
      requiereDatosFiscales: false,
      requiereMetodoPago: false,
      requiereFormaPago: false,
      requiereUsoCfdi: false,
      requiereRegimenFiscal: false,
      requiereTipoCambio: false,
    },
    estatusPermitidos: ['borrador', 'emitido', 'cancelado', 'pagado'],
  },
};

export const getDocumentoTypeConfig = (tipo: TipoDocumento): DocumentoTypeConfig | undefined => {
  const normalizedTipo = String(tipo ?? '').trim().toLowerCase() as TipoDocumento;
  return DOCUMENTO_TYPE_CONFIG[normalizedTipo];
};

const TEXTOS_DEFAULT: DocumentoTextos = {
  nuevo: 'Nuevo documento',
  editar: 'Editar documento',
  guardado: 'Documento guardado',
  cargando: 'Cargando documento...',
  singular: 'documento',
};

export const resolveDocumentoTextos = (tipo: TipoDocumento, config?: DocumentoTypeConfig): DocumentoTextos => {
  const resolvedConfig = config ?? getDocumentoTypeConfig(tipo);
  if (!resolvedConfig?.textos) return TEXTOS_DEFAULT;
  return { ...TEXTOS_DEFAULT, ...resolvedConfig.textos };
};
