import * as React from 'react';
import { Alert, Box, Button, Chip, CircularProgress, Drawer, Paper, Stack, Tab, Tabs, Typography } from '@mui/material';
import RefreshRounded from '@mui/icons-material/RefreshRounded';
import VisibilityOutlined from '@mui/icons-material/VisibilityOutlined';
import { DataGrid, type GridColDef } from '@mui/x-data-grid';
import { esES } from '@mui/x-data-grid/locales';
import { LocalizationProvider, DatePicker } from '@mui/x-date-pickers';
import { AdapterDayjs } from '@mui/x-date-pickers/AdapterDayjs';
import 'dayjs/locale/es';
import dayjs from 'dayjs';
import { obtenerBloques, obtenerMetricas, type BloquePendiente, type BloqueRespondido, type VendedorMetrica } from '../services/evaluacionVendedoresService';
import { STANDARD_DATA_GRID_HEADER_HEIGHT, STANDARD_DATA_GRID_ROW_HEIGHT, standardDataGridSx } from '../components/grids/standardDataGridSx';
import { esRolAdmin } from '../session/rolScope';
import { useSession } from '../session/useSession';

const formatoTiempo = (s: number | null | undefined) => {
  if (s == null) return 'Sin datos'; if (s === 0) return '0 s';
  const n = Math.floor(s), h = Math.floor(n / 3600), m = Math.floor(n % 3600 / 60), sec = n % 60;
  return h ? `${h} h ${String(m).padStart(2, '0')} min ${String(sec).padStart(2, '0')} s` : m ? `${m} min ${String(sec).padStart(2, '0')} s` : `${sec} s`;
};
const fechaHora = (v: string) => dayjs(v).isValid() ? dayjs(v).format('DD/MM/YYYY HH:mm') : 'Sin fecha';
const periodo = (a: string, b: string) => `${dayjs(a).locale('es').format('D MMM YYYY')} – ${dayjs(b).locale('es').format('D MMM YYYY')}`;
const origen = (v: string) => v === 'manual' ? 'Manual' : v === 'plantilla_manual' ? 'Plantilla manual' : v;

function BloqueCard({ bloque, vendedor }: { bloque: BloqueRespondido | BloquePendiente; vendedor: VendedorMetrica }) {
  const respondido = 'fecha_respuesta' in bloque;
  const responsable = !respondido ? bloque.responsable_vigente_contacto_id : null;
  const responsableTexto = responsable == null ? 'Sin responsable' : responsable === vendedor.vendedor_contacto_id ? (vendedor.nombre ?? `Vendedor ID ${responsable}`) : `Vendedor ID ${responsable}`;
  return <Paper variant="outlined" sx={{ p: 2 }}><Stack spacing={1}>
    <Typography fontWeight={700}>Conversación {bloque.conversacion_id}</Typography>
    <Typography variant="body2" color="text.secondary">Contacto: {bloque.contacto_id}</Typography>
    <Typography variant="body2">Inicio: {fechaHora(bloque.fecha_inicio_bloque)}</Typography>
    {respondido ? <><Typography variant="body2">Respuesta: {fechaHora(bloque.fecha_respuesta)}</Typography><Typography variant="body2">Tiempo transcurrido: {formatoTiempo(bloque.tiempo_total_segundos)}</Typography><Typography variant="body2">Tiempo laboral: {formatoTiempo(bloque.tiempo_laboral_segundos)}</Typography><Typography variant="body2">Origen: {origen(bloque.origen_respuesta)}</Typography><Stack direction="row" gap={.75} flexWrap="wrap">{bloque.reasignado_durante_espera && <Chip size="small" label="Reasignado" variant="outlined" />}{bloque.respuesta_por_tercero && <Chip size="small" label="Respuesta por tercero" variant="outlined" />}{bloque.primera_respuesta_elegible_para_kpi && <Chip size="small" label="Primera respuesta elegible" variant="outlined" />}</Stack></> : <><Typography variant="body2">Responsable actual: {responsableTexto}</Typography><Typography variant="body2">Tiempo transcurrido: {formatoTiempo(bloque.tiempo_total_actual)}</Typography><Typography variant="body2">Tiempo laboral transcurrido: {formatoTiempo(bloque.tiempo_laboral_actual)}</Typography>{bloque.reasignado_desde_inicio && <Chip size="small" label="Reasignado desde el inicio" variant="outlined" />}</>}
  </Stack></Paper>;
}

export default function EvaluacionVendedoresPage() {
  const { session } = useSession(); const puedeAcceder = esRolAdmin(session.roles);
  const [desde, setDesde] = React.useState(dayjs().startOf('month').format('YYYY-MM-DD')); const [hasta, setHasta] = React.useState(dayjs().format('YYYY-MM-DD')); const [vendedores, setVendedores] = React.useState<VendedorMetrica[]>([]); const [loading, setLoading] = React.useState(false); const [error, setError] = React.useState<string | null>(null); const [seleccionado, setSeleccionado] = React.useState<VendedorMetrica | null>(null); const [tab, setTab] = React.useState<'respondido'|'pendiente'>('respondido'); const [bloques, setBloques] = React.useState<{respondidos: BloqueRespondido[]; pendientes: BloquePendiente[]}>({ respondidos: [], pendientes: [] }); const [loadingBloques, setLoadingBloques] = React.useState(false); const [errorBloques, setErrorBloques] = React.useState<string | null>(null); const [cargados, setCargados] = React.useState<Partial<Record<'respondido'|'pendiente', boolean>>>({});
  const cargar = React.useCallback(async () => { setLoading(true); setError(null); try { setVendedores((await obtenerMetricas(desde, hasta)).vendedores); } catch { setError('No se pudieron cargar las métricas. Intenta nuevamente.'); setVendedores([]); } finally { setLoading(false); } }, [desde, hasta]);
  React.useEffect(() => { if (puedeAcceder) void cargar(); }, [cargar, puedeAcceder]);
  const cargarBloques = React.useCallback(async (estado: 'respondido'|'pendiente') => { if (!seleccionado || cargados[estado]) return; setLoadingBloques(true); setErrorBloques(null); try { const r = await obtenerBloques(desde, hasta, seleccionado.vendedor_contacto_id, estado); setBloques(p => ({ respondidos: estado === 'respondido' ? r.bloques_respondidos : p.respondidos, pendientes: estado === 'pendiente' ? r.bloques_pendientes : p.pendientes })); setCargados(p => ({ ...p, [estado]: true })); } catch { setErrorBloques('No se pudieron cargar los bloques. Intenta nuevamente.'); } finally { setLoadingBloques(false); } }, [cargados, desde, hasta, seleccionado]);
  React.useEffect(() => { if (seleccionado) void cargarBloques(tab); }, [tab, seleccionado, cargarBloques]);
  const abrir = (v: VendedorMetrica) => { setSeleccionado(v); setTab('respondido'); setBloques({ respondidos: [], pendientes: [] }); setCargados({}); setErrorBloques(null); };
  const columnas = React.useMemo<GridColDef<VendedorMetrica>[]>(() => [{ field: 'nombre', headerName: 'Vendedor', flex: 1.5, minWidth: 180, valueGetter: (_v, r) => r.nombre ?? `Vendedor ${r.vendedor_contacto_id}` }, { field: 'conversaciones_atendidas', headerName: 'Conversaciones', minWidth: 130, flex: 1 }, { field: 'respuestas_validas_para_kpi', headerName: 'Respuestas evaluables', minWidth: 155, flex: 1 }, { field: 'tiempo_promedio_respuesta_laboral', headerName: 'Tiempo prom. respuesta', minWidth: 175, flex: 1.2, valueFormatter: v => formatoTiempo(v) }, { field: 'conversaciones_pendientes_respuesta', headerName: 'Pendientes', minWidth: 115, flex: .9 }, { field: 'detalle', headerName: 'Detalle', sortable: false, filterable: false, minWidth: 115, flex: .8, renderCell: p => <Button size="small" startIcon={<VisibilityOutlined />} onClick={(event) => { event.stopPropagation(); abrir(p.row); }}>VER</Button> }], []);
  if (!puedeAcceder) return <Alert severity="warning">No tienes permisos para consultar la evaluación de vendedores.</Alert>;
  return <Box sx={{ display: 'flex', flexDirection: 'column', gap: 2.5 }}><Stack spacing={.5}><Typography variant="h5" fontWeight={700} color="#1d2f68">Evaluación de vendedores</Typography><Typography variant="body2" color="#4b5563">Consulta métricas de atención y revisa el detalle de las conversaciones.</Typography></Stack>
    <Paper variant="outlined" sx={{ p: 2 }}><Stack direction={{ xs: 'column', sm: 'row' }} spacing={1.5} alignItems={{ sm: 'center' }}><LocalizationProvider dateAdapter={AdapterDayjs} adapterLocale="es"><DatePicker label="Desde" format="DD/MM/YYYY" value={dayjs(desde)} onChange={v => v?.isValid() && setDesde(v.format('YYYY-MM-DD'))} slotProps={{ textField: { size: 'small', fullWidth: true } }} /><DatePicker label="Hasta" format="DD/MM/YYYY" value={dayjs(hasta)} onChange={v => v?.isValid() && setHasta(v.format('YYYY-MM-DD'))} slotProps={{ textField: { size: 'small', fullWidth: true } }} /></LocalizationProvider><Button variant="contained" sx={{ flexShrink: 0, alignSelf: { xs: 'stretch', sm: 'center' } }} startIcon={loading ? <CircularProgress size={16} color="inherit" /> : <RefreshRounded />} disabled={loading} onClick={() => void cargar()}>Actualizar</Button></Stack></Paper>
    {error ? <Alert severity="error">{error}</Alert> : loading ? <Paper variant="outlined" sx={{ minHeight: 180, display: 'grid', placeItems: 'center' }}><CircularProgress /></Paper> : !vendedores.length ? <Alert severity="info">No hay métricas disponibles para el periodo seleccionado.</Alert> : <Paper variant="outlined" sx={{ overflow: 'hidden' }}><DataGrid rows={vendedores} getRowId={r => r.vendedor_contacto_id} columns={columnas} autoHeight disableRowSelectionOnClick onRowClick={p => abrir(p.row)} localeText={esES.components.MuiDataGrid.defaultProps.localeText} rowHeight={STANDARD_DATA_GRID_ROW_HEIGHT} columnHeaderHeight={STANDARD_DATA_GRID_HEADER_HEIGHT} sx={standardDataGridSx} /></Paper>}
    <Drawer anchor="right" open={Boolean(seleccionado)} onClose={() => setSeleccionado(null)} PaperProps={{ sx: { width: { xs: '100%', sm: 680, md: 740 } } }}>{seleccionado && <Box sx={{ p: 2.5, height: '100%', overflow: 'auto' }}><Typography variant="h6" fontWeight={700} color="#1d2f68">{seleccionado.nombre ?? `Vendedor ${seleccionado.vendedor_contacto_id}`}</Typography><Typography variant="body2" color="text.secondary" sx={{ mb: 2 }}>Periodo: {periodo(desde, hasta)}</Typography><Stack direction={{ xs: 'column', sm: 'row' }} spacing={1.5} sx={{ mb: 2 }}><Paper variant="outlined" sx={{ p: 1.5, flex: 1 }}><Typography variant="overline">Atención</Typography><Typography variant="body2">Conversaciones: {seleccionado.conversaciones_atendidas}</Typography><Typography variant="body2">Respuestas evaluables: {seleccionado.respuestas_validas_para_kpi}</Typography><Typography variant="body2">Pendientes: {seleccionado.conversaciones_pendientes_respuesta}</Typography><Typography variant="body2">Tiempo prom. respuesta: {formatoTiempo(seleccionado.tiempo_promedio_respuesta_laboral)}</Typography></Paper><Paper variant="outlined" sx={{ p: 1.5, flex: 1 }}><Typography variant="overline">Actividad</Typography><Typography variant="body2">Mensajes manuales: {seleccionado.mensajes_manual}</Typography><Typography variant="body2">Plantillas manuales: {seleccionado.mensajes_plantilla_manual}</Typography><Typography variant="body2">Respuestas por tercero: {seleccionado.respuestas_por_tercero}</Typography><Typography variant="body2">Primeras respuestas elegibles: {seleccionado.primeras_respuestas_elegibles}</Typography><Typography variant="body2">Tiempo prom. primera respuesta: {formatoTiempo(seleccionado.tiempo_promedio_primera_respuesta_laboral)}</Typography></Paper></Stack><Tabs value={tab} onChange={(_, v) => setTab(v)}><Tab value="respondido" label="Respondidos" /><Tab value="pendiente" label="Pendientes" /></Tabs>{errorBloques && <Alert severity="error" sx={{ my: 2 }}>{errorBloques}</Alert>}{loadingBloques ? <Box sx={{ display: 'grid', placeItems: 'center', py: 6 }}><CircularProgress /></Box> : <Stack spacing={1.5} sx={{ mt: 2 }}>{(tab === 'respondido' ? bloques.respondidos : bloques.pendientes).map(b => <BloqueCard key={`${b.conversacion_id}-${b.fecha_inicio_bloque}`} bloque={b} vendedor={seleccionado} />)}</Stack>}</Box>}</Drawer>
  </Box>;
}
