import * as React from 'react';
import { Alert, Autocomplete, Box, Button, Card, Chip, Divider, FormControl, FormControlLabel, FormLabel, Paper, Radio, RadioGroup, Stack, Switch, TextField, Typography } from '@mui/material';
import { AddRounded, EditRounded } from '@mui/icons-material';
import { apiFetch } from '../services/apiFetch';

type V = Record<string, any>;
type Contact = { id: number; nombre: string };
const empty = (): V => ({ clave_interna:'', placas:'', modelo_anio:'', remolque_predeterminado_id:null, configuracion_vehicular_sat:null, peso_bruto_vehicular:'', tipo_permiso_sict:null, numero_permiso_sict:'', propietario_contacto_id:null, aseguradora_responsabilidad_civil:'', poliza_responsabilidad_civil:'', aseguradora_medio_ambiente:'', poliza_medio_ambiente:'', aseguradora_carga:'', poliza_carga:'', activo:true });
const Input = ({ k, label, form, set }: { k:string; label:string; form:V; set:(k:string,v:any)=>void }) => <TextField size="small" fullWidth label={label} value={form[k] ?? ''} onChange={e=>set(k,e.target.value)} />;
const Section = ({ title, children }: { title:string; children:React.ReactNode }) => <Box><Typography variant="subtitle1" fontWeight={700} color="#1d2f68" mb={1}>{title}</Typography>{children}</Box>;

export default function VehiculosPage() {
  const [rows,setRows]=React.useState<V[]>([]),[form,setForm]=React.useState<V>(empty()),[edit,setEdit]=React.useState<number|null>(null),[show,setShow]=React.useState(false),[configs,setConfigs]=React.useState<V[]>([]),[permisos,setPermisos]=React.useState<V[]>([]),[remolques,setRemolques]=React.useState<V[]>([]),[contacts,setContacts]=React.useState<Contact[]>([]),[error,setError]=React.useState(''),[saving,setSaving]=React.useState(false);
  const load=React.useCallback(async()=>setRows(await apiFetch<V[]>('/api/transporte/vehiculos')),[]);
  React.useEffect(()=>{void Promise.all([load(),apiFetch<{items:V[]}>('/api/catalogos/sat/configuraciones-autotransporte?limit=50').then(x=>setConfigs(x.items)),apiFetch<{items:V[]}>('/api/catalogos/sat/tipos-permiso?limit=50').then(x=>setPermisos(x.items)),apiFetch<V[]>('/api/transporte/remolques?activo=activos').then(setRemolques),apiFetch<any>('/api/contactos?limit=100').then(x=>setContacts(Array.isArray(x)?x:x.items??x.data??[]))]).catch((e:any)=>setError(e.message));},[load]);
  const set=(k:string,v:any)=>setForm(x=>({...x,[k]:v})); const reset=()=>{setEdit(null);setForm(empty());setShow(false);};
  const start=(v:V)=>{setEdit(v.id);setForm({...v,modelo_anio:v.modelo_anio??'',peso_bruto_vehicular:v.peso_bruto_vehicular??''});setShow(true);};
  const save=async()=>{setSaving(true);setError('');try{await apiFetch(edit?'/api/transporte/vehiculos/'+edit:'/api/transporte/vehiculos',{method:edit?'PUT':'POST',body:{...form,modelo_anio:form.modelo_anio===''?null:Number(form.modelo_anio),peso_bruto_vehicular:form.peso_bruto_vehicular===''?null:Number(form.peso_bruto_vehicular),propietario_contacto_id:form.propietario_contacto_id??null}});await load();reset();}catch(e:any){setError(e.message);}finally{setSaving(false);}};
  const toggle=async(v:V)=>{try{if(v.activo)await apiFetch('/api/transporte/vehiculos/'+v.id+'/desactivar',{method:'PATCH'});else await apiFetch('/api/transporte/vehiculos/'+v.id,{method:'PUT',body:{...v,activo:true}});await load();}catch(e:any){setError(e.message);}};
  const third=form.propietario_contacto_id!=null, selected=contacts.find(c=>c.id===form.propietario_contacto_id)??null;
  return <Box sx={{maxWidth:1180,mx:'auto',p:{xs:2,md:3}}}>
    <Stack direction={{xs:'column',sm:'row'}} justifyContent="space-between" alignItems={{sm:'center'}} spacing={1.5} mb={2.5}><Box><Typography variant="h5" fontWeight={700} color="#1d2f68">Vehículos</Typography><Typography variant="body2" color="text.secondary">Administra las unidades disponibles para Transporte y Carta Porte.</Typography></Box>{!show&&<Button variant="contained" startIcon={<AddRounded/>} onClick={()=>setShow(true)}>Nuevo vehículo</Button>}</Stack>
    {error&&<Alert severity="error" sx={{mb:2}}>{error}</Alert>}
    {!show&&<Card variant="outlined" sx={{borderRadius:2}}><Box sx={{p:2}}><Typography variant="subtitle1" fontWeight={700}>Unidades registradas</Typography></Box><Divider/>{rows.length===0?<Typography color="text.secondary" sx={{p:3}}>No hay vehículos registrados.</Typography>:rows.map(v=><Box key={v.id} sx={{display:'flex',alignItems:'center',justifyContent:'space-between',gap:2,flexWrap:'wrap',px:2,py:1.5,borderBottom:'1px solid #edf0f5'}}><Box sx={{minWidth:220}}><Stack direction="row" spacing={1} alignItems="center"><Typography fontWeight={700}>{v.clave_interna}</Typography><Chip size="small" label={v.activo?'Activo':'Inactivo'} color={v.activo?'success':'default'} variant="outlined"/></Stack><Typography variant="body2" color="text.secondary">{v.placas} · {v.configuracion_vehicular_sat||'Sin configuración SAT'}</Typography></Box><Stack direction="row" spacing={1}><Button size="small" startIcon={<EditRounded/>} onClick={()=>start(v)}>Editar</Button><Button size="small" onClick={()=>void toggle(v)}>{v.activo?'Desactivar':'Activar'}</Button></Stack></Box>)}</Card>}
    {show&&<Paper variant="outlined" sx={{p:{xs:2,md:3},borderRadius:2}}><Stack direction={{xs:'column',sm:'row'}} justifyContent="space-between" alignItems={{sm:'center'}} spacing={1} mb={2.5}><Box><Typography variant="h6" fontWeight={700}>{edit?'Editar vehículo':'Nuevo vehículo'}</Typography><Typography variant="body2" color="text.secondary">Información permanente de la unidad y sus permisos.</Typography></Box><FormControlLabel control={<Switch size="small" checked={form.activo!==false} onChange={e=>set('activo',e.target.checked)}/>} label="Activo"/></Stack><Stack spacing={2.5}>
      <Section title="Identificación"><Box sx={{display:'grid',gridTemplateColumns:{xs:'1fr',sm:'1.3fr 1fr .7fr'},gap:1.5}}><Input k="clave_interna" label="Clave interna" form={form} set={set}/><Input k="placas" label="Placas" form={form} set={set}/><Input k="modelo_anio" label="Modelo/año" form={form} set={set}/></Box><Box sx={{display:'grid',gridTemplateColumns:{xs:'1fr',sm:'minmax(220px,.7fr) 1fr'},gap:1.5,mt:1.5}}><FormControl><FormLabel sx={{fontSize:13}}>Tipo de propietario</FormLabel><RadioGroup row value={third?'tercero':'propio'} onChange={e=>{if(e.target.value==='propio'){set('propietario_contacto_id',null);}}}><FormControlLabel value="propio" control={<Radio size="small"/>} label="Propio"/><FormControlLabel value="tercero" control={<Radio size="small"/>} label="Tercero"/></RadioGroup></FormControl>{third?<Autocomplete options={contacts} value={selected} getOptionLabel={x=>x.nombre} onChange={(_,v)=>set('propietario_contacto_id',v?.id??null)} renderInput={p=><TextField {...p} size="small" label="Contacto propietario"/>}/>:<Typography variant="body2" color="text.secondary" sx={{alignSelf:'center'}}>Empresa activa como propietaria</Typography>}</Box></Section>
      <Section title="Carta Porte / Autotransporte"><Box sx={{display:'grid',gridTemplateColumns:{xs:'1fr',sm:'minmax(0,2fr) minmax(180px,1fr)'},gap:1.5}}><Autocomplete options={configs} value={configs.find(x=>x.clave===form.configuracion_vehicular_sat)??null} getOptionLabel={x=>x.clave+' — '+x.descripcion} onChange={(_,v)=>set('configuracion_vehicular_sat',v?.clave??null)} renderInput={p=><TextField {...p} size="small" label="Configuración vehicular SAT"/>}/><Input k="peso_bruto_vehicular" label="Peso bruto vehicular" form={form} set={set}/></Box><Box sx={{display:'grid',gridTemplateColumns:{xs:'1fr',sm:'minmax(0,2fr) minmax(180px,1fr)'},gap:1.5,mt:1.5}}><Autocomplete options={permisos} value={permisos.find(x=>x.clave===form.tipo_permiso_sict)??null} getOptionLabel={x=>x.clave+' — '+x.descripcion} onChange={(_,v)=>set('tipo_permiso_sict',v?.clave??null)} renderInput={p=><TextField {...p} size="small" label="Tipo permiso SICT"/>}/><Input k="numero_permiso_sict" label="Número de permiso" form={form} set={set}/></Box><Box sx={{mt:1.5}}><Autocomplete options={remolques} value={remolques.find(x=>x.id===form.remolque_predeterminado_id)??null} getOptionLabel={x=>x.clave_interna+' — '+x.placas+' — '+(x.subtipo_remolque_sat||'Sin subtipo')} onChange={(_,v)=>set('remolque_predeterminado_id',v?.id??null)} renderInput={p=><TextField {...p} size='small' label='Remolque predeterminado'/>}/></Box></Section>
      <Section title="Seguros"><Box sx={{display:'grid',gridTemplateColumns:{xs:'1fr',md:'repeat(3,minmax(0,1fr))'},gap:1.5}}>{[['Responsabilidad civil','aseguradora_responsabilidad_civil','poliza_responsabilidad_civil'],['Medio ambiente','aseguradora_medio_ambiente','poliza_medio_ambiente'],['Carga','aseguradora_carga','poliza_carga']].map(([title,a,p])=><Paper key={title} variant="outlined" sx={{p:1.5,borderRadius:1.5}}><Typography variant="subtitle2" fontWeight={700} mb={1}>{title}</Typography><Stack spacing={1.2}><Input k={a} label="Aseguradora" form={form} set={set}/><Input k={p} label="Póliza" form={form} set={set}/></Stack></Paper>)}</Box></Section>
    </Stack><Stack direction="row" justifyContent="flex-end" spacing={1.25} mt={3}><Button onClick={reset}>Cancelar</Button><Button variant="contained" onClick={()=>void save()} disabled={saving}>{saving?'Guardando…':'Guardar'}</Button></Stack></Paper>}
  </Box>;
}

