BEGIN;

CREATE TABLE IF NOT EXISTS public.cfdi_intentos_timbrado (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  empresa_id integer NOT NULL REFERENCES core.empresas(id),
  documento_id integer NOT NULL REFERENCES public.documentos(id),
  proveedor varchar(50) NOT NULL,
  proveedor_cfdi_id varchar(100) NOT NULL,
  endpoint text NOT NULL,
  estado varchar(40) NOT NULL,
  uuid varchar(36),
  error_codigo varchar(100),
  error_mensaje_sanitizado text,
  intentos_descarga integer NOT NULL DEFAULT 0,
  metadata_sanitizada jsonb,
  created_at timestamptz NOT NULL DEFAULT NOW(),
  updated_at timestamptz NOT NULL DEFAULT NOW(),
  CONSTRAINT cfdi_intentos_timbrado_estado_check CHECK (
    estado IN (
      'aceptado_pendiente_descarga',
      'xml_recuperado',
      'persistido',
      'error_descarga',
      'error_validacion',
      'reconciliado'
    )
  ),
  CONSTRAINT cfdi_intentos_timbrado_proveedor_id_uk UNIQUE (proveedor, proveedor_cfdi_id)
);

CREATE INDEX IF NOT EXISTS idx_cfdi_intentos_timbrado_documento
  ON public.cfdi_intentos_timbrado (empresa_id, documento_id, created_at DESC);

CREATE UNIQUE INDEX IF NOT EXISTS ux_cfdi_intentos_timbrado_uuid
  ON public.cfdi_intentos_timbrado (uuid)
  WHERE uuid IS NOT NULL;

COMMIT;
