BEGIN;

CREATE SCHEMA IF NOT EXISTS transporte;

CREATE TABLE IF NOT EXISTS transporte.mercancias (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  empresa_id integer NOT NULL REFERENCES core.empresas(id),
  clave_interna varchar(50) NOT NULL,
  descripcion varchar(250) NOT NULL,
  clave_bienes_transportados_sat varchar(20),
  clave_unidad_sat varchar(10),
  unidad_descripcion varchar(100),
  material_peligroso boolean NOT NULL DEFAULT false,
  clave_material_peligroso varchar(20),
  embalaje varchar(20),
  descripcion_embalaje varchar(100),
  activo boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT uq_transporte_mercancias_empresa_clave UNIQUE (empresa_id, clave_interna),
  CONSTRAINT uq_transporte_mercancias_empresa_id UNIQUE (empresa_id, id),
  CONSTRAINT ck_transporte_mercancias_clave CHECK (btrim(clave_interna) <> ''),
  CONSTRAINT ck_transporte_mercancias_descripcion CHECK (btrim(descripcion) <> '')
);

CREATE TABLE IF NOT EXISTS transporte.mercancias_referencias (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  mercancia_id bigint NOT NULL REFERENCES transporte.mercancias(id) ON DELETE CASCADE,
  empresa_fuente_id integer NOT NULL REFERENCES core.empresas(id),
  tipo_entidad_fuente varchar(50) NOT NULL,
  entidad_fuente_id bigint NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT uq_transporte_mercancias_referencias_fuente
    UNIQUE (mercancia_id, empresa_fuente_id, tipo_entidad_fuente, entidad_fuente_id),
  CONSTRAINT ck_transporte_mercancias_referencias_tipo
    CHECK (btrim(tipo_entidad_fuente) <> '')
);

CREATE TABLE IF NOT EXISTS transporte.ubicaciones (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  empresa_id integer NOT NULL REFERENCES core.empresas(id),
  nombre varchar(150) NOT NULL,
  tipo_referencia varchar(50),
  contacto_id integer REFERENCES public.contactos(id),
  empresa_contraparte_id integer REFERENCES core.empresas(id),
  calle varchar(150),
  numero_exterior varchar(30),
  numero_interior varchar(30),
  colonia varchar(150),
  localidad varchar(150),
  municipio varchar(150),
  estado varchar(100),
  pais varchar(100),
  codigo_postal varchar(10),
  referencia text,
  latitud numeric(10,7),
  longitud numeric(10,7),
  activo boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT uq_transporte_ubicaciones_empresa_id UNIQUE (empresa_id, id),
  CONSTRAINT ck_transporte_ubicaciones_nombre CHECK (btrim(nombre) <> ''),
  CONSTRAINT ck_transporte_ubicaciones_latitud
    CHECK (latitud IS NULL OR latitud BETWEEN -90 AND 90),
  CONSTRAINT ck_transporte_ubicaciones_longitud
    CHECK (longitud IS NULL OR longitud BETWEEN -180 AND 180)
);

CREATE TABLE IF NOT EXISTS transporte.vehiculos (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  empresa_id integer NOT NULL REFERENCES core.empresas(id),
  clave_interna varchar(50) NOT NULL,
  placas varchar(20) NOT NULL,
  configuracion_vehicular_sat varchar(20),
  peso_bruto_vehicular numeric(14,3),
  tipo_permiso_sict varchar(20),
  numero_permiso_sict varchar(50),
  aseguradora_responsabilidad_civil varchar(200),
  poliza_responsabilidad_civil varchar(100),
  aseguradora_medio_ambiente varchar(200),
  poliza_medio_ambiente varchar(100),
  aseguradora_carga varchar(200),
  poliza_carga varchar(100),
  modelo_anio smallint,
  propietario_contacto_id integer REFERENCES public.contactos(id),
  activo boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT uq_transporte_vehiculos_empresa_clave UNIQUE (empresa_id, clave_interna),
  CONSTRAINT uq_transporte_vehiculos_empresa_placas UNIQUE (empresa_id, placas),
  CONSTRAINT uq_transporte_vehiculos_empresa_id UNIQUE (empresa_id, id),
  CONSTRAINT ck_transporte_vehiculos_clave CHECK (btrim(clave_interna) <> ''),
  CONSTRAINT ck_transporte_vehiculos_placas CHECK (btrim(placas) <> ''),
  CONSTRAINT ck_transporte_vehiculos_peso
    CHECK (peso_bruto_vehicular IS NULL OR peso_bruto_vehicular > 0),
  CONSTRAINT ck_transporte_vehiculos_modelo
    CHECK (modelo_anio IS NULL OR modelo_anio BETWEEN 1900 AND 2200)
);

CREATE TABLE IF NOT EXISTS transporte.remolques (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  empresa_id integer NOT NULL REFERENCES core.empresas(id),
  clave_interna varchar(50) NOT NULL,
  subtipo_remolque_sat varchar(20),
  placas varchar(20) NOT NULL,
  propietario_contacto_id integer REFERENCES public.contactos(id),
  activo boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT uq_transporte_remolques_empresa_clave UNIQUE (empresa_id, clave_interna),
  CONSTRAINT uq_transporte_remolques_empresa_placas UNIQUE (empresa_id, placas),
  CONSTRAINT uq_transporte_remolques_empresa_id UNIQUE (empresa_id, id),
  CONSTRAINT ck_transporte_remolques_clave CHECK (btrim(clave_interna) <> ''),
  CONSTRAINT ck_transporte_remolques_placas CHECK (btrim(placas) <> '')
);

CREATE TABLE IF NOT EXISTS transporte.operadores (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  empresa_id integer NOT NULL REFERENCES core.empresas(id),
  contacto_id integer NOT NULL REFERENCES public.contactos(id),
  numero_licencia varchar(50) NOT NULL,
  tipo_licencia varchar(30),
  vigencia_licencia date,
  activo boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT uq_transporte_operadores_empresa_contacto UNIQUE (empresa_id, contacto_id),
  CONSTRAINT uq_transporte_operadores_empresa_id UNIQUE (empresa_id, id),
  CONSTRAINT ck_transporte_operadores_licencia CHECK (btrim(numero_licencia) <> '')
);

CREATE TABLE IF NOT EXISTS transporte.viajes (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  empresa_id integer NOT NULL REFERENCES core.empresas(id),
  folio_interno varchar(50) NOT NULL,
  cliente_contacto_id integer NOT NULL REFERENCES public.contactos(id),
  estatus varchar(30) NOT NULL DEFAULT 'borrador',
  fecha_programada timestamptz,
  fecha_inicio timestamptz,
  fecha_fin timestamptz,
  vehiculo_id bigint,
  referencia_cliente varchar(100),
  observaciones text,
  creado_por integer NOT NULL REFERENCES core.usuarios(id),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT uq_transporte_viajes_empresa_folio UNIQUE (empresa_id, folio_interno),
  CONSTRAINT uq_transporte_viajes_empresa_id UNIQUE (empresa_id, id),
  CONSTRAINT fk_transporte_viajes_vehiculo
    FOREIGN KEY (empresa_id, vehiculo_id)
    REFERENCES transporte.vehiculos(empresa_id, id),
  CONSTRAINT ck_transporte_viajes_folio CHECK (btrim(folio_interno) <> ''),
  CONSTRAINT ck_transporte_viajes_estatus CHECK (
    estatus IN ('borrador', 'listo_para_validar', 'validado', 'timbrado', 'cancelado')
  ),
  CONSTRAINT ck_transporte_viajes_fechas CHECK (
    fecha_inicio IS NULL OR fecha_fin IS NULL OR fecha_fin >= fecha_inicio
  )
);

CREATE TABLE IF NOT EXISTS transporte.viaje_ubicaciones (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  empresa_id integer NOT NULL,
  viaje_id bigint NOT NULL,
  ubicacion_id bigint,
  tipo varchar(20) NOT NULL,
  secuencia integer NOT NULL,
  remitente_destinatario_nombre varchar(200) NOT NULL,
  remitente_destinatario_rfc varchar(13),
  fecha_hora_programada timestamptz NOT NULL,
  fecha_hora_real timestamptz,
  distancia_recorrida numeric(14,3),
  domicilio_snapshot jsonb NOT NULL,
  coordenadas_snapshot jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT uq_transporte_viaje_ubicaciones_secuencia UNIQUE (viaje_id, secuencia),
  CONSTRAINT uq_transporte_viaje_ubicaciones_viaje_id UNIQUE (viaje_id, id),
  CONSTRAINT uq_transporte_viaje_ubicaciones_empresa_viaje_id UNIQUE (empresa_id, viaje_id, id),
  CONSTRAINT fk_transporte_viaje_ubicaciones_viaje
    FOREIGN KEY (empresa_id, viaje_id)
    REFERENCES transporte.viajes(empresa_id, id) ON DELETE CASCADE,
  CONSTRAINT fk_transporte_viaje_ubicaciones_ubicacion
    FOREIGN KEY (empresa_id, ubicacion_id)
    REFERENCES transporte.ubicaciones(empresa_id, id),
  CONSTRAINT ck_transporte_viaje_ubicaciones_tipo CHECK (tipo IN ('origen', 'destino')),
  CONSTRAINT ck_transporte_viaje_ubicaciones_secuencia CHECK (secuencia > 0),
  CONSTRAINT ck_transporte_viaje_ubicaciones_nombre
    CHECK (btrim(remitente_destinatario_nombre) <> ''),
  CONSTRAINT ck_transporte_viaje_ubicaciones_distancia
    CHECK (distancia_recorrida IS NULL OR distancia_recorrida >= 0),
  CONSTRAINT ck_transporte_viaje_ubicaciones_domicilio
    CHECK (jsonb_typeof(domicilio_snapshot) = 'object'),
  CONSTRAINT ck_transporte_viaje_ubicaciones_coordenadas
    CHECK (coordenadas_snapshot IS NULL OR jsonb_typeof(coordenadas_snapshot) = 'object')
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_transporte_viaje_ubicaciones_origen
  ON transporte.viaje_ubicaciones (viaje_id)
  WHERE tipo = 'origen';

CREATE TABLE IF NOT EXISTS transporte.viaje_mercancias (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  empresa_id integer NOT NULL,
  viaje_id bigint NOT NULL,
  mercancia_id bigint,
  descripcion_snapshot varchar(250) NOT NULL,
  clave_bienes_transportados_sat varchar(20),
  clave_unidad_sat varchar(10),
  unidad_descripcion varchar(100),
  cantidad numeric(18,6) NOT NULL,
  peso_kg numeric(18,3) NOT NULL,
  valor_mercancia numeric(18,2),
  material_peligroso boolean NOT NULL DEFAULT false,
  clave_material_peligroso varchar(20),
  embalaje varchar(20),
  descripcion_embalaje varchar(100),
  origen_viaje_ubicacion_id bigint,
  destino_viaje_ubicacion_id bigint,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT fk_transporte_viaje_mercancias_viaje
    FOREIGN KEY (empresa_id, viaje_id)
    REFERENCES transporte.viajes(empresa_id, id) ON DELETE CASCADE,
  CONSTRAINT fk_transporte_viaje_mercancias_mercancia
    FOREIGN KEY (empresa_id, mercancia_id)
    REFERENCES transporte.mercancias(empresa_id, id),
  CONSTRAINT fk_transporte_viaje_mercancias_origen
    FOREIGN KEY (empresa_id, viaje_id, origen_viaje_ubicacion_id)
    REFERENCES transporte.viaje_ubicaciones(empresa_id, viaje_id, id),
  CONSTRAINT fk_transporte_viaje_mercancias_destino
    FOREIGN KEY (empresa_id, viaje_id, destino_viaje_ubicacion_id)
    REFERENCES transporte.viaje_ubicaciones(empresa_id, viaje_id, id),
  CONSTRAINT ck_transporte_viaje_mercancias_descripcion
    CHECK (btrim(descripcion_snapshot) <> ''),
  CONSTRAINT ck_transporte_viaje_mercancias_cantidad CHECK (cantidad > 0),
  CONSTRAINT ck_transporte_viaje_mercancias_peso CHECK (peso_kg > 0),
  CONSTRAINT ck_transporte_viaje_mercancias_valor
    CHECK (valor_mercancia IS NULL OR valor_mercancia >= 0)
);

CREATE TABLE IF NOT EXISTS transporte.viaje_figuras (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  empresa_id integer NOT NULL,
  viaje_id bigint NOT NULL,
  tipo_figura varchar(30) NOT NULL DEFAULT 'operador',
  operador_id bigint,
  contacto_id integer REFERENCES public.contactos(id),
  secuencia integer NOT NULL,
  datos_snapshot jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT uq_transporte_viaje_figuras_secuencia UNIQUE (viaje_id, tipo_figura, secuencia),
  CONSTRAINT fk_transporte_viaje_figuras_viaje
    FOREIGN KEY (empresa_id, viaje_id)
    REFERENCES transporte.viajes(empresa_id, id) ON DELETE CASCADE,
  CONSTRAINT fk_transporte_viaje_figuras_operador
    FOREIGN KEY (empresa_id, operador_id)
    REFERENCES transporte.operadores(empresa_id, id),
  CONSTRAINT ck_transporte_viaje_figuras_secuencia CHECK (secuencia > 0),
  CONSTRAINT ck_transporte_viaje_figuras_snapshot
    CHECK (jsonb_typeof(datos_snapshot) = 'object')
);

CREATE TABLE IF NOT EXISTS transporte.viaje_remolques (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  empresa_id integer NOT NULL,
  viaje_id bigint NOT NULL,
  remolque_id bigint NOT NULL,
  orden integer NOT NULL,
  datos_snapshot jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT uq_transporte_viaje_remolques_remolque UNIQUE (viaje_id, remolque_id),
  CONSTRAINT uq_transporte_viaje_remolques_orden UNIQUE (viaje_id, orden),
  CONSTRAINT fk_transporte_viaje_remolques_viaje
    FOREIGN KEY (empresa_id, viaje_id)
    REFERENCES transporte.viajes(empresa_id, id) ON DELETE CASCADE,
  CONSTRAINT fk_transporte_viaje_remolques_remolque
    FOREIGN KEY (empresa_id, remolque_id)
    REFERENCES transporte.remolques(empresa_id, id),
  CONSTRAINT ck_transporte_viaje_remolques_orden CHECK (orden > 0),
  CONSTRAINT ck_transporte_viaje_remolques_snapshot
    CHECK (jsonb_typeof(datos_snapshot) = 'object')
);

CREATE TABLE IF NOT EXISTS transporte.viaje_documentos (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  empresa_id integer NOT NULL,
  viaje_id bigint NOT NULL,
  documento_id integer NOT NULL REFERENCES public.documentos(id),
  tipo_relacion varchar(30) NOT NULL DEFAULT 'factura_servicio',
  principal boolean NOT NULL DEFAULT false,
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT uq_transporte_viaje_documentos_relacion
    UNIQUE (viaje_id, documento_id, tipo_relacion),
  CONSTRAINT fk_transporte_viaje_documentos_viaje
    FOREIGN KEY (empresa_id, viaje_id)
    REFERENCES transporte.viajes(empresa_id, id) ON DELETE CASCADE,
  CONSTRAINT ck_transporte_viaje_documentos_tipo
    CHECK (tipo_relacion = 'factura_servicio')
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_transporte_viaje_documentos_principal
  ON transporte.viaje_documentos (viaje_id, tipo_relacion)
  WHERE principal = true;

CREATE TABLE IF NOT EXISTS transporte.cartas_porte (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  empresa_id integer NOT NULL REFERENCES core.empresas(id),
  viaje_id bigint NOT NULL,
  documento_id integer NOT NULL REFERENCES public.documentos(id),
  version varchar(10) NOT NULL DEFAULT '3.1',
  id_ccp varchar(36),
  estatus varchar(30) NOT NULL DEFAULT 'borrador',
  snapshot_json jsonb NOT NULL,
  validado_at timestamptz,
  timbrado_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT uq_transporte_cartas_porte_viaje_documento UNIQUE (viaje_id, documento_id),
  CONSTRAINT fk_transporte_cartas_porte_viaje
    FOREIGN KEY (empresa_id, viaje_id)
    REFERENCES transporte.viajes(empresa_id, id),
  CONSTRAINT ck_transporte_cartas_porte_version CHECK (version = '3.1'),
  CONSTRAINT ck_transporte_cartas_porte_snapshot
    CHECK (jsonb_typeof(snapshot_json) = 'object')
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_transporte_cartas_porte_id_ccp
  ON transporte.cartas_porte (id_ccp)
  WHERE id_ccp IS NOT NULL;

CREATE INDEX IF NOT EXISTS ix_transporte_mercancias_empresa_activo
  ON transporte.mercancias (empresa_id, activo);
CREATE INDEX IF NOT EXISTS ix_transporte_mercancias_referencias_fuente
  ON transporte.mercancias_referencias (empresa_fuente_id, tipo_entidad_fuente, entidad_fuente_id);
CREATE INDEX IF NOT EXISTS ix_transporte_ubicaciones_empresa_activo
  ON transporte.ubicaciones (empresa_id, activo);
CREATE INDEX IF NOT EXISTS ix_transporte_ubicaciones_contacto
  ON transporte.ubicaciones (contacto_id) WHERE contacto_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS ix_transporte_vehiculos_empresa_activo
  ON transporte.vehiculos (empresa_id, activo);
CREATE INDEX IF NOT EXISTS ix_transporte_remolques_empresa_activo
  ON transporte.remolques (empresa_id, activo);
CREATE INDEX IF NOT EXISTS ix_transporte_operadores_empresa_activo
  ON transporte.operadores (empresa_id, activo);
CREATE INDEX IF NOT EXISTS ix_transporte_viajes_empresa_estatus
  ON transporte.viajes (empresa_id, estatus, fecha_programada);
CREATE INDEX IF NOT EXISTS ix_transporte_viaje_ubicaciones_ubicacion
  ON transporte.viaje_ubicaciones (empresa_id, ubicacion_id)
  WHERE ubicacion_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS ix_transporte_viaje_mercancias_viaje
  ON transporte.viaje_mercancias (viaje_id);
CREATE INDEX IF NOT EXISTS ix_transporte_viaje_figuras_operador
  ON transporte.viaje_figuras (empresa_id, operador_id)
  WHERE operador_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS ix_transporte_viaje_documentos_documento
  ON transporte.viaje_documentos (documento_id);
CREATE INDEX IF NOT EXISTS ix_transporte_cartas_porte_documento
  ON transporte.cartas_porte (documento_id);
CREATE INDEX IF NOT EXISTS ix_transporte_cartas_porte_empresa_estatus
  ON transporte.cartas_porte (empresa_id, estatus);

COMMENT ON SCHEMA transporte IS 'Operación logística y materialización fiscal de servicios de transporte.';
COMMENT ON TABLE transporte.mercancias IS 'Catálogo logístico de mercancías; no contiene precios, impuestos ni inventario.';
COMMENT ON TABLE transporte.mercancias_referencias IS 'Referencias informativas a entidades fuente, sin dependencia fiscal en tiempo real.';
COMMENT ON TABLE transporte.viaje_ubicaciones IS 'Paradas de un viaje con snapshot histórico del domicilio utilizado.';
COMMENT ON TABLE transporte.viaje_mercancias IS 'Mercancías transportadas con datos fiscales y operativos congelados por viaje.';
COMMENT ON TABLE transporte.cartas_porte IS 'Materialización fiscal inmutable preparada para Carta Porte; el XML timbrado permanece en public.documentos_cfdi.';
COMMENT ON COLUMN transporte.cartas_porte.snapshot_json IS 'Objeto fiscal exacto que posteriormente se enviará como complemento a Facturama.';

COMMIT;
