import React from 'react';
import { Alert, Autocomplete, Box, Button, Card, CardContent, CircularProgress, MenuItem, Stack, TextField, Typography } from '@mui/material';
import DeleteOutlineIcon from '@mui/icons-material/DeleteOutline';
import { apiFetch } from '../../services/apiFetch';
import { useSession } from '../../session/useSession';
import { esRolAdmin } from '../../session/rolScope';

type Horario = { id?: number; dia_semana: number; hora_inicio: string; hora_fin: string; activo: boolean };
type Excepcion = { id: number; fecha: string; tipo: 'inhabil'|'horario_especial'; descripcion?: string|null; hora_inicio?: string|null; hora_fin?: string|null };
const dias = ['Domingo','Lunes','Martes','Miércoles','Jueves','Viernes','Sábado'];
const FALLBACK_ZONAS_IANA = [
 'America/Mexico_City','America/Cancun','America/Chihuahua','America/Hermosillo','America/Matamoros','America/Mazatlan','America/Monterrey','America/Ojinaga','America/Tijuana',
 'UTC','America/New_York','America/Chicago','America/Denver','America/Los_Angeles','America/Toronto','America/Vancouver','America/Sao_Paulo','America/Argentina/Buenos_Aires',
 'Europe/London','Europe/Madrid','Europe/Paris','Europe/Berlin','Europe/Rome','Africa/Cairo','Asia/Dubai','Asia/Kolkata','Asia/Shanghai','Asia/Tokyo','Asia/Seoul','Australia/Sydney',
];
function obtenerZonasIana(): string[] {
 const supportedValuesOf = (Intl as typeof Intl & { supportedValuesOf?: (key: string) => string[] }).supportedValuesOf;
 if (typeof supportedValuesOf === 'function') {
   try { return supportedValuesOf('timeZone').filter(Boolean).sort(); } catch { /* usa fallback explícito */ }
 }
 return FALLBACK_ZONAS_IANA;
}
const ZONAS_IANA = obtenerZonasIana();
const normalizarBusqueda = (value: string) => value.normalize('NFD').replace(/[\u0300-\u036f]/g, '').toLowerCase();
const NOMBRES_AMIGABLES_MEXICO: Record<string, string> = {
 'America/Mexico_City':'Ciudad de México','America/Cancun':'Cancún','America/Chihuahua':'Chihuahua','America/Ciudad_Juarez':'Ciudad Juárez','America/Hermosillo':'Hermosillo','America/Matamoros':'Matamoros','America/Mazatlan':'Mazatlán','America/Merida':'Mérida','America/Monterrey':'Monterrey','America/Ojinaga':'Ojinaga','America/Tijuana':'Tijuana','America/Bahia_Banderas':'Bahía de Banderas',
};
type ZonaOption = { value: string; label: string };
const transformarZona = (value: string): ZonaOption => ({ value, label: NOMBRES_AMIGABLES_MEXICO[value] ?? value });
const OPCIONES_ZONA = ZONAS_IANA.map(transformarZona);
const normalizarHora = (value: string | null | undefined, fallback: string) => /^([01]\d|2[0-3]):[0-5]\d/.test(value ?? '') ? (value as string).slice(0, 5) : fallback;
const blank = (dia: number): Horario => ({ dia_semana: dia, hora_inicio: '09:00', hora_fin: '18:00', activo: false });
export default function HorariosLaboralesPage() {
 const { session } = useSession(); const editable = Boolean(session.user?.es_superadmin) || esRolAdmin(session.roles);
 const [zona,setZona]=React.useState(''); const [horarios,setHorarios]=React.useState<Horario[]>(dias.map((_,i)=>blank(i))); const [excepciones,setExcepciones]=React.useState<Excepcion[]>([]); const [form,setForm]=React.useState({fecha:'',tipo:'inhabil',descripcion:'',hora_inicio:'09:00',hora_fin:'13:00'}); const [editingId,setEditingId]=React.useState<number|null>(null); const [deleteId,setDeleteId]=React.useState<number|null>(null); const [busy,setBusy]=React.useState(true); const [message,setMessage]=React.useState<{type:'success'|'error',text:string}|null>(null);
 const opcionesZona = React.useMemo(() => { const current = zona && !OPCIONES_ZONA.some(option => option.value === zona) ? [transformarZona(zona)] : []; return [...OPCIONES_ZONA, ...current]; }, [zona]);
 const load=React.useCallback(async()=>{setBusy(true);try{const d=await apiFetch<any>('/api/configuracion/horarios-laborales');setZona(d.zona_horaria??'');setExcepciones(d.excepciones);setHorarios(dias.map((_,i)=>{const h=d.horarios.find((item:Horario)=>item.dia_semana===i);return h?{...h,hora_inicio:normalizarHora(h.hora_inicio,'09:00'),hora_fin:normalizarHora(h.hora_fin,'18:00')}:blank(i);}));}catch(e:any){setMessage({type:'error',text:e.message});}finally{setBusy(false);}},[]);
 React.useEffect(()=>{void load()},[load,session.empresaActivaId]);
 const save=async()=>{setMessage(null);try{await apiFetch('/api/configuracion/horarios-laborales/zona-horaria',{method:'PUT',body:{zona_horaria:zona||null}});const payload=horarios.map(h=>({...h,hora_inicio:normalizarHora(h.hora_inicio,'09:00'),hora_fin:normalizarHora(h.hora_fin,'18:00')}));await apiFetch('/api/configuracion/horarios-laborales/horarios',{method:'PUT',body:{horarios:payload}});setMessage({type:'success',text:'Configuración guardada.'});await load();}catch(e:any){setMessage({type:'error',text:e.message});}};
 const add=async()=>{try{const path=editingId?`/api/configuracion/horarios-laborales/excepciones/${editingId}`:'/api/configuracion/horarios-laborales/excepciones';const d=await apiFetch<Excepcion>(path,{method:editingId?'PUT':'POST',body:{...form,hora_inicio:form.tipo==='inhabil'?null:form.hora_inicio,hora_fin:form.tipo==='inhabil'?null:form.hora_fin}});setExcepciones(x=>[d,...x.filter(i=>i.id!==d.id&&i.fecha!==d.fecha)]);setForm({...form,fecha:'',descripcion:''});setEditingId(null);setMessage({type:'success',text:editingId?'Excepción actualizada.':'Excepción creada.'});}catch(e:any){setMessage({type:'error',text:e.message});}};
 const startEdit=(e:Excepcion)=>{setEditingId(e.id);setForm({fecha:e.fecha.slice(0,10),tipo:e.tipo,descripcion:e.descripcion??'',hora_inicio:e.hora_inicio??'09:00',hora_fin:e.hora_fin??'13:00'});};
 const remove=async(id:number)=>{try{await apiFetch(`/api/configuracion/horarios-laborales/excepciones/${id}`,{method:'DELETE'});setExcepciones(x=>x.filter(i=>i.id!==id));setDeleteId(null);setMessage({type:'success',text:'Excepción eliminada.'});}catch(e:any){setMessage({type:'error',text:e.message});}};
 if (busy) return <CircularProgress/>;
 return <Box sx={{maxWidth:1000}}><Stack spacing={2}><Typography variant="h5" fontWeight={700} color="#1d2f68">Horarios laborales</Typography><Typography color="text.secondary">Empresa activa: {session.empresas.find(e=>e.id===session.empresaActivaId)?.nombre??'sin seleccionar'}. Si no configuras horarios, las futuras métricas usarán tiempo natural.</Typography>{!editable&&<Alert severity="info">Sólo administradores y superadministradores pueden modificar esta configuración.</Alert>}{message&&<Alert severity={message.type}>{message.text}</Alert>}
 <Card><CardContent><Stack spacing={2}><Autocomplete options={opcionesZona} value={opcionesZona.find(option=>option.value===zona)||null} onChange={(_,value)=>setZona(value?.value??'')} getOptionLabel={option=>option.label} isOptionEqualToValue={(option,value)=>option.value===value.value} filterOptions={(options,{inputValue})=>{const query=normalizarBusqueda(inputValue);return options.filter(option=>normalizarBusqueda(`${option.label} ${option.value}`).includes(query));}} renderOption={(props,option)=><li {...props} key={option.value}><Stack spacing={0.25}><Typography>{option.label}</Typography><Typography variant="caption" color="text.secondary">{option.value}</Typography></Stack></li>} disabled={!editable} renderInput={(params)=><TextField {...params} label="Zona horaria" placeholder="Busca por nombre o identificador IANA" helperText="Selecciona una zona de la lista; por ejemplo, Ciudad de México."/>}/><Typography variant="h6">Días laborables</Typography>{horarios.map((h,i)=><Stack key={i} direction={{xs:'column',sm:'row'}} spacing={1} alignItems={{sm:'center'}}><TextField select label={dias[i]} value={h.activo?'activo':'inhabilitado'} onChange={e=>setHorarios(x=>x.map((v,j)=>j===i?{...v,activo:e.target.value==='activo'}:v))} disabled={!editable} sx={{minWidth:160}}><MenuItem value="activo">Activo</MenuItem><MenuItem value="inhabilitado">No laborable</MenuItem></TextField><TextField type="time" label="Inicio" value={h.hora_inicio} onChange={e=>setHorarios(x=>x.map((v,j)=>j===i?{...v,hora_inicio:e.target.value}:v))} disabled={!editable||!h.activo}/><TextField type="time" label="Fin" value={h.hora_fin} onChange={e=>setHorarios(x=>x.map((v,j)=>j===i?{...v,hora_fin:e.target.value}:v))} disabled={!editable||!h.activo}/></Stack>)}<Button variant="contained" onClick={save} disabled={!editable||Boolean(zona&&!ZONAS_IANA.includes(zona))}>Guardar configuración</Button></Stack></CardContent></Card>
 <Card><CardContent><Stack spacing={2}><Typography variant="h6">Excepciones</Typography><Stack direction={{xs:'column',sm:'row'}} spacing={1}><TextField type="date" label="Fecha" InputLabelProps={{shrink:true}} value={form.fecha} onChange={e=>setForm({...form,fecha:e.target.value})} disabled={!editable}/><TextField select label="Tipo" value={form.tipo} onChange={e=>setForm({...form,tipo:e.target.value})} disabled={!editable}><MenuItem value="inhabil">Día no laborable</MenuItem><MenuItem value="horario_especial">Horario especial</MenuItem></TextField><TextField label="Descripción" value={form.descripcion} onChange={e=>setForm({...form,descripcion:e.target.value})} disabled={!editable}/></Stack>{form.tipo==='horario_especial'&&<Stack direction="row" spacing={1}><TextField type="time" label="Inicio" value={form.hora_inicio} onChange={e=>setForm({...form,hora_inicio:e.target.value})}/><TextField type="time" label="Fin" value={form.hora_fin} onChange={e=>setForm({...form,hora_fin:e.target.value})}/></Stack>}<Button variant="outlined" onClick={add} disabled={!editable||!form.fecha}>{editingId?'Actualizar excepción':'Agregar excepción'}</Button>{excepciones.map(e=><Stack key={e.id} spacing={1}><Stack direction={{xs:'column',sm:'row'}} justifyContent="space-between" alignItems={{sm:'center'}}><Typography>{e.fecha} · {e.tipo==='inhabil'?'No laborable':`${e.hora_inicio}–${e.hora_fin}`} {e.descripcion||''}</Typography><Stack direction="row"><Button onClick={()=>startEdit(e)} disabled={!editable}>Editar</Button><Button color="error" startIcon={<DeleteOutlineIcon/>} onClick={()=>setDeleteId(e.id)} disabled={!editable}>Eliminar</Button></Stack></Stack>{deleteId===e.id&&<Alert severity="warning" action={<><Button color="inherit" size="small" onClick={()=>remove(e.id)}>Confirmar</Button><Button color="inherit" size="small" onClick={()=>setDeleteId(null)}>Cancelar</Button></>}>¿Eliminar esta excepción?</Alert>}</Stack>)}</Stack></CardContent></Card></Stack></Box>;
}
