import * as React from 'react';
import { Alert, Autocomplete, Box, Button, Dialog, DialogActions, DialogContent, DialogTitle, IconButton, Paper, Stack, Switch, Table, TableBody, TableCell, TableHead, TableRow, TextField, Typography } from '@mui/material';
import { Add, Delete, Edit } from '@mui/icons-material';
import { apiFetch } from '../../services/apiFetch';
import { actualizarUnidad, crearUnidad, eliminarUnidad, fetchUnidades, type Unidad } from '../../services/unidadesService';

type Sat = { id: number; clave: string; descripcion: string };
const empty = { clave: '', descripcion: '', unidad_sat_id: 0, activo: true };

export default function UnidadesPage() {
  const [rows, setRows] = React.useState<Unidad[]>([]); const [editing, setEditing] = React.useState<Unidad | null>(null); const [form, setForm] = React.useState(empty); const [sat, setSat] = React.useState<Sat[]>([]); const [open, setOpen] = React.useState(false); const [error, setError] = React.useState('');
  const load = React.useCallback(async () => setRows(await fetchUnidades(true)), []); React.useEffect(() => { void load(); }, [load]);
  const searchSat = async (q: string) => { try { const r = await apiFetch<{ items: Sat[] }>(`/api/catalogos/sat/unidades?q=${encodeURIComponent(q)}&limit=50`); setSat(r.items ?? []); } catch { setSat([]); } };
  const start = (row?: Unidad) => { setError(''); setEditing(row ?? null); setForm(row ? { clave: row.clave, descripcion: row.descripcion, unidad_sat_id: row.unidad_sat_id, activo: row.activo } : empty); setOpen(true); };
  const save = async () => { try { setError(''); if (editing) await actualizarUnidad(editing.id, form); else await crearUnidad(form); setOpen(false); await load(); } catch (e) { setError(e instanceof Error ? e.message : 'No se pudo guardar'); } };
  const remove = async (row: Unidad) => { if (!window.confirm(`¿Eliminar ${row.descripcion}?`)) return; try { await eliminarUnidad(row.id); await load(); } catch (e) { setError(e instanceof Error ? e.message : 'No se pudo eliminar'); } };
  const selected = sat.find((x) => x.id === form.unidad_sat_id) ?? null;
  return <Box><Stack direction="row" justifyContent="space-between" alignItems="center" mb={2}><Box><Typography variant="h5" fontWeight={700}>Unidades</Typography><Typography variant="body2">Catálogo operativo de la empresa activa.</Typography></Box><Button variant="contained" startIcon={<Add />} onClick={() => start()}>Nueva unidad</Button></Stack>{error && <Alert severity="error" sx={{ mb: 2 }} onClose={() => setError('')}>{error}</Alert>}<Paper><Table><TableHead><TableRow><TableCell>Clave</TableCell><TableCell>Nombre</TableCell><TableCell>Unidad SAT</TableCell><TableCell>Activa</TableCell><TableCell align="right">Acciones</TableCell></TableRow></TableHead><TableBody>{rows.map((r) => <TableRow key={r.id}><TableCell>{r.clave}</TableCell><TableCell>{r.descripcion}</TableCell><TableCell>{r.unidad_sat_clave} — {r.unidad_sat_descripcion}</TableCell><TableCell><Switch checked={r.activo} onChange={() => void actualizarUnidad(r.id, { clave: r.clave, descripcion: r.descripcion, unidad_sat_id: r.unidad_sat_id, activo: !r.activo }).then(load)} /></TableCell><TableCell align="right"><IconButton onClick={() => start(r)}><Edit /></IconButton><IconButton onClick={() => void remove(r)}><Delete /></IconButton></TableCell></TableRow>)}</TableBody></Table></Paper><Dialog open={open} onClose={() => setOpen(false)} fullWidth maxWidth="sm"><DialogTitle>{editing ? 'Editar unidad' : 'Nueva unidad'}</DialogTitle><DialogContent><Stack spacing={2} mt={1}><TextField label="Nombre" value={form.descripcion} onChange={(e) => setForm({ ...form, descripcion: e.target.value })} required /><TextField label="Clave operativa / abreviatura" value={form.clave} onChange={(e) => setForm({ ...form, clave: e.target.value })} required /><Autocomplete options={sat} value={selected} isOptionEqualToValue={(option, value) => option.id === value.id} filterOptions={(x) => x} getOptionLabel={(x) => `${x.clave} — ${x.descripcion}`} onOpen={() => void searchSat('')} onInputChange={(_, v, reason) => { if (reason === 'input') void searchSat(v); }} onChange={(_, v) => setForm({ ...form, unidad_sat_id: v?.id ?? 0 })} renderInput={(params) => <TextField {...params} label="Unidad SAT" required />} /></Stack></DialogContent><DialogActions><Button onClick={() => setOpen(false)}>Cancelar</Button><Button variant="contained" onClick={() => void save()}>Guardar</Button></DialogActions></Dialog></Box>;
}
