"use client"
import { useCallback,useEffect,useMemo,useState } from "react"
import { ChevronLeft,ChevronRight,Plus } from "lucide-react"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { ActividadRow } from "@/components/actividad/actividad-row"
import { CerrarActividadDrawer } from "@/components/actividad/cerrar-actividad-drawer"
import { diasDeSemana,sumarDias } from "@/lib/calendario-fechas"
import { useRealWork } from "@/lib/real-work-store"
import type { Actividad } from "../../../services/compassService"
const localDate=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`}
const localIso=(date:string,time="00:00")=>new Date(`${date}T${time}:00`).toISOString()
const dateKey=(iso:string)=>{const d=new Date(iso);return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`}
export function CalendarioView(){
 const [fecha,setFecha]=useState(localDate);const dias=useMemo(()=>diasDeSemana(fecha),[fecha]);const {actividades,frentes,loading,error,loadActividades,loadFrentes,crearActividad}=useRealWork()
 const [selected,setSelected]=useState<Actividad|null>(null);const [creating,setCreating]=useState<string|null>(null);const [titulo,setTitulo]=useState("");const [inicio,setInicio]=useState("09:00");const [fin,setFin]=useState("10:00");const [frente,setFrente]=useState("")
 const load=useCallback(()=>loadActividades({fecha_inicio:localIso(dias[0]),fecha_fin:localIso(sumarDias(dias[6],1))}),[dias,loadActividades])
 useEffect(()=>{void loadFrentes()},[loadFrentes]);useEffect(()=>{void load()},[load])
 async function save(){if(!creating||!titulo.trim())return;await crearActividad({titulo:titulo.trim(),frente_id:frente?Number(frente):null,tarea_id:null,inicio_programado:localIso(creating,inicio),fin_programado:localIso(creating,fin)});setCreating(null);setTitulo("");await load()}
 return <div className="flex flex-col gap-6 md:gap-8"><header><h1 className="font-heading text-3xl tracking-tight">Calendario</h1><p className="mt-2 text-sm text-muted-foreground">El registro real de cómo se usó el tiempo, día por día.</p></header><div className="flex items-center justify-between rounded-2xl border border-border bg-card px-4 py-3"><button onClick={()=>setFecha(f=>sumarDias(f,-7))}><ChevronLeft className="size-4"/></button><p className="text-xs text-muted-foreground">Semana del {dias[0]}</p><button onClick={()=>setFecha(f=>sumarDias(f,7))}><ChevronRight className="size-4"/></button></div>{error&&<p className="text-sm text-destructive">{error}</p>}{loading&&actividades.length===0&&<p className="text-sm text-muted-foreground">Cargando calendario…</p>}<div className="grid gap-3 md:grid-cols-7">{dias.map(dia=><section key={dia} className="min-h-40 rounded-2xl border border-border bg-card p-2"><div className="mb-2 flex items-center justify-between"><span className="text-xs font-medium">{new Date(`${dia}T12:00:00`).toLocaleDateString("es-MX",{weekday:"short",day:"numeric"})}</span><button onClick={()=>setCreating(dia)} aria-label="Agendar"><Plus className="size-3.5 text-muted-foreground"/></button></div>{actividades.filter(a=>dateKey(a.inicio_programado)===dia&&a.estado!=="cancelada").map(a=><ActividadRow key={a.id} actividad={a} onSelect={setSelected}/>)}</section>)}</div><CerrarActividadDrawer actividad={selected} open={!!selected} onOpenChange={v=>!v&&setSelected(null)} onSaved={load}/>{creating&&<div className="fixed inset-0 z-[1300] flex items-end justify-center bg-black/20 sm:items-center sm:p-4" onMouseDown={e=>e.target===e.currentTarget&&setCreating(null)}><div className="w-full max-w-lg rounded-t-2xl border border-border bg-popover p-5 sm:rounded-2xl"><h2 className="font-heading text-xl">Nueva actividad</h2><p className="text-sm text-muted-foreground">{creating}</p><div className="mt-4 flex flex-col gap-3"><Input value={titulo} onChange={e=>setTitulo(e.target.value)} placeholder="Qué vas a hacer" autoFocus/><div className="grid grid-cols-2 gap-3"><Input type="time" value={inicio} onChange={e=>setInicio(e.target.value)}/><Input type="time" value={fin} onChange={e=>setFin(e.target.value)}/></div><select value={frente} onChange={e=>setFrente(e.target.value)} className="h-9 rounded-md border border-input bg-transparent px-3 text-sm"><option value="">Sin Frente</option>{frentes.map(f=><option key={f.id} value={f.id}>{f.nombre}</option>)}</select></div><div className="mt-5 flex justify-end gap-2"><Button variant="ghost" onClick={()=>setCreating(null)}>Cancelar</Button><Button onClick={()=>void save()} disabled={!titulo.trim()||fin<=inicio}>Agendar</Button></div></div></div>}</div>
}

